Avalara Fullqa/src/Conversica/objects/Contact.object
<CustomObject>
</CustomObject>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>SubType__c</fullName>
        <description>Update: IBST-9676</description>
        <formula>CASE(Account.RecordTypeId, &quot;01233000000Ue6l&quot;, &quot;Trustfile Bharat&quot;, &quot;012330000005hcF&quot;, &quot;Brazil&quot;, &quot;01233000000Udyw&quot;, &quot;Communications&quot;, &quot;01240000000Ubqg&quot;, &quot;Excise&quot;, &quot;01240000000Ubql&quot;, &quot;Excise&quot;, &quot;01233000000Ue4G&quot;, &quot;MyLodge&quot;, &quot;01233000000MIr9&quot;, &quot;CertCapture&quot;, &quot;012330000005hjV&quot;, &quot;Avalara Trustfile&quot;, &quot;01233000000MImx&quot;, &quot;EMEA&quot;, &quot;01233000000MIyU&quot;, &quot;SOHO&quot;, &quot;0120b0000005ip7&quot;, &quot;Included&quot;, &quot;AvaTax&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SubType</label>
        <type>Text</type>
    </fields>

FullQa New/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

FullQa New/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>PaymentTerms__c</fullName>
        <defaultValue>&quot;Due Upon Receipt of Invoice&quot;</defaultValue>
        <description>Allows a Sales Manager to add custom Payment Terms to a quote</description>
        <inlineHelpText>Allows a Sales Manager to add custom Payment Terms to a quote</inlineHelpText>
        <label>Payment Terms:</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Avalara Fullqa/src/classes/testQuoteUpdateOppTerms.cls
@isTest  (SeeAllData = true) 

private class testQuoteUpdateOppTerms{

    static testMethod void testQuoteUpdateOppTerms(){
   
     	Account acct = new Account();
        acct.Name='Test Account';
        acct.Industry = 'Automotive';
        acct.Type__c='Customer';
        acct.BillingStreet='100 Ravine Lane NE';
        acct.BillingCity = 'Bainbridge Island';
        acct.BillingState = 'WA';
        acct.BillingPostalCode = '98110';
        insert acct;

        Contact con = makeContact(acct);
        //see all data is on, this is pulling a random account.
        //Account a = [select Id from Account limit 1];
        //Maks Demin 8/15
        Account a = [select Id from Account where Id = :acct.Id limit 1];
        //Maks Demin 8/15 added to try to fix when deploying to prod
        /*
        testQuoteUpdateOppTerms.testQuoteUpdateOppTerms(), Details: System.DmlException: Update failed. 
        First exception on row 0 with id 0014000000H0Kn4AAF; 
        first error: FIELD_FILTER_VALIDATION_EXCEPTION, 
        The contact must exist on this account: [Partner_Commissions_Contact__c] 
        Class.testQuoteUpdateOppTerms.testQuoteUpdateOppTerms: line 21, column 1
        */ 
        a.Partner_Commissions_Contact__c = con.Id;
        update a;        
        Opportunity o = new Opportunity(); 
        OpportunityLineItem ol = new OpportunityLineItem();
        PricebookEntry pbID = [select Id from PricebookEntry where IsActive=TRUE and Pricebook2.Name='GP SKU\'s' and CurrencyIsoCode = 'USD' limit 1];
  
  
        o.AccountId = a.Id;
        o.Name = 'test';
        o.StageName = 'Prospecting';
        o.CloseDate = date.today();
        o.Type = 'Existing';
        o.SubType__c = 'Epicor';
        o.Amount = 0;
        o.CurrencyIsoCode = 'USD';
        insert o;
        
        ol.OpportunityId = o.Id;
        ol.Quantity = 1;
        ol.TotalPrice__c =3.00;
        ol.UnitPrice = 2.00;
        ol.PricebookEntryId = pbId.Id;
        
        insert ol;
 
        Opportunity targetOpp =  [select Id, Quote_Payment_Terms__c from Opportunity where id=:o.Id];
        
        Quote quo = new Quote();
        quo.OpportunityId = targetOpp.Id;
        quo.Name = 'Unit Test';
        quo.PaymentTerms__c = 'Initial Terms';
        
        insert quo;
        
        Quote insertedQuo = [select Id, PaymentTerms__c from Quote where Name='Unit Test' limit 1];
        Opportunity insertedOpp = [select Id, Quote_Payment_Terms__c from Opportunity where id=:o.Id];
        
        insertedOpp.SyncedQuoteId = insertedQuo.Id;
        
        update insertedOpp;
 
        System.assert(insertedQuo.PaymentTerms__c == 'Initial Terms');  
        insertedQuo.PaymentTerms__c = 'New Terms';
        update insertedQuo;

       	Opportunity updatedOpp = [select Id, Quote_Payment_Terms__c from Opportunity where id=:o.Id];
        System.assert(updatedOpp.Quote_Payment_terms__c=='New Terms');

    }
      /**
   * Insert a test contact associated with an account in the db
   */
  public static Contact makeContact(Account testAcc) {

    Contact testContact = new Contact();

    testContact.FirstName = 'firstname';
    testContact.LastName = 'lastname';
    testContact.Email = 'email@mail.me';

    testContact.AccountId = testAcc.Id;

    insert testContact;
    return testContact;
  }
}