Avalara Fullqa/src/Conversica/objects/Contact.object
<CustomObject>
</CustomObject>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Partner_Launch_User_Requests__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Launch User Requests</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>

Prod/src/objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partner Launch User Requests</label>
    <nameField>
        <displayFormat>R-{0}</displayFormat>
        <label>Request No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Avalara Fullqa/src/classes/AvalaraNewUserCtrl.cls
public class AvalaraNewUserCtrl {

    public Request__c req {get;set;}
    public boolean isSuccess {get;set;}
    
    public AvalaraNewUserCtrl(){
        req = new  Request__c();
        isSuccess = false;       
    }
    
    public pageReference insertRequest(){
        try{
            insert req;
            insert new Contact(
                FirstName = req.First_Name__c,
                LastName = req.Last_Name__c,
                Email = req.Email__c,
                Partner_Launch_User_Requests__c = req.Id,
                AccountId = [SELECT Id,AccountId FROM User WHERE Id =:UserInfo.getUserId()].AccountId
            );
            
            isSuccess = true;
        }
        catch(exception e){
            apexpages.addmessages(e);
        }
        return null;       
    }
    
   
}