Prod/src/objects/Account_Statistics__c.object
<CustomObject>
    <description>Used to track all AvaTax prod and dev admin console accounts and associated milestones</description>
    <fields>
        <fullName>AccountID__c</fullName>
        <externalId>true</externalId>
        <label>Account ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Statistics</relationshipLabel>
        <relationshipName>Account_Statistics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AvaTaxAccountID__c</fullName>
        <formula>TEXT( AccountID__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AvaTax Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_SubType__c</fullName>
        <label>System SubType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TRUSTFILE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <label>System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DEV</fullName>
                </value>
                <value>
                    <fullName>PROD</fullName>
                </value>
                <value>
                    <fullName>TRUSTFILE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Statistics</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Statistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Compliance_Item__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Compliance Variance Items</relationshipLabel>
        <relationshipName>Compliance_Variance_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AvaTaxAccountIdNew__c</fullName>
        <label>AvaTaxAccountIdNew</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Compliance Variance Item</label>
    <nameField>
        <displayFormat>cvi{0000}</displayFormat>
        <label>Compliance Variance Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Variance Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev/src/classes/ComplianceVarianceItemTriggerHandler.cls
public class ComplianceVarianceItemTriggerHandler extends TriggerHandler {
      //Trigger Handler Methods
    protected override void beforeInsert(){
    	 beforeInsertUpdate();
    }
    	
      protected override void beforeUpdate(){
            beforeInsertUpdate();
    }
    public void beforeInsertUpdate(){
    	    Map<Decimal,Compliance_Item__c> mapComplianceAccountIDs=new  Map<Decimal,Compliance_Item__c>();
            for(Compliance_Item__c cVI :(List<Compliance_Item__c>)Trigger.new){
            	if(/*String.isNotBlank(cVI.name) &&*/ cVI.AvaTaxAccountIdNew__c!=null && cVI.Account__c==null){
            	    mapComplianceAccountIDs.put(cVI.AvaTaxAccountIdNew__c,cVI);
            	}
            }
        
	            Map<Decimal,Id> mapAccountIDs=new Map<Decimal,Id>();
	            for(Account_Statistics__c accStat:[Select Id,Account__c,AvaTaxAccountID__c,AccountID__c
	                                From Account_Statistics__c Where AccountID__c=:mapComplianceAccountIDs.keySet() AND Account__r.ActiveCustomer__c=true 
	                                AND System_SubType__c != 'TRUSTFILE' AND System__c='PROD']){
	                mapAccountIDs.put(accStat.AccountID__c,accStat.Account__c);
	            }
	            for(Compliance_Item__c cVI :(List<Compliance_Item__c>)Trigger.new){
	               if(mapAccountIDs.containsKey(cVI.AvaTaxAccountIdNew__c)){
	            	   mapComplianceAccountIDs.get(cVI.AvaTaxAccountIdNew__c).Account__c=mapAccountIDs.get(cVI.AvaTaxAccountIdNew__c);
	            	}
	            }
           
    }
    /*
    protected override void beforeUpdate(){
            beforeInsertUpdate();
    }
    protected override void afterInsert(){
        if(!afterInsertUpdateExecuted){
            afterInsertUpdate();
        }
    }
    
    protected override void beforeDelete(){}

    protected override void afterDelete(){}

    protected override void afterUndelete(){}
    */
}