Prod/src/objects/Account_Profile__c.object
<CustomObject>
    <description>Used to track partner specific KPI&apos;s associated with a given (customer) account record</description>
    <fields>
        <fullName>Account_Profile__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; Id, &quot;Command OF The Message&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Profile</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>https://jira.avalara.com/browse/ITBSE-1030</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Account Profiles</relationshipLabel>
        <relationshipName>Prospect_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Profile</label>
    <nameField>
        <label>Account Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Profiles</pluralLabel>
    <recordTypes>
        <fullName>Prospect_Profile_1_0</fullName>
        <active>true</active>
        <description>https://jira.avalara.com/browse/ITBSE-1030</description>
        <label>Prospect Profile 1.0</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Avalara Fullqa/src/classes/AccountProfile.cls
public class AccountProfile {

public Account_Profile__c accPro { get; set; }

public AccountProfile (ApexPages.StandardController ctrl) {
    String opportuniyID =(String)ctrl.getRecord().get('Id');
    id prosProRecrdtypeid = [Select Id from RecordType where DeveloperName='Prospect_Profile_1_0' limit 1].Id;
    String query = 'SELECT ';
    for(Schema.FieldSetMember f : this.getFields()) {
        query += f.getFieldPath() + ', ';
    }
    query += 'Id FROM Account_Profile__c where Opportunity__c =: opportuniyID AND recordtypeid= :prosProRecrdtypeid ';
    accPro = (Account_Profile__c)Database.query(query);
}

    public List<Schema.FieldSetMember> getFields() {
        return SObjectType.Account_Profile__c.FieldSets.Command_of_The_Message_Prospect_Profile.getFields();
    }
}