Prod/src/objects/Account_Statistics__c.object
<CustomObject>
    <description>Used to track all AvaTax prod and dev admin console accounts and associated milestones</description>
    <fields>
        <fullName>AccountID__c</fullName>
        <externalId>true</externalId>
        <label>Account ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Statistics</relationshipLabel>
        <relationshipName>Account_Statistics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <label>System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DEV</fullName>
                </value>
                <value>
                    <fullName>PROD</fullName>
                </value>
                <value>
                    <fullName>TRUSTFILE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Statistics</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Statistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Compliance_Item__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Compliance Variance Items</relationshipLabel>
        <relationshipName>Compliance_Variance_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AvaTaxAccountIdNew__c</fullName>
        <label>AvaTaxAccountIdNew</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Compliance Variance Item</label>
    <nameField>
        <displayFormat>cvi{0000}</displayFormat>
        <label>Compliance Variance Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Variance Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FullQA/src/classes/ComplianceVarianceItemTriggerHandlerTest.cls
@isTest
public class ComplianceVarianceItemTriggerHandlerTest {
  //IBST-16111
  static testMethod void testCVIAccUpdate() {
    	 Test.startTest();
	    	//Create an account
	       Id customerAccountTypeId=[Select Id from RecordType where DeveloperName='Customer_Account_Type' limit 1].Id;
	       Account acc = TestUtil.createAccount(customerAccountTypeId,1,false)[0];
	       acc.ActiveCustomer__c=true;
           acc.ActiveSubscriptionCount__c = 5;
           acc.CARR_Override__c = 50;
           insert acc;
      
	       //Create Account Statistics
           Account_Statistics__c accStat= TestUtil.createAccountStatistics(acc.id,1,false)[0];
           accStat.AccountID__c = 2000060838;
           accStat.System__c='PROD';
           insert accStat;
	       
	       //create Compliance Variance Item
	       Compliance_Item__c cVI = TestUtil.createComplianceItem(1,false)[0];
           cVI.AvaTaxAccountIdNew__c=2000060838;
	       insert cVI;
           
           Compliance_Item__c cIAcc = [Select Account__c from Compliance_Item__c where id=:cVI.id];
           System.assertEquals(cIAcc.Account__c, acc.id);
           
      Test.stopTest();
    }
}