Prod/src/objects/Account_Profile__c.object
<CustomObject>
    <description>Used to track partner specific KPI&apos;s associated with a given (customer) account record</description>
    <fields>
        <fullName>Account_Profile__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; Id, &quot;Command OF The Message&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Profile</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Profiles</relationshipLabel>
        <relationshipName>Account_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>https://jira.avalara.com/browse/ITBSE-1030</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Account Profiles</relationshipLabel>
        <relationshipName>Prospect_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Profile</label>
    <nameField>
        <label>Account Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Profiles</pluralLabel>
    <recordTypes>
        <fullName>Prospect_Profile_1_0</fullName>
        <active>true</active>
        <description>https://jira.avalara.com/browse/ITBSE-1030</description>
        <label>Prospect Profile 1.0</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev/src/classes/AccountProfileTest.cls
@isTest
private class AccountProfileTest {
    //BATS-355 ITBSE-1303
    static testMethod void testCoMPage() {
    	 Test.startTest();
	    	//Create an account
	    	Id customerAccountTypeId=[Select Id from RecordType where DeveloperName='Customer_Account_Type' limit 1].Id;
	       Account acc = TestUtil.createAccount(customerAccountTypeId,1,true)[0];
	       
	       //Create Opportunity
	       Id defaultOppRecTypeId=[Select Id from RecordType where DeveloperName='Default_OppRecType' limit 1].Id;
           Opportunity o = TestUtil.createOpportunity(acc.id,defaultOppRecTypeId,1,true)[0];
	       
	       //create Account Profile
	       id prosProRecrdtypeid = [Select Id from RecordType where DeveloperName='Prospect_Profile_1_0' limit 1].Id;
	       Account_Profile__c accPro = TestUtil.createAccountProfile(1,false,acc)[0];
	       accPro.recordtypeID = prosProRecrdtypeid;
	       accPro.Opportunity__c = o.id;
	       //accPro.Account__c = acc.id;
	       insert accPro;
	       
           //Add the page to the test context
	       PageReference testPage = Page.CoMPage;
	       testPage.getParameters().put('id', String.valueOf(o.Id));
           Test.setCurrentPage(testPage);

	        // Create a controller for the book	
           ApexPages.StandardController sc = new ApexPages.StandardController(o); 
           
           //Create an extension with the controller
	       AccountProfile accExtenstion = new AccountProfile(sc);
 	       
      Test.stopTest();
    }
}