Prod/src/objects/Ava_In_Maintenance__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting for redirect guest user to in maintenance page</description>
    <fields>
        <fullName>Turn_Off_Site_for_Maintenance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this attribute if the site is in maintenance</description>
        <label>Turn Off Site for Maintenance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>URL_for_redirection__c</fullName>
        <description>The URL use to redirect the site for maintenance</description>
        <label>URL for redirection</label>
        <type>Url</type>
    </fields>
    <label>Ava In Maintenance</label>
</CustomObject>

FullQA/src/classes/cc_Ava_ctrl_header.cls
global with sharing class cc_Ava_ctrl_header {
	public Boolean isRedirect {get;private set;}
	public String redirectLoc {get;private set;}

	public cc_Ava_ctrl_header(){
		Map<String,Ava_In_Maintenance__c> inMaintenanceSetting = Ava_In_Maintenance__c.getAll();
		Ava_In_Maintenance__c avaDevEnv = inMaintenanceSetting.get('Ava Dev Environment');
		isRedirect = avaDevEnv.Turn_Off_Site_for_Maintenance__c;
		redirectLoc = (String)avaDevEnv.URL_for_redirection__c;
	}

}