Prod/src/objects/Ava_In_Maintenance__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting for redirect guest user to in maintenance page</description>
    <fields>
        <fullName>Turn_Off_Site_for_Maintenance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this attribute if the site is in maintenance</description>
        <label>Turn Off Site for Maintenance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>URL_for_redirection__c</fullName>
        <description>The URL use to redirect the site for maintenance</description>
        <label>URL for redirection</label>
        <type>Url</type>
    </fields>
    <label>Ava In Maintenance</label>
</CustomObject>

Avalara Fullqa/src/classes/cc_Ava_ctrl_headerTest.cls
@isTest
public class cc_Ava_ctrl_headerTest {    
    @testSetup
    static void testSetup() { 
        Ava_In_Maintenance__c avaDevTestEnv= new Ava_In_Maintenance__c(Name='Ava Dev Environment',Turn_Off_Site_for_Maintenance__c=true,URL_for_redirection__c='test.example.com');
        insert avaDevTestEnv;
    }
    @isTest static void headerTest() { 
        Test.startTest();
		cc_Ava_ctrl_header ctrler= new cc_Ava_ctrl_header();
        Test.stopTest();
        System.assert(ctrler.isRedirect);
        System.assertEquals('test.example.com', ctrler.redirectLoc);
    }
}