Prod/src/objects/AvaConfig__c.object
<CustomObject>
    <description>This object is being used to store different config to be used in code. Do not give permission on this object other than admin</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of config</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Survey Action Rule</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value1__c</fullName>
        <label>Value1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Value2__c</fullName>
        <label>Value2</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>AvaConfig</label>
    <nameField>
        <label>AvaConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AvaConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/SurveyResponse__c.object
<CustomObject>
    <description>Used to map in responses to Clicktools surveys</description>
    <fields>
        <fullName>Call_to_Action__c</fullName>
        <description>This field is being populated through code and AvaConfig rules where type is Survey Action Rule</description>
        <label>Call to Action</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <label>Survey Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Avalara Fullqa/src/classes/SurveyResponseTriggerHandlerTest.cls
@isTest
private class SurveyResponseTriggerHandlerTest {

    static testMethod void testUpdateSurveyResponse() {
        AvaConfig__c ac=new AvaConfig__c(Type__c='Survey Action Rule',Active__c=true,Value1__c='Select Id From SurveyResponse__c Where Name=\'Test Survey\' ',Value2__c='Test');
        insert ac;
        Test.startTest();
        SurveyResponse__c sr=new SurveyResponse__c(Name='Test Survey');
        insert sr;
        TriggerHandler.clearBypass('SurveyResponseTriggerHandler');
         update sr; 
        Test.stopTest();
        sr=[Select Id, Call_to_Action__c From SurveyResponse__c Where Id=:sr.Id];
        System.assertEquals('Test',sr.Call_to_Action__c);
              
    }
}