Prod/src/objects/Badge__c.object
<CustomObject>
    <fields>
        <fullName>Functional_Matrix_Ext_Id__c</fullName>
        <externalId>true</externalId>
        <label>Functional Matrix Ext Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Functional_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Matrix</label>
        <referenceTo>Functional_Matrix__c</referenceTo>
        <relationshipLabel>Badges</relationshipLabel>
        <relationshipName>Badges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <formula>CASE(Type__c, 
&quot;Sales Tax&quot;, 1,
&quot;Refunds&quot;, 2,
&quot;Address Validation&quot;, 3,
&quot;VAT&quot;, 4,
&quot;Customs Duty &amp; Import Tax&quot;, 5,
&quot;GST&quot;, 6,
&quot;Brazil&quot;, 7,
&quot;POS&quot;, 8,
&quot;MultiTax&quot;, 9,
&quot;Extractor&quot;, 10,
&quot;Document Management&quot;, 11,
&quot;Communication&quot;, 12,
&quot;Lodging&quot;, 13,
&quot;Excise&quot;, 14,
&quot;Provisioning&quot;,15,
null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Badges</relationshipLabel>
        <relationshipName>Badges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Badge</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Badge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Connector__c.object
<CustomObject>
    <description>Used to track all Avalara connectors and associated data</description>
    <fields>
        <fullName>External_Id__c</fullName>
        <label>External_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Connector</label>
    <nameField>
        <label>Connector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Connector_KB__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Address_Validation_Functional_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address Validation Functional Matrix</label>
        <referenceTo>Functional_Matrix__c</referenceTo>
        <relationshipLabel>Connector KB (Address Validation Functional Matrix)</relationshipLabel>
        <relationshipName>Connector_KB_AV</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comm_Functional_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comm Functional Matrix</label>
        <referenceTo>Functional_Matrix__c</referenceTo>
        <relationshipLabel>Connector KB (Comm Functional Matrix)</relationshipLabel>
        <relationshipName>Connector_KB_Comm</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Connector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Connector</label>
        <referenceTo>Connector__c</referenceTo>
        <relationshipLabel>Connector KB</relationshipLabel>
        <relationshipName>Connector_KB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Tax_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Tax Matrix</label>
        <referenceTo>Functional_Matrix__c</referenceTo>
        <relationshipLabel>Connector KB</relationshipLabel>
        <relationshipName>Connector_KB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Connector KB</relationshipLabel>
        <relationshipName>Connector_KB</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Connector KB</label>
    <pluralLabel>Connector KB</pluralLabel>
</CustomObject>

Prod/src/objects/Functional_Checklist__c.object
<CustomObject>
    <description>Used to track connector development milestones related to a specific version of a connector</description>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Functional Checklists</relationshipLabel>
        <relationshipName>Functional_Checklists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Functional Checklist</label>
    <nameField>
        <label>Functional Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functional Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Functional_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Functional Matrix</relationshipLabel>
        <relationshipName>Functional_Matrix</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Functional Matrix</label>
    <nameField>
        <displayFormat>FM-{000000}</displayFormat>
        <label>Functional Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Functional_Matrix_Requirement__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Functional_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Matrix</label>
        <referenceTo>Functional_Matrix__c</referenceTo>
        <relationshipLabel>Functional Matrix Requirements</relationshipLabel>
        <relationshipName>Functional_Matrix_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Functional Matrix Requirements</label>
    <nameField>
        <label>Functional Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functional Matrix Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Version__c.object
<CustomObject>
    <description>Used as an associated related list for the connector object to track the version associated with a given connector</description>
    <fields>
        <fullName>Connector__c</fullName>
        <label>Connector</label>
        <referenceTo>Connector__c</referenceTo>
        <relationshipLabel>Versions</relationshipLabel>
        <relationshipName>Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Parent_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Sub Versions</relationshipLabel>
        <relationshipName>Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>ITBSE-973</description>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Version_KB__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Version KB</label>
        <referenceTo>Solution</referenceTo>
        <relationshipLabel>Versions</relationshipLabel>
        <relationshipName>Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Version</label>
    <nameField>
        <label>Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev/src/classes/VersionClone.cls
//https://jira.avalara.com/browse/ITBSE-973?filter=-1
public with sharing class VersionClone {
	public Version__c majorVersion{get;set;}
	public Version__c subVersion{get;set;}
    public VersionClone(ApexPages.StandardController stdController) {
        this.majorVersion = (Version__c)stdController.getRecord();
        this.subVersion=new Version__c();
    }
    public PageReference saveSubVersion(){
    		FunctionalMatrixHandler.doNotExecuteTrigger=true;
    		this.majorVersion=Database.query('Select Connector__r.Name,Version_KB__r.SolutionName,'+Utility.getSObjectFields('Version__c')+',(Select '+Utility.getSObjectFields('Badge__c')+' From Badges__r),(Select id From Connector_KB__r),(Select '+Utility.getSObjectFields('Functional_Checklist__c')+' From Functional_Checklists__r),(Select '+Utility.getSObjectFields('Functional_Matrix__c')+' From 	Functional_Matrix__r) From Version__c Where Id=\''+majorVersion.Id+'\' ');
    		String versionName=this.subVersion.Name;
    		Decimal sortOrder=this.subVersion.Sort_Order__c;
    		this.subVersion=this.majorVersion.clone();
    		this.subVersion.Parent_Version__c=this.majorVersion.Id;
    		this.subVersion.Name=versionName;
    		this.subVersion.Sort_Order__c=sortOrder;
    		insert this.subVersion;
    		
    		List<Functional_Checklist__c> listFC=new List<Functional_Checklist__c>();
    		for(Functional_Checklist__c fc:this.majorVersion.Functional_Checklists__r){
    			Functional_Checklist__c clonedFC=fc.clone();
    			clonedFC.Version__c=this.subVersion.Id;
    			listFC.add(clonedFC);
    		}
    		insert listFC;
    		
    		Map<Id,Functional_Matrix__c> fmMap=new Map<Id,Functional_Matrix__c>();
    		for(Functional_Matrix__c fm:this.majorVersion.Functional_Matrix__r){
    			Functional_Matrix__c clonedFM=fm.clone();
    			clonedFM.Version__c=this.subVersion.Id;
    			fmMap.put(fm.Id,clonedFM);
    		}
    		insert fmMap.values();    		
    		
    		List<Badge__c> listBadges=new List<Badge__c>();
    		for(Badge__c b:this.majorVersion.Badges__r){
    			Badge__c clonedBadge=b.clone();
    			clonedBadge.Version__c=this.subVersion.Id;
    			clonedBadge.Functional_Matrix_Ext_Id__c=null;
    			clonedBadge.Functional_Matrix__c=null;
    			if(b.Functional_Matrix__c!=null && fmMap.containsKey(b.Functional_Matrix__c)){
    				clonedBadge.Functional_Matrix__c=fmMap.get(b.Functional_Matrix__c).Id;
    				//clonedBadge.Functional_Matrix_Ext_Id__c=fmMap.get(b.Functional_Matrix__c).Id;
    			}
    			listBadges.add(clonedBadge);
    		}
    		insert listBadges;
    		
		List<Functional_Matrix_Requirement__c> listFMROld=Database.query('Select '+Utility.getSObjectFields('Functional_Matrix_Requirement__c')+' From Functional_Matrix_Requirement__c Where 	Functional_Matrix__r.Version__c=\''+majorVersion.Id+'\' ');
		List<Functional_Matrix_Requirement__c> listFMR=new List<Functional_Matrix_Requirement__c>();  
		for(Functional_Matrix_Requirement__c fmr:listFMROld){
			Functional_Matrix_Requirement__c clonedFMR=fmr.clone();
			clonedFMR.Functional_Matrix__c=null;
			clonedFMR.External_Id__c=null;
			if(fmr.Functional_Matrix__c!=null && fmMap.containsKey(fmr.Functional_Matrix__c)){
				clonedFMR.Functional_Matrix__c=fmMap.get(fmr.Functional_Matrix__c).Id;
				//clonedFMR.External_Id__c=fmMap.get(fmr.Functional_Matrix__c).Id;				
			}
			listFMR.add(clonedFMR);
		}  
		insert listFMR;		
    		
    		List<Connector_KB__kav> oldCKBIDs=new List<Connector_KB__kav>();
    		oldCKBIDs.addAll(this.majorVersion.Connector_KB__r);
    		List<Connector_KB__kav> listOldCKB=Database.query('select '+Utility.getSObjectFields('Connector_KB__kav')+' From Connector_KB__kav  Where Version__c=\''+majorVersion.Id+'\'  AND Id=:oldCKBIDs' );
    		List<Connector_KB__kav> listCKB=new List<Connector_KB__kav>();
    		for(Connector_KB__kav ckb:listOldCKB){
    			Connector_KB__kav clonedCKB=ckb.clone();
    			clonedCKB.Version__c=this.subVersion.Id;
    			clonedCKB.Title = this.subVersion.Name;
    			clonedCKB.UrlName = (this.majorVersion.Connector__r.Name + '-' +this.subVersion.Name + '-' + this.majorVersion.Version_KB__r.SolutionName).replaceAll('[^a-zA-Z0-9]',' ').normalizeSpace().toLowerCase().replaceAll(' ','-')+this.subVersion.Id;
    			clonedCKB.Address_Validation_Functional_Matrix__c=null;
    			clonedCKB.Comm_Functional_Matrix__c=null;
    			clonedCKB.Sales_Tax_Matrix__c=null;
    			if(ckb.Address_Validation_Functional_Matrix__c!=null  && fmMap.containsKey(ckb.Address_Validation_Functional_Matrix__c)){
    				clonedCKB.Address_Validation_Functional_Matrix__c=fmMap.get(ckb.Address_Validation_Functional_Matrix__c).Id;
    			}
    			if(ckb.Comm_Functional_Matrix__c!=null  && fmMap.containsKey(ckb.Comm_Functional_Matrix__c)){
    				clonedCKB.Comm_Functional_Matrix__c=fmMap.get(ckb.Comm_Functional_Matrix__c).Id;
    			}
    			if(ckb.Sales_Tax_Matrix__c!=null  && fmMap.containsKey(ckb.Sales_Tax_Matrix__c)){
    				clonedCKB.Sales_Tax_Matrix__c=fmMap.get(ckb.Sales_Tax_Matrix__c).Id;
    			}    			    			
    			listCKB.add(clonedCKB);
    		}
        if(!listCKB.isEmpty()){
            insert listCKB;
            FunctionalMatrixSyncUtil.publishNewArticle(new Map<Id, Connector_KB__kav>(listCKB).keySet());
        }
    		PageReference pr=new PageReference('/'+this.subVersion.Id);
    		pr.setRedirect(true);
    		return pr;
    }    
}