Prod/src/objects/Badge__c.object
<CustomObject>
    <fields>
        <fullName>Functional_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Matrix</label>
        <referenceTo>Functional_Matrix__c</referenceTo>
        <relationshipLabel>Badges</relationshipLabel>
        <relationshipName>Badges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <formula>CASE(Type__c, 
&quot;Sales Tax&quot;, 1,
&quot;Refunds&quot;, 2,
&quot;Address Validation&quot;, 3,
&quot;VAT&quot;, 4,
&quot;Customs Duty &amp; Import Tax&quot;, 5,
&quot;GST&quot;, 6,
&quot;Brazil&quot;, 7,
&quot;POS&quot;, 8,
&quot;MultiTax&quot;, 9,
&quot;Extractor&quot;, 10,
&quot;Document Management&quot;, 11,
&quot;Communication&quot;, 12,
&quot;Lodging&quot;, 13,
&quot;Excise&quot;, 14,
&quot;Provisioning&quot;,15,
null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Badges</relationshipLabel>
        <relationshipName>Badges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Badge</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Badge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Connector__c.object
<CustomObject>
    <description>Used to track all Avalara connectors and associated data</description>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Track the original developer of the code associated with this connector
Integrated: Yes 
Change: Level 1 
Custodian: Business Development / Greg Chapman</description>
        <inlineHelpText>Associate the account of the original developer of the code associated with this connector</inlineHelpText>
        <label>Author</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connectors (Author)</relationshipLabel>
        <relationshipName>Connectors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Managed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Track 30 day delta between old calc estimation and new calc estimation 
Integrated: No 
Change: Level 0 
Custodian: Business Development / Greg Chapman</description>
        <inlineHelpText>Associate the account currently managing / responsible for the code associated with this connector</inlineHelpText>
        <label>Managed By</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connectors (Managed By)</relationshipLabel>
        <relationshipName>Managed_Connectors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Connector</label>
    <nameField>
        <label>Connector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Functional_Checklist__c.object
<CustomObject>
    <description>Used to track connector development milestones related to a specific version of a connector</description>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Functional Checklists</relationshipLabel>
        <relationshipName>Functional_Checklists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Functional Checklist</label>
    <nameField>
        <label>Functional Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functional Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Functional_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <label>Sales Tax</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Badges_Achieved</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Functional Matrix</relationshipLabel>
        <relationshipName>Functional_Matrix</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Functional Matrix</label>
    <nameField>
        <displayFormat>FM-{000000}</displayFormat>
        <label>Functional Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Functional_Matrix_Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Functional_Matrix_Requirements_Config__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Matrix Requirements Config</label>
        <referenceTo>Functional_Matrix_Requirements_Config__c</referenceTo>
        <relationshipLabel>Functional Matrix Requirements</relationshipLabel>
        <relationshipName>Functional_Matrix_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Functional_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Matrix</label>
        <referenceTo>Functional_Matrix__c</referenceTo>
        <relationshipLabel>Functional Matrix Requirements</relationshipLabel>
        <relationshipName>Functional_Matrix_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Functional Matrix Requirements</label>
    <nameField>
        <label>Functional Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functional Matrix Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Functional_Matrix_Requirements_Config__c.object
<CustomObject>
    <fields>
        <fullName>Core_Type__c</fullName>
        <label>Core Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Core Sales Tax</fullName>
                </value>
                <value>
                    <fullName>Core Address Validation</fullName>
                </value>
                <value>
                    <fullName>Core Communication</fullName>
                </value>
                <value>
                    <fullName>Core Use Tax</fullName>
                </value>
                <value>
                    <fullName>Core Document Management</fullName>
                </value>
                <value>
                    <fullName>Core Lodging</fullName>
                </value>
                <value>
                    <fullName>Core Excise</fullName>
                </value>
                <value>
                    <fullName>Core Extractor TrustFile</fullName>
                </value>
                <value>
                    <fullName>Core Extractor AvaTax</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Functional Matrix Requirements Config</label>
    <nameField>
        <label>Functional Matrix Requirements Config Na</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functional Matrix Requirements Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FullQa New/src/objects/Solution.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Provide a brief explanation of what the solution is about or what the customer is trying to do.</description>
        <inlineHelpText>This field is used to describe the purpose and intent of the solution.  This is not a customer facing field that is viewable in the Public Knowledgebase.</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Avalara Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Avalara AvaTax</fullName>
                </value>
                <value>
                    <fullName>Avalara Returns</fullName>
                </value>
                <value>
                    <fullName>CertCapture</fullName>
                </value>
                <value>
                    <fullName>AvaTax APIs</fullName>
                </value>
                <value>
                    <fullName>Admin Console</fullName>
                </value>
                <value>
                    <fullName>Customer Center</fullName>
                </value>
                <value>
                    <fullName>Account Management</fullName>
                </value>
                <value>
                    <fullName>SST</fullName>
                </value>
                <value>
                    <fullName>Dynamics GP</fullName>
                </value>
                <value>
                    <fullName>Dynamics NAV</fullName>
                </value>
                <value>
                    <fullName>Dynamics AX</fullName>
                </value>
                <value>
                    <fullName>Dynamics RMS</fullName>
                </value>
                <value>
                    <fullName>Mas 90/200</fullName>
                </value>
                <value>
                    <fullName>Mas 500</fullName>
                </value>
                <value>
                    <fullName>Accpac</fullName>
                </value>
                <value>
                    <fullName>Sage Pro ERP</fullName>
                </value>
                <value>
                    <fullName>Netsuite</fullName>
                </value>
                <value>
                    <fullName>Quickbooks</fullName>
                </value>
                <value>
                    <fullName>OEM Connector</fullName>
                </value>
                <value>
                    <fullName>AvaLink</fullName>
                </value>
                <value>
                    <fullName>AvaLocal</fullName>
                </value>
                <value>
                    <fullName>AvaRates</fullName>
                </value>
                <value>
                    <fullName>Ebay Prostores</fullName>
                </value>
                <value>
                    <fullName>Peachtree</fullName>
                </value>
                <value>
                    <fullName>Avalara Onsite</fullName>
                </value>
                <value>
                    <fullName>ISPI</fullName>
                </value>
                <value>
                    <fullName>ISPI Rate Product</fullName>
                </value>
                <value>
                    <fullName>Laserbridge</fullName>
                </value>
                <value>
                    <fullName>CalcTx32.DLL</fullName>
                </value>
                <value>
                    <fullName>SalesTax II</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solution_Type__c</fullName>
        <description>These solution types help define the type of solutions created.</description>
        <label>Solution Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAQ</fullName>
                </value>
                <value>
                    <fullName>ERRMSG</fullName>
                </value>
                <value>
                    <fullName>TUTORIAL</fullName>
                </value>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>GO LIVE GUIDE</fullName>
                </value>
                <value>
                    <fullName>RELEASE NOTES</fullName>
                </value>
                <value>
                    <fullName>MONTHLY MAINTENANCE GUIDE</fullName>
                </value>
                <value>
                    <fullName>INTERNAL</fullName>
                </value>
                <value>
                    <fullName>OEM GUIDE</fullName>
                </value>
                <value>
                    <fullName>USER GUIDE</fullName>
                </value>
                <value>
                    <fullName>SOLUTION PARTNER</fullName>
                </value>
                <value>
                    <fullName>CHANNEL PARTNER</fullName>
                </value>
                <value>
                    <fullName>DEVELOPMENT PARTNER</fullName>
                </value>
                <value>
                    <fullName>AASP PARTNER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Prod/src/objects/Version__c.object
<CustomObject>
    <description>Used as an associated related list for the connector object to track the version associated with a given connector</description>
    <fields>
        <fullName>Connector__c</fullName>
        <label>Connector</label>
        <referenceTo>Connector__c</referenceTo>
        <relationshipLabel>Versions</relationshipLabel>
        <relationshipName>Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Version_KB__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Version KB</label>
        <referenceTo>Solution</referenceTo>
        <relationshipLabel>Versions</relationshipLabel>
        <relationshipName>Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Version</label>
    <nameField>
        <label>Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/classes/VersionCloneTest.cls
@isTest
private class VersionCloneTest {
    @testSetup
    static void setup(){
        Account acc = new Account(
            Name = 'Test Account'
        );
        insert acc;
        
        Connector__c c = new Connector__c(
            Name = 'Test Connector',
            Author__c = acc.Id,
            Managed_By__c = acc.Id
        );
        insert c;
        
        Solution sol = new Solution(
            SolutionName = 'Solution 1',
            Solution_Type__c  = 'FAQ',
            Description__c = 'Solution Description',
            Product__c = 'Avalara AvaTax'
        );
        insert sol;
        
        Version__c ver = new Version__c(
            Name = 'Text version',
            Connector__c = c.Id,
            Version_KB__c = sol.Id
        );
        insert ver; 
        Functional_Matrix__c fm = new Functional_Matrix__c(
            Version__c = ver.Id,
            RecordTypeId = Schema.SObjectType.Functional_Matrix__c.getRecordTypeInfosByName().get('Core Sales Tax').getRecordTypeId(),
            Sales_Tax__c = 'Certified'
        );
        insert fm;
        List<Functional_Matrix_Requirement__c> req = new List<Functional_Matrix_Requirement__c>();
        req.add(new Functional_Matrix_Requirement__c(Name='test req',Functional_Matrix__c=fm.Id));
        insert req;
		//Functional_Matrix_Requirements_Config__c cf = new Functional_Matrix_Requirements_Config__c(
		//	Core_Type__c = 'Core Sales Tax'
		//);
		//insert cf;
		Functional_Checklist__c fc=new Functional_Checklist__c(Name='fc',Version__c=ver.Id);
        insert fc;
        Badge__c b = new Badge__c(Version__c = ver.Id);
        insert b;        
    }
    static testMethod void myUnitTest() {
        Version__c v = [SELECT Id FROM Version__c LIMIT 1];
		PageReference pageRef = Page.VersionClone;
        Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('Id',v.id);
		ApexPages.StandardController stdV = new ApexPages.StandardController(v);        
        VersionClone vc=new VersionClone(stdV);
        vc.subVersion.Name='Test';
        vc.subVersion.Sort_Order__c=1.1;
        vc.saveSubVersion();
        Version__c subV = [SELECT Id,Name FROM Version__c Where Parent_Version__c=:v.Id];
        system.assertEquals('Test', subV.Name);
    }
}