Prod/src/objects/Badge__c.object
<CustomObject>
    <fields>
        <fullName>Date_Achieved__c</fullName>
        <label>Date Achieved</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Functional_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Matrix</label>
        <referenceTo>Functional_Matrix__c</referenceTo>
        <relationshipLabel>Badges</relationshipLabel>
        <relationshipName>Badges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <formula>CASE(Type__c, 
&quot;Sales Tax&quot;, 1,
&quot;Refunds&quot;, 2,
&quot;Address Validation&quot;, 3,
&quot;VAT&quot;, 4,
&quot;Customs Duty &amp; Import Tax&quot;, 5,
&quot;GST&quot;, 6,
&quot;Brazil&quot;, 7,
&quot;POS&quot;, 8,
&quot;MultiTax&quot;, 9,
&quot;Extractor&quot;, 10,
&quot;Document Management&quot;, 11,
&quot;Communication&quot;, 12,
&quot;Lodging&quot;, 13,
&quot;Excise&quot;, 14,
&quot;Provisioning&quot;,15,
null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Badges_Achieved</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Tax</fullName>
                </value>
                <value>
                    <fullName>Refunds</fullName>
                </value>
                <value>
                    <fullName>VAT</fullName>
                </value>
                <value>
                    <fullName>Duties &amp; Tarrifs</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>MultiTax</fullName>
                </value>
                <value>
                    <fullName>GST</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Address Validation</fullName>
                </value>
                <value>
                    <fullName>Communication</fullName>
                </value>
                <value>
                    <fullName>Use Tax</fullName>
                </value>
                <value>
                    <fullName>Document Management</fullName>
                </value>
                <value>
                    <fullName>Lodging</fullName>
                </value>
                <value>
                    <fullName>Excise</fullName>
                </value>
                <value>
                    <fullName>Sales Tax - AvaTax</fullName>
                </value>
                <value>
                    <fullName>Customs Duty &amp; Import Tax</fullName>
                </value>
                <value>
                    <fullName>Provisioning</fullName>
                </value>
                <value>
                    <fullName>Sales Tax - TrustFile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Badges</relationshipLabel>
        <relationshipName>Badges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Badge</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Badge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FullQa New/src/objects/Badge_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Badge_Resource_Path__c</fullName>
        <label>Badge Resource Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Badge Setting</label>
    <pluralLabel>Badge Settings</pluralLabel>
</CustomObject>

Prod/src/objects/Functional_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Functional Matrix</relationshipLabel>
        <relationshipName>Functional_Matrix</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Functional Matrix</label>
    <nameField>
        <displayFormat>FM-{000000}</displayFormat>
        <label>Functional Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Functional_Matrix_Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>Requirement Date</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Functional_Matrix_Requirements_Config__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Matrix Requirements Config</label>
        <referenceTo>Functional_Matrix_Requirements_Config__c</referenceTo>
        <relationshipLabel>Functional Matrix Requirements</relationshipLabel>
        <relationshipName>Functional_Matrix_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Functional_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Matrix</label>
        <referenceTo>Functional_Matrix__c</referenceTo>
        <relationshipLabel>Functional Matrix Requirements</relationshipLabel>
        <relationshipName>Functional_Matrix_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Functional_Requirement_Name__c</fullName>
        <formula>Functional_Matrix_Requirements_Config__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Functional Requirement Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <inlineHelpText>Requirement Note</inlineHelpText>
        <label>Note</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Functional Matrix Requirements</label>
    <nameField>
        <label>Functional Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functional Matrix Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Functional_Matrix_Requirements_Config__c.object
<CustomObject>
    <fields>
        <fullName>Certification_Type__c</fullName>
        <label>Certification Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Tax</fullName>
                </value>
                <value>
                    <fullName>Refunds</fullName>
                </value>
                <value>
                    <fullName>VAT</fullName>
                </value>
                <value>
                    <fullName>Duties &amp; Tarrifs</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>MultiTax</fullName>
                </value>
                <value>
                    <fullName>GST</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Communication</fullName>
                </value>
                <value>
                    <fullName>Use Tax</fullName>
                </value>
                <value>
                    <fullName>Address Validation</fullName>
                </value>
                <value>
                    <fullName>Extractor TrustFile</fullName>
                </value>
                <value>
                    <fullName>Document Management</fullName>
                </value>
                <value>
                    <fullName>Provisioning</fullName>
                </value>
                <value>
                    <fullName>Sales-Tax AvaTax</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Core_Type__c</fullName>
        <label>Core Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Core Sales Tax</fullName>
                </value>
                <value>
                    <fullName>Core Address Validation</fullName>
                </value>
                <value>
                    <fullName>Core Communication</fullName>
                </value>
                <value>
                    <fullName>Core Use Tax</fullName>
                </value>
                <value>
                    <fullName>Core Document Management</fullName>
                </value>
                <value>
                    <fullName>Core Lodging</fullName>
                </value>
                <value>
                    <fullName>Core Excise</fullName>
                </value>
                <value>
                    <fullName>Core Extractor TrustFile</fullName>
                </value>
                <value>
                    <fullName>Core Extractor AvaTax</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SubHeader__c</fullName>
        <label>SubHeader</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Functional Matrix Requirements Config</label>
    <nameField>
        <label>Functional Matrix Requirements Config Na</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functional Matrix Requirements Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Note__c.object
<CustomObject>
    <label>Note</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Version__c.object
<CustomObject>
    <description>Used as an associated related list for the connector object to track the version associated with a given connector</description>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>ITBSE-973</description>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Certified</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Certified</fullName>
                </value>
                <value>
                    <fullName>Revoked/Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Version</label>
    <nameField>
        <label>Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Avalara Fullqa/src/classes/VersionBadgeCtrl.cls
global with sharing class VersionBadgeCtrl {

    global VersionBadgeCtrl(ApexPages.StandardController ctrl) {}

    @RemoteAction
    global Static List<Badge_Setting__mdt> getSettings(){
        return [
            SELECT Id, Label, Status__c, Type__c,Badge_Resource_Path__c
            FROM Badge_Setting__mdt
        ];
    }

    @RemoteAction
    global static List<Badge__c> getBadges(String vId){
        return [
            SELECT Id, Name, Status__c, Type__c, Date_Achieved__c
            FROM Badge__c
            WHERE Version__c =:vId AND Type__c <> NULL AND Status__c <> NULL
            ORDER BY Sort_Order__c ASC,Type__c DESC, Status__c DESC
        ];
    }

    @RemoteAction
    global static List<Functional_Matrix_Requirement__c> getRequirements(String vId,String type){
        return [
            SELECT Id,Functional_Requirement_Name__c,Date__c,Functional_Matrix_Requirements_Config__r.Core_Type__c,Note__c,
                Functional_Matrix_Requirements_Config__r.Section__c,Functional_Matrix_Requirements_Config__r.SubHeader__c
            FROM Functional_Matrix_Requirement__c
            WHERE Functional_Matrix__r.Version__c =:vId
                AND Functional_Matrix_Requirements_Config__r.Certification_Type__c <> NULL
                AND Functional_Matrix_Requirements_Config__r.Certification_Type__c = :type
            ORDER BY Functional_Matrix_Requirements_Config__r.SubHeader__c ASC, Functional_Matrix_Requirements_Config__r.Sort_Order__c ASC
        ];
    }
}