Prod/src/objects/BookingsDelta__c.object
<CustomObject>
    <description>https://jira.avalara.com/browse/ITBSE-1212</description>
    <fields>
        <fullName>JIRATicketURL__c</fullName>
        <description>A link to the JIRA Ticket that captures the progress/status of resolving an identified Bookings Delta. ITBSX-306</description>
        <formula>IF(ISBLANK(Opportunity__r.JIRATicketURL__c),&quot;&quot;,HYPERLINK( Opportunity__r.JIRATicketURL__c , &quot;Immediate Resolution Tracking&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>JIRA Ticket URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OLD_Amount_SF__c</fullName>
        <label>OLD Amount (SF)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OLD_Booked_Value_EDW__c</fullName>
        <label>OLD Booked Value (EDW)</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BookingsDelta</relationshipLabel>
        <relationshipName>BookingsDelta</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BookingsDelta</label>
    <nameField>
        <displayFormat>BookingDelta#{00000}</displayFormat>
        <label>BookingsDelta Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BookingsDelta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FullQA/src/classes/CreateJiraTicket.cls
public with sharing class CreateJiraTicket {
    public PageReference createTicket(){
        String OppId=ApexPages.currentPage().getParameters().get('eid');
        Opportunity o=[Select Id,HasBookingsDelta__c,JIRATicketURL__c,Amount,BookedValue__c from Opportunity Where Id=:OppId]; 
        if(String.isBlank(o.JIRATicketURL__c)){
            List<Id> opportunityIds=new List<Id>();
            opportunityIds.add(o.Id);
            JobCreateBookingDeltaJiraTicket job = new JobCreateBookingDeltaJiraTicket(opportunityIds);
            ID batchprocessid = Database.executeBatch(job,22); 
            BookingsDelta__c bd=new BookingsDelta__c(Opportunity__c =o.Id,	OLD_Amount_SF__c=o.Amount,OLD_Booked_Value_EDW__c=o.BookedValue__c);
            insert bd;            
        }
        PageReference pr=new PageReference('/'+o.Id);
        pr.setRedirect(true);
        return pr;
    }
}