Prod/src/objects/BookingsDelta__c.object
<CustomObject>
    <description>https://jira.avalara.com/browse/ITBSE-1212</description>
    <fields>
        <fullName>Booking_Issue_Resolved_By__c</fullName>
        <label>Booking Issue Resolved By</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Akansha Gosain</fullName>
                </value>
                <value>
                    <fullName>Alison Cain</fullName>
                </value>
                <value>
                    <fullName>Brent Douma</fullName>
                </value>
                <value>
                    <fullName>Clay Wiggins</fullName>
                </value>
                <value>
                    <fullName>David Halladay</fullName>
                </value>
                <value>
                    <fullName>Mangal Pardeshi</fullName>
                </value>
                <value>
                    <fullName>Navees Ahmed</fullName>
                </value>
                <value>
                    <fullName>Priyanka Duggar</fullName>
                </value>
                <value>
                    <fullName>Kyle Leyh</fullName>
                </value>
                <value>
                    <fullName>Vaibhav Bandge</fullName>
                </value>
                <value>
                    <fullName>Andrew Gill</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Booking_Issue_Resolved_Date__c</fullName>
        <label>Booking Issue Resolved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>JIRATicketURL__c</fullName>
        <description>A link to the JIRA Ticket that captures the progress/status of resolving an identified Bookings Delta. ITBSX-306</description>
        <formula>IF(ISBLANK(Opportunity__r.JIRATicketURL__c),&quot;&quot;,HYPERLINK( Opportunity__r.JIRATicketURL__c , &quot;Immediate Resolution Tracking&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>JIRA Ticket URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BookingsDelta</relationshipLabel>
        <relationshipName>BookingsDelta</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BookingsDelta</label>
    <nameField>
        <displayFormat>BookingDelta#{00000}</displayFormat>
        <label>BookingsDelta Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BookingsDelta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Avalara Fullqa/src/classes/ProcessBuilderAPITest.cls
@isTest
private class ProcessBuilderAPITest {

    static testMethod void testCreateBookingDeltaJiraTicket() {
		Id customerAccountTypeId=[Select Id from RecordType where DeveloperName='Customer_Account_Type' limit 1].Id;
		Account a =TestUtil.createAccount(customerAccountTypeId,1,true)[0];
        //create Opportunity
        Id defaultOppRecTypeId=[Select Id from RecordType where DeveloperName='Default_OppRecType' limit 1].Id;
        Opportunity o = TestUtil.createOpportunity(a.id,defaultOppRecTypeId,1,true)[0];  
        User talendProductionUser=[Select id from User Where Id='00533000003lfbJ'];    
        Test.startTest();
        System.runAs(talendProductionUser){
            o.Amount=1000;
            o.BookedValue__c=2000;
            o.Booked_Date__c=Date.today();
            o.Locked__c=true;
            o.Type='Existing';
            update o;
            ProcessBuilderAPI.createBookingDeltaJiraTicket(new List<Id>{o.Id});
            System.debug('o.Amount======== '+o.Amount);
            System.debug('o.BookedValue__c======== '+o.BookedValue__c);
            System.debug('o.Booked_Delta__c======== '+o.Booked_Delta__c);             
        }
      
        Test.stopTest();
        o=[Select Id,Booked_Delta__c,Amount,BookedValue__c,JIRATicketURL__c,(Select Id,Notes__c From BookingsDelta__r) From Opportunity Where Id=:o.Id];
        System.assertNotEquals(null, o.JIRATicketURL__c);
        System.assertEquals(1, o.BookingsDelta__r.size());
        JobUpdateBookingDeltaRecords job = new JobUpdateBookingDeltaRecords();
        ID batchprocessid = Database.executeBatch(job,99);      
        o=[Select Id,Booked_Delta__c,Amount,BookedValue__c,JIRATicketURL__c,(Select Id,Notes__c,Booking_Issue_Resolved_By__c,Booking_Issue_Resolved_Date__c From BookingsDelta__r) From Opportunity Where Id=:o.Id];
    }
}