Prod/src/objects/Connector_KB__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>API__c</fullName>
        <label>API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Validation_Click_Path__c</fullName>
        <label>Address Validation Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>C_API__c</fullName>
        <label>C - API</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>REST V1</fullName>
                </value>
                <value>
                    <fullName>REST V2</fullName>
                </value>
                <value>
                    <fullName>SOAP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>C_Address_Validation_Click_Path__c</fullName>
        <label>C - Address Validation Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>C_Client_Exemption_Click_Path__c</fullName>
        <label>C - Client Exemption Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>C_Company_Code__c</fullName>
        <label>C - Company Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>C_Configuration_Click_Path__c</fullName>
        <label>C - Configuration Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>C_Implementation_Path__c</fullName>
        <label>C - Implementation Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>C_Line_Level_Addressing__c</fullName>
        <label>C - Line Level Addressing</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>C_Location_Code_Click_Path__c</fullName>
        <label>C - Location Code &amp; Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Client_Exemption_Click_Path__c</fullName>
        <label>Client Exemption Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Configuration_Click_Path__c</fullName>
        <label>Configuration Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Connector KB</relationshipLabel>
        <relationshipName>Connector_KB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Core_Notes__c</fullName>
        <label>Core Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Escalation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Escalation Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Connector KB (Escalation Contact)</relationshipLabel>
        <relationshipName>Connector_KB1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Path__c</fullName>
        <label>Implementation Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Line_Level_Addressing__c</fullName>
        <label>Line Level Addressing</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Location_Code_Click_Path__c</fullName>
        <label>Location Code &amp; Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_Mapping_Click_Path__c</fullName>
        <label>Product Mapping Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Support_Support_Path__c</fullName>
        <label>Support - Support Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Timing_for_Tax_Calculation__c</fullName>
        <label>Timing for Tax Calculation</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Timing_for_recording_Committing_Transa__c</fullName>
        <label>Timing for recording &amp; Committing Transa</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>User_Guide_Documentation__c</fullName>
        <label>User Guides URL</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Connector KB</relationshipLabel>
        <relationshipName>Connector_KB</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Connector KB</label>
    <pluralLabel>Connector KB</pluralLabel>
</CustomObject>

Prod/src/objects/Functional_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>API__c</fullName>
        <label>API</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>REST V1</fullName>
                </value>
                <value>
                    <fullName>REST V2</fullName>
                </value>
                <value>
                    <fullName>SOAP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Address_Validation_Click_Path__c</fullName>
        <inlineHelpText>Describe the path of clicks that the user must take to find the Address Validation button. Is it on the customer record, the invoice/order screen, or both? Is there no button and it automatically happens upon save event?</inlineHelpText>
        <label>Address Validation Click Path</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>C_API__c</fullName>
        <label>C - API</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>REST V1</fullName>
                </value>
                <value>
                    <fullName>REST V2</fullName>
                </value>
                <value>
                    <fullName>SOAP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>C_Address_Validation_Click_Path__c</fullName>
        <label>C - Address Validation Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>C_Client_Exemption_Click_Path__c</fullName>
        <label>C - Client Exemption Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>C_Company_Code__c</fullName>
        <label>C - Company Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>C_Configuration_Click_Path__c</fullName>
        <label>C - Configuration Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>C_Implementation_Path__c</fullName>
        <label>C - Implementation Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>C_Line_Level_Addressing__c</fullName>
        <label>C - Line Level Addressing</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Client_Exemption_Click_Path__c</fullName>
        <inlineHelpText>Describe the path of clicks that the user must take to find where they can apply Entity Use code or Exemption No data to a customer record.</inlineHelpText>
        <label>Client Exemption Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <inlineHelpText>Describe what value comes across to AvaTax as the Company Code, is it user defined or static?</inlineHelpText>
        <label>Company Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Configuration_Click_Path__c</fullName>
        <inlineHelpText>Describe the path of clicks that the user must take to find the AvaTax configuration. Also note if it&apos;s gated by permissions.</inlineHelpText>
        <label>Configuration Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Functional Matrix</relationshipLabel>
        <relationshipName>Functional_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Core_Notes__c</fullName>
        <label>Core Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Escalation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Escalation Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Functional Matrix (Escalation Contact)</relationshipLabel>
        <relationshipName>Functional_Matrix2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implemenation_Path__c</fullName>
        <label>Implementation Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Implementation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Functional Matrix (Implementation Contact)</relationshipLabel>
        <relationshipName>Functional_Matrix1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Path__c</fullName>
        <label>Implementation Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Line_Level_Addressing__c</fullName>
        <inlineHelpText>State whether or not the integration can send AvaTax separate addresses at the line level. If so, describe how it can be done.</inlineHelpText>
        <label>Line Level Addressing</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Location_Code_Click_Path__c</fullName>
        <inlineHelpText>Describe the path of clicks that the user must take to see the value that is sent to AvaTax as the Location Code on transactions.</inlineHelpText>
        <label>Location Code &amp; Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Product_Mapping_Click_Path__c</fullName>
        <inlineHelpText>Describe the path of clicks that the user must take to find the area where they can map products/services to Avalara Tax Codes.</inlineHelpText>
        <label>Product Mapping Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Support_Support_Path__c</fullName>
        <label>Support - Support Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Timing_For_Tax_Calculation__c</fullName>
        <inlineHelpText>Describe the events and triggers which call out to AvaTax. Is it manually by a calculate button? Automatically on save event? State all stages of transaction life cycle where a call is made, estimate, order, invoice etc.</inlineHelpText>
        <label>Timing For Tax Calculation</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Timing_for_recording_Committing_Trans__c</fullName>
        <label>Timing for recording &amp; Committing Trans.</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Timing_for_recording_Committing_Transa__c</fullName>
        <label>Timing for recording &amp; Committing Transa</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>User_Implementation_Guide__c</fullName>
        <inlineHelpText>The User Implementation Guide should contain screenshots and information allowing the end user to configure for AvaTax including where the company code is entered, where the credentials are entered and where tax codes can be mapped within the application.</inlineHelpText>
        <label>User Implementation Guide</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Functional Matrix</relationshipLabel>
        <relationshipName>Functional_Matrix</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Functional Matrix</label>
    <nameField>
        <displayFormat>FM-{000000}</displayFormat>
        <label>Functional Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Avalara Fullqa/src/classes/FunctionalMatrixHandler.cls
public class FunctionalMatrixHandler{

    public static void enforceSingleFM(List<Functional_Matrix__c> triggerNew){
        Map<String,Set<Id>> matrixMap = matrixMap(triggerNew);
        Map<String,String> recordTypeMap = recordTypeMap();
        for(Functional_Matrix__c matrix : triggerNew){
            // check if there is a record with the same record type for this version
            if(matrixMap.containsKey(matrix.Version__c) && matrixMap.get(matrix.Version__c).contains(matrix.RecordTypeId)){
                matrix.addError(recordTypeMap.get(matrix.RecordTypeId) + ' already exists in this version, please select another type');
            }
        }
    }

    public static void syncToConnectorKB(List<Functional_Matrix__c> fms){
        syncToConnectorKB(new Map<Id, Functional_Matrix__c>(fms), NULL);
    }

    public static void syncToConnectorKB(Map<Id, Functional_Matrix__c> fmMap, Map<Id, Functional_Matrix__c> fmOldMap){
            // Functaional Matrix => Connector KB
        Map<String, String> fieldsToSync = new Map<String, String>{
            'Configuration_Click_Path__c' => 'Configuration_Click_Path__c',
            'Company_Code__c' => 'Company_Code__c',
            'Product_Mapping_Click_Path__c' => 'Product_Mapping_Click_Path__c',
            'Client_Exemption_Click_Path__c' => 'Client_Exemption_Click_Path__c',
            'Location_Code_Click_Path__c' => 'Location_Code_Click_Path__c',
            'Line_Level_Addressing__c' => 'Line_Level_Addressing__c',
            'Timing_For_Tax_Calculation__c' => 'Timing_For_Tax_Calculation__c',
            'Timing_for_recording_Committing_Trans__c' => 'Timing_for_recording_Committing_Transa__c',
            'Notes__c' => 'Notes__c',
            'User_Implementation_Guide__c' => 'User_Guide_Documentation__c',
            'Implementation_Contact__c' => 'Contact__c',
            'Support_Support_Path__c' => 'Support_Support_Path__c',
            'Escalation_Contact__c' => 'Escalation_Contact__c',
            'Core_Notes__c' => 'Core_Notes__c',
            'Address_Validation_Click_Path__c' => 'Address_Validation_Click_Path__c',
            'API__c' => 'API__c',
            'Implemenation_Path__c' => 'Implementation_Path__c',

            'C_API__c' => 'C_API__c',
            'C_Address_Validation_Click_Path__c' => 'C_Address_Validation_Click_Path__c',
            'C_Client_Exemption_Click_Path__c' => 'C_Client_Exemption_Click_Path__c',
            'C_Company_Code__c' => 'C_Company_Code__c',
            'C_Configuration_Click_Path__c' => 'C_Configuration_Click_Path__c',
            'C_Implementation_Path__c' => 'C_Implementation_Path__c',
            'C_Line_Level_Addressing__c' => 'C_Line_Level_Addressing__c',
            'C_Location_Code_Click_Path__c' => 'C_Location_Code_Click_Path__c',
            'C_Notes__c' => 'C_Notes__c',
            'C_Product_Mapping_Click_Path__c' => 'C_Product_Mapping_Click_Path__c',
            'C_Support_Path__c' => 'C_Support_Path__c',
            'C_Timing_For_Tax_Calculation__c' => 'C_Timing_For_Tax_Calculation__c',
            'C_User_Implementation_Guide__c' => 'C_User_Implementation_Guide__c',
            'C_Location_Code_Click_Path__c' => 'C_Location_Code_Click_Path__c',
            'C_Timing_For_Recording_Committing_Tran__c' => 'C_Timing_For_Recording_Committing_Tran__c'
        };

        List<Connector_KB__kav> ckbs = [
            SELECT Id, Sales_Tax_Matrix__c, KnowledgeArticleId, Comm_Functional_Matrix__c,
                Version__r.Connector__r.Connector_Description__c,Version__r.Connector__r.Connector_EcoSystem_Test__c
            FROM Connector_KB__kav
            WHERE Sales_Tax_Matrix__c IN:fmMap.keySet() OR Comm_Functional_Matrix__c IN:fmMap.keySet()
        ];

        for(Connector_KB__kav ckb : ckbs){
            if( ckb.Version__r != NULL &&  ckb.Version__r.Connector__r != NULL){
                ckb.Connector_Description__c = ckb.Version__r.Connector__r.Connector_Description__c;
                ckb.Selling_Information__c = ckb.Version__r.Connector__r.Connector_EcoSystem_Test__c;
            }
            if(ckb.Sales_Tax_Matrix__c!= NULL && fmMap.get(ckb.Sales_Tax_Matrix__c) != NULL){
                Functional_Matrix__c fm = fmMap.get(ckb.Sales_Tax_Matrix__c);

                for(String f : fieldsToSync.keySet()){
                    if(fmOldMap == NULL || fmOldMap.get(ckb.Sales_Tax_Matrix__c).get(f) != fm.get(f)){
                        ckb.put(fieldsToSync.get(f), fm.get(f));
                    }
                }
            }

            if(ckb.Comm_Functional_Matrix__c != NULL && fmMap.get(ckb.Comm_Functional_Matrix__c) != NULL){
                Functional_Matrix__c fm = fmMap.get(ckb.Comm_Functional_Matrix__c);
                for(String f : fieldsToSync.keySet()){
                    if(f.startsWith('C_') && (fmOldMap == NULL || fmOldMap.get(ckb.Comm_Functional_Matrix__c).get(f) != fm.get(f))){
                        ckb.put(fieldsToSync.get(f), fm.get(f));
                    }
                }
            }
        }

        FunctionalMatrixSyncUtil.publishArticle(ckbs);
    }

    // creates a map of version vs all the recordtype id that version has
    private static Map<String,Set<Id>> matrixMap(List<Functional_Matrix__c> triggerNew){
        Set<String> versionIds = new Set<String>();
        Set<String> rTypeIds = new Set<String>();

        for(Functional_Matrix__c matrix : triggerNew){
            versionIds.add(matrix.Version__c);
            rTypeIds.add(matrix.RecordTypeId);
        }

        Map<String,Set<Id>> mMap = new Map<String,Set<Id>>();
        for(Functional_Matrix__c matrix : [
            SELECT Id, RecordTypeId, Version__c
            FROM Functional_Matrix__c
            WHERE Version__c IN:versionIds AND RecordTypeId IN:rTypeIds
        ]){
            if(!mMap.containsKey(matrix.Version__c)){
                mMap.put(matrix.Version__c,new Set<Id>());
            }
            mMap.get(matrix.Version__c).add(matrix.RecordTypeId);
        }
        return mMap;
    }

    //helper method
    private static Map<String,String> recordTypeMap(){
        Map<String,String> rTypeMap = new Map<String,String>();
        for(RecordType rt : [
            SELECT Id, Name
            FROM RecordType
            WHERE sObjectType = 'Functional_Matrix__c'
        ]){
            rTypeMap.put(rt.Id,rt.Name);
        }
        return rTypeMap;
    }
}