Prod/src/objects/Connector__c.object
<CustomObject>
    <description>Used to track all Avalara connectors and associated data</description>
    <fields>
        <fullName>Connector_Description__c</fullName>
        <inlineHelpText>Enter a summary of the partner connector relationship, capabilities and any other pertinent information specific to this connector.</inlineHelpText>
        <label>Connector Description</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Connector_EcoSystem_Test__c</fullName>
        <label>Connector EcoSystem Summary</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Partner_Fee__c</fullName>
        <description>Used by the Partner Launch Team for Partner comments
Owner: Sara Simrell</description>
        <label>Partner Fee</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <label>Connector</label>
    <nameField>
        <label>Connector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Connector_KB__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>API__c</fullName>
        <label>API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connector KB</relationshipLabel>
        <relationshipName>Connector_KB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Exemption_Click_Path__c</fullName>
        <label>Client Exemption Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Configuration_Click_Path__c</fullName>
        <label>Configuration Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Connector_Description__c</fullName>
        <label>Connector Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Connector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Connector</label>
        <referenceTo>Connector__c</referenceTo>
        <relationshipLabel>Connector KB</relationshipLabel>
        <relationshipName>Connector_KB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Connector KB</relationshipLabel>
        <relationshipName>Connector_KB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Core_Notes__c</fullName>
        <label>Core Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Download_User_Guide_Template__c</fullName>
        <label>Download User Guide Template</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Escalation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Escalation Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Connector KB (Escalation Contact)</relationshipLabel>
        <relationshipName>Connector_KB1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Path__c</fullName>
        <label>Implementation Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Line_Level_Addressing__c</fullName>
        <label>Line Level Addressing</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Partner_Fee__c</fullName>
        <label>Partner Fee</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_Mapping_Click_Path__c</fullName>
        <label>Product Mapping Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Selling_Information__c</fullName>
        <label>Selling Information</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Submit_Demo_Video_url__c</fullName>
        <label>Submit Demo Video (url)</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Submit_User_Guide_url__c</fullName>
        <label>Submit User Guide (url)</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Support_Notes__c</fullName>
        <label>Support Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Support_Support_Path__c</fullName>
        <label>Support - Support Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Timing_for_Tax_Calculation__c</fullName>
        <label>Timing for Tax Calculation</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Timing_for_recording_Committing_Transa__c</fullName>
        <label>Timing for recording &amp; Committing Transa</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Unique_Identifier__c</fullName>
        <label>Unique Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Guide_Documentation__c</fullName>
        <label>User Guides URL</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Connector KB</relationshipLabel>
        <relationshipName>Connector_KB</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Connector KB</label>
    <pluralLabel>Connector KB</pluralLabel>
</CustomObject>

FullQa New/src/objects/Solution.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the Account of the partner who owns the integration</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Validation_Batch_Utlity__c</fullName>
        <description>y/n  Explicit or part of get tax call? Is there a batch utility?</description>
        <inlineHelpText>y/n  Explicit or part of get tax call? Is there a batch utility?</inlineHelpText>
        <label>Address Validation / Batch Utlity</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Committing_Transactions__c</fullName>
        <description>y/n  At what point are transactions committed to the Admin Console?</description>
        <inlineHelpText>y/n  At what point are transactions committed to the Admin Console?</inlineHelpText>
        <label>Committing Transactions</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <description>User Defined y/n  If no, where to locate the code.</description>
        <inlineHelpText>User Defined y/n  If no, where to locate the code.</inlineHelpText>
        <label>Company Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Configuration_Screen__c</fullName>
        <inlineHelpText>Where is the configuration screen located?</inlineHelpText>
        <label>Configuration Screen</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Support_Info__c</fullName>
        <label>Product Support</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Download_User_Guide_Template__c</fullName>
        <label>Download User Guide  Template</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Escalation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Contact in Salesforce to be used in case of escalation</inlineHelpText>
        <label>Escalation Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Solutions (Escalation Contact)</relationshipLabel>
        <relationshipName>Solutions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exemptions__c</fullName>
        <description>y/n Provide details for how to do exemptions</description>
        <inlineHelpText>y/n Provide details for how to do exemptions</inlineHelpText>
        <label>Exemptions</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Implementation_Instructions__c</fullName>
        <description>Instructions to customers for implementing this integration</description>
        <inlineHelpText>Instructions to customers for implementing this integration</inlineHelpText>
        <label>Implementation Instructions</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Installation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Who will help customer install AvaTax module</description>
        <inlineHelpText>Who will help customer install AvaTax module</inlineHelpText>
        <label>Installation Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Known_Issues__c</fullName>
        <inlineHelpText>Short description of known issues.</inlineHelpText>
        <label>Known Issues</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mapping__c</fullName>
        <description>y/n provide details on where and how to map here</description>
        <inlineHelpText>y/n Provide details on where and how to map here</inlineHelpText>
        <label>Mapping</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SDK_Platform__c</fullName>
        <inlineHelpText>Specify which SDK platform partner is using.</inlineHelpText>
        <label>SDK Platform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>REST API</fullName>
                </value>
                <value>
                    <fullName>SOAP API – PHP</fullName>
                </value>
                <value>
                    <fullName>SOAP API – Java</fullName>
                </value>
                <value>
                    <fullName>SOAP API – C#/.NET</fullName>
                </value>
                <value>
                    <fullName>SOAP API – Other</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submit_Demo_Video_url__c</fullName>
        <label>Submit Demo Video (url)</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Submit_User_Guide_url__c</fullName>
        <label>Submit User Guide (url)</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Support_Escalation_Info__c</fullName>
        <label>Escalation Info</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Timing_Process_for_Tax_Calc__c</fullName>
        <description>At what stages in the order/invoice lifecycle is tax calculated?</description>
        <inlineHelpText>At what stages in the order/invoice lifecycle is tax calculated?</inlineHelpText>
        <label>Timing / Process for Tax Calc</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>User_Guide_Documentation__c</fullName>
        <description>Provide the link or details for getting to the guide here.</description>
        <inlineHelpText>Provide the link or details for getting to the guide here.</inlineHelpText>
        <label>User Guides URL</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Warehouse_Ship_to_by_Line__c</fullName>
        <description>Lines with multiple ship-from addresses? y/n  Lines with multiple ship-to addresses? y/n</description>
        <inlineHelpText>Lines with multiple ship-from addresses? y/n  Lines with multiple ship-to addresses? y/n</inlineHelpText>
        <label>Warehouse / Ship to by Line</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

Prod/src/objects/Version__c.object
<CustomObject>
    <description>Used as an associated related list for the connector object to track the version associated with a given connector</description>
    <fields>
        <fullName>Connector__c</fullName>
        <label>Connector</label>
        <referenceTo>Connector__c</referenceTo>
        <relationshipLabel>Versions</relationshipLabel>
        <relationshipName>Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Version_KB__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Version KB</label>
        <referenceTo>Solution</referenceTo>
        <relationshipLabel>Versions</relationshipLabel>
        <relationshipName>Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Version</label>
    <nameField>
        <label>Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Avalara Fullqa/src/classes/VersionArticleManager.cls
public class VersionArticleManager{

    public static void process(List<Version__c> triggerNew){

        List<Connector_KB__kav> articles = new List<Connector_KB__kav>();

        List<Version__c> versions = getVersions(triggerNew);

        for(Version__c v : versions){
            Connector_KB__kav ka = toArticle(v);
            articles.add(ka);
            //articles.add(toArticle(v));
        }


        if(!articles.isEmpty()){
            insert articles;
            FunctionalMatrixSyncUtil.publishNewArticle(new Map<Id, Connector_KB__kav>(articles).keySet());
        }
    }

    public static Connector_KB__kav toArticle(Version__c v){
        Connector_KB__kav ckb = new Connector_KB__kav();
        ckb.Connector__c = v.Connector__c;
        // ckb.Partner_Fee__c = v.Connector__r.Partner_Fee__c;
        ckb.Connector_Description__c = v.Connector__r.Connector_Description__c;
        ckb.Selling_Information__c = v.Connector__r.Connector_EcoSystem_Test__c;
        ckb.Version__c = v.Id;
        if(v.Version_KB__c <> NULL){
            ckb.Title = v.Version_KB__r.SolutionName;
            ckb.UrlName = (v.Connector__r.Name + '-' + v.Name + '-' + v.Version_KB__r.SolutionName).replaceAll('[^a-zA-Z0-9]',' ').normalizeSpace().toLowerCase().replaceAll(' ','-');
            ckb.Unique_Identifier__c = v.Version_KB__c + '||' + v.Id;
            ckb.Account__c = v.Version_KB__r.Account__c;
            ckb.User_Guide_Documentation__c = v.Version_KB__r.User_Guide_Documentation__c;
            ckb.Submit_Demo_Video_url__c = v.Version_KB__r.Submit_Demo_Video_url__c;
            ckb.Submit_User_Guide_url__c = v.Version_KB__r.Submit_User_Guide_url__c;
            ckb.Escalation_Contact__c = v.Version_KB__r.Escalation_Contact__c;
            ckb.Download_User_Guide_Template__c = v.Version_KB__r.Download_User_Guide_Template__c;

            ckb.Configuration_Click_Path__c = v.Version_KB__r.Configuration_Screen__c;
            ckb.Company_Code__c = v.Version_KB__r.Company_Code__c;
            ckb.Product_Mapping_Click_Path__c = v.Version_KB__r.Mapping__c;
            ckb.Client_Exemption_Click_Path__c = v.Version_KB__r.Exemptions__c;
            ckb.Timing_for_Tax_Calculation__c = v.Version_KB__r.Timing_Process_for_Tax_Calc__c;
            ckb.Timing_for_recording_Committing_Transa__c = v.Version_KB__r.Committing_Transactions__c;
            ckb.Line_Level_Addressing__c = v.Version_KB__r.Warehouse_Ship_to_by_Line__c;
            ckb.Notes__c = v.Version_KB__r.Known_Issues__c;
            ckb.API__c = v.Version_KB__r.SDK_Platform__c;
            ckb.Implementation_Path__c = v.Version_KB__r.Implementation_Instructions__c;
            ckb.Support_Support_Path__c  = v.Version_KB__r.Customer_Support_Info__c;
            ckb.Support_Notes__c = v.Version_KB__r.Support_Escalation_Info__c;
            ckb.Core_Notes__c = v.Version_KB__r.Address_Validation_Batch_Utlity__c;
            ckb.Contact__c = v.Version_KB__r.Installation_Contact__c;
        }
        else{
            ckb.Title = v.Name ;
            ckb.UrlName = (v.Connector__r.Name + '-' + v.Name).replaceAll('[^a-zA-Z0-9]',' ').normalizeSpace().toLowerCase().replaceAll(' ','-');
            ckb.Unique_Identifier__c = v.Id;
        }

        return ckb;
    }

    private static List<Version__c> getVersions(List<Version__c> triggerNew){
        return [
            SELECT Name,Version_KB__c,Version_KB__r.SolutionName,Version_KB__r.Account__c,Version_KB__r.User_Guide_Documentation__c,
               Version_KB__r.Submit_Demo_Video_url__c,Version_KB__r.Submit_User_Guide_url__c,Version_KB__r.Escalation_Contact__c,
               Version_KB__r.Download_User_Guide_Template__c,Version_KB__r.Configuration_Screen__c,Version_KB__r.Company_Code__c,
               Version_KB__r.Mapping__c,Version_KB__r.Exemptions__c,Version_KB__r.Timing_Process_for_Tax_Calc__c,Version_KB__r.Committing_Transactions__c,
               Version_KB__r.Warehouse_Ship_to_by_Line__c,Version_KB__r.Known_Issues__c,Version_KB__r.SDK_Platform__c,Version_KB__r.Implementation_Instructions__c,
               Version_KB__r.Customer_Support_Info__c,Version_KB__r.Support_Escalation_Info__c,Version_KB__r.Address_Validation_Batch_Utlity__c,Version_KB__r.Installation_Contact__c,
               Connector__r.Connector_Description__c,Connector__r.Name, Connector__r.Connector_EcoSystem_Test__c
            FROM Version__c
            WHERE Id IN :triggerNew];
    }
}