Prod/src/objects/Connector__c.object
<CustomObject>
    <description>Used to track all Avalara connectors and associated data</description>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Track the original developer of the code associated with this connector
Integrated: Yes 
Change: Level 1 
Custodian: Business Development / Greg Chapman</description>
        <inlineHelpText>Associate the account of the original developer of the code associated with this connector</inlineHelpText>
        <label>Author</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connectors (Author)</relationshipLabel>
        <relationshipName>Connectors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Managed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Track 30 day delta between old calc estimation and new calc estimation 
Integrated: No 
Change: Level 0 
Custodian: Business Development / Greg Chapman</description>
        <inlineHelpText>Associate the account currently managing / responsible for the code associated with this connector</inlineHelpText>
        <label>Managed By</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connectors (Managed By)</relationshipLabel>
        <relationshipName>Managed_Connectors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Connector</label>
    <nameField>
        <label>Connector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Version__c.object
<CustomObject>
    <description>Used as an associated related list for the connector object to track the version associated with a given connector</description>
    <fields>
        <fullName>Connector__c</fullName>
        <label>Connector</label>
        <referenceTo>Connector__c</referenceTo>
        <relationshipLabel>Versions</relationshipLabel>
        <relationshipName>Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Version</label>
    <nameField>
        <label>Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/classes/VersionBadgeCtrlTest.cls
@IsTest
private class VersionBadgeCtrlTest{

    static testMethod void testAll(){
        Account acc = new Account(
            Name = 'Test Account'
        );
        insert acc;

        Connector__c c = new Connector__c(
            Name = 'Test Connector',
            Author__c = acc.Id,
            Managed_By__c = acc.Id
        );
        insert c;

        Version__c ver = new Version__c(
            Name = 'Text version',
            Connector__c = c.Id
        );
        insert ver;
        VersionBadgeCtrl.getSettings();
        VersionBadgeCtrl.getBadges(ver.Id);
        VersionBadgeCtrl.getRequirements(ver.Id,'VAT');
    }
}