Prod/src/objects/Connector__c.object
<CustomObject>
    <description>Used to track all Avalara connectors and associated data</description>
    <fields>
        <fullName>Connector_EcoSystem_Test__c</fullName>
        <label>Connector EcoSystem Summary</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Connector</label>
    <nameField>
        <label>Connector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Connector_KB__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Connector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Connector</label>
        <referenceTo>Connector__c</referenceTo>
        <relationshipLabel>Connector KB</relationshipLabel>
        <relationshipName>Connector_KB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selling_Information__c</fullName>
        <label>Selling Information</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Unique_Identifier__c</fullName>
        <label>Unique Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Connector KB</relationshipLabel>
        <relationshipName>Connector_KB</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Connector KB</label>
    <pluralLabel>Connector KB</pluralLabel>
</CustomObject>

Prod/src/objects/Version__c.object
<CustomObject>
    <description>Used as an associated related list for the connector object to track the version associated with a given connector</description>
    <fields>
        <fullName>Connector__c</fullName>
        <label>Connector</label>
        <referenceTo>Connector__c</referenceTo>
        <relationshipLabel>Versions</relationshipLabel>
        <relationshipName>Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Version</label>
    <nameField>
        <label>Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev/src/classes/ConnectorTriggerHandlerTest.cls
@isTest
private class ConnectorTriggerHandlerTest {
    private static Solution sol;
	private static Connector__c con;
	private static Connector_KB__kav conKB;
	private static Version__c ver;
	private static Account a;
    static testMethod void connectorUpdate() {
        	Test.startTest();
	        	 //Create User
		     //Create an account
	    	     Id customerAccountTypeId=[Select Id from RecordType where DeveloperName='Customer_Account_Type' limit 1].Id;
	         a =TestUtil.createAccount(customerAccountTypeId,1,false)[0];
		     //create solution
		     sol = TestUtil.createSolution(1,true)[0];
		     //Create Connector
	         con = TestUtil.createConnector(a.id,a.id,1,false)[0];
	         con.Connector_EcoSystem_Test__c='Test';   
	         insert con;
	         //Create Version
	         ver = TestUtil.createVersion(con.id,sol.id,1,true)[0];
	         //Create ConnectorKB
	         conKB = TestUtil.createConnectorKB(ver.id,sol.id,1,false)[0];
	         conKB.Selling_Information__c = 'Test Knowledge';
	         insert conKB;
	         //Update connectro field 
	         con.Connector_EcoSystem_Test__c='Test Connector';        
	         update con; 
        	Test.stopTest();
	        	Connector_KB__kav knowledge = [SELECT Id,Unique_Identifier__c,Selling_Information__c,Connector__c FROM Connector_KB__kav WHERE Connector__c=:con.id AND  Language = 'en_US' AND PublishStatus ='online' limit 1];
	        	Version__c v=[Select id,Connector__r.Connector_EcoSystem_Test__c from Version__c where id=:ver.id];
	        	System.assertEquals(knowledge.Selling_Information__c,v.Connector__r.Connector_EcoSystem_Test__c );
    }
}