Prod/src/objects/Connector__c.object
<CustomObject>
    <description>Used to track all Avalara connectors and associated data</description>
    <label>Connector</label>
    <nameField>
        <label>Connector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Avalara Fullqa/src/Conversica/objects/Contact.object
<CustomObject>
</CustomObject>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>ChangedChannelPartnerName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this field will be used to capture email if it was changed before 6 months https://jira.avalara.com/browse/IBST-7371</description>
        <inlineHelpText>Partner on latest form submission, unable to overwrite, &lt;6 mo. since prior partner added.</inlineHelpText>
        <label>Suggested Channel Partner Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Account)</relationshipLabel>
        <relationshipName>Contacts2</relationshipName>
        <type>Lookup</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Channel_Partner_Name_Update_6__c</fullName>
        <defaultValue>false</defaultValue>
        <description>https://jira.avalara.com/browse/IBST-7371</description>
        <label>Channel Partner Name Update &lt;6</label>
        <type>Checkbox</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Partner_Connector_Assigned_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is being populated from contact trigger</description>
        <label>Partner Connector Assigned Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PartnerConnectorContacts</relationshipName>
        <type>Lookup</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Partner_Contact_Not_Found_Email_Sent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Partner Contact Not Found Email Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Partner_Rep_Email__c</fullName>
        <label>Partner Rep Email</label>
        <type>Email</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Prior_Channel_Partner_Name_Change_Date__c</fullName>
        <description>https://jira.avalara.com/browse/IBST-7371</description>
        <label>Prior Channel Partner Name Change Date</label>
        <type>Date</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>PriorChannelPartnerName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>https://jira.avalara.com/browse/IBST-7371</description>
        <label>Prior Channel Partner Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Account)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>

FullQa New/src/objects/KeyPairValue__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To store Opportunity Type and Meeting type for EventTriggerHandler</description>
    <fields>
        <fullName>Values__c</fullName>
        <label>Values</label>
        <type>TextArea</type>
    </fields>
    <label>KeyPairValue</label>
</CustomObject>

Avalara Fullqa/src/Infer Behavior Scoring/objects/Lead.object
<CustomObject>
</CustomObject>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>ChangedChannelPartnerName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>(this field will be used to capture email if it was changed before 6 months)https://jira.avalara.com/browse/IBST-7371</description>
        <inlineHelpText>Partner on latest form submission, unable to overwrite, &lt;6 mo. since prior partner added.</inlineHelpText>
        <label>Suggested Channel Partner Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Account)</relationshipLabel>
        <relationshipName>Leads5</relationshipName>
        <type>Lookup</type>
    </fields>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>Channel_Partner_Name_Update_6__c</fullName>
        <defaultValue>false</defaultValue>
        <description>https://jira.avalara.com/browse/IBST-7371</description>
        <label>Channel Partner Name Update &lt;6</label>
        <type>Checkbox</type>
    </fields>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>Connector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Inbound lead connector
Integrated: No
Change: Level 0
Custodian: AvaTax VP Marketing Demand Gen</description>
        <inlineHelpText>The additional primary connector associated with this lead</inlineHelpText>
        <label>Connector</label>
        <referenceTo>Connector__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>Partner_Connector_Assigned_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is populated with LeadTrigger. System check if connector__c and PartnerName__c are populated and Reselling_Partner__c contains a record with partner and connector then Assigned_Sales_Rep__c field is used to populate this field</description>
        <label>Partner Connector Assigned Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PartnerConnectorLeads</relationshipName>
        <type>Lookup</type>
    </fields>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>Partner_Contact_Not_Found_Email_Sent__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is being used in LeadTrigger. If Partner_Rep_Email__c field is populated and no contact is found then code will put current time stamp in this field and WF will send email to  pmm@avalara.com</description>
        <label>Partner Contact Not Found Email Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>Partner_Rep_Email__c</fullName>
        <label>Partner Rep Email</label>
        <type>Email</type>
    </fields>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>PartnerName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Track the Partner responsible for bringing in the Lead
Integrated: Yes (Partner Portal)
Change: Level 1 
Custodian: VP Partner Management / Balz Wyss</description>
        <inlineHelpText>The Partner responsible for bringing in the Lead</inlineHelpText>
        <label>Channel Partner Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Track the partner portal user who submitted this lead - changed Label from Portal contact to Channel Partner Sales Rep 10.7.15
Integrated: Yes
Change: Level 1 
Custodian: Partner Portal / VP Partner Operations</description>
        <inlineHelpText>Partner portal user contact. Maps to Channel Sales Rep on the opportunity.</inlineHelpText>
        <label>Channel Partner Sales Rep</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>Prior_Channel_Partner_Name_Change_Date__c</fullName>
        <description>https://jira.avalara.com/browse/IBST-7371</description>
        <label>Prior Channel Partner Name Change Date</label>
        <type>Date</type>
    </fields>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>PriorChannelPartnerName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>https://jira.avalara.com/browse/IBST-7371</description>
        <label>Prior Channel Partner Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Account)</relationshipLabel>
        <relationshipName>Leads4</relationshipName>
        <type>Lookup</type>
    </fields>

Prod/src/objects/Reselling_Partner__c.object
<CustomObject>
    <description>Used as a junction object to track connector &lt;--&gt; partner relationships</description>
    <fields>
        <fullName>Assigned_Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to direct all opportunities of a specific connector to the rep that manages that partners opportunities if they come in from the Channel with that specific connector.
Matt Kantellis</description>
        <label>Assigned Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reselling_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Connector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Connector</label>
        <referenceTo>Connector__c</referenceTo>
        <relationshipLabel>Reselling Partners</relationshipLabel>
        <relationshipName>Reselling_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reselling_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reselling Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connectors Resold</relationshipLabel>
        <relationshipName>Reselling_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reselling Partner</label>
    <nameField>
        <displayFormat>RSP{0000}</displayFormat>
        <label>RID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reselling Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Avalara Fullqa/src/classes/LeadTriggerHandler.cls
public class LeadTriggerHandler extends TriggerHandler {
	//https://jira.avalara.com/browse/IBST-8008
    public static boolean isLeadConverted= false;
    //Trigger Handler Methods
    protected override void beforeInsert(){
    		beforeInsertUpdate();
    }

    protected override void beforeUpdate(){
    		beforeInsertUpdate();
    }

    /*
    protected override void beforeDelete(){}

    protected override void afterInsert(){}

    protected override void afterDelete(){}

    protected override void afterUndelete(){}
    */
   //Helper Methods
  //https://jira.avalara.com/browse/SFCOM-8722?filter=-1
    public void beforeInsertUpdate(){
    		//Get partner rep email of all leads where partner is not populated 
    		Set<String> setPartnerContactEmails=new Set<String>();
    		String EloquaAvalaraCaseSafeID='';
        EloquaAvalaraCaseSafeID =KeyPairValue__c.getInstance('EloquaAvalaraCaseSafeID').Values__c;  
        for(Lead l:(List<Lead>)Trigger.new){
        	l.Partner_Connector_Assigned_Rep__c=null;
            if(l.PartnerName__c!=null){
               l.Prior_Channel_Partner_Name_Change_Date__c = System.today();  
            }
            if(
            		l.PartnerName__c==null && 
            		l.Portal_Contact__c==null && 
            		String.isNotBlank(l.Partner_Rep_Email__c) && 
            		(Trigger.isInsert || (Trigger.isUpdate && l.Partner_Rep_Email__c.equalsIgnoreCase(((Lead)Trigger.oldMap.get(l.Id)).Partner_Rep_Email__c)==false))
            		){
            		setPartnerContactEmails.add(l.Partner_Rep_Email__c.trim());
            }
        }
        //get most recent contact where email match with partner rep email
        //if(setPartnerContactEmails.size()>0){
        Set<Id> partnerIDs=new Set<Id>();
        Set<Id> connectorIDs=new Set<Id>();
        		Map<String,Contact> mapPartnerContacts=new Map<String,Contact>();
        		for(Contact c:[Select Id,AccountId,Email From Contact 
        						Where Email!=null AND AccountId!=null AND Email=:setPartnerContactEmails 
        						Order By CreatedDate DESC]){
				String key=c.Email.toLowerCase();
				if(!mapPartnerContacts.containsKey(key)){
        				mapPartnerContacts.put(key,c);
				}
        		}
	        for(Lead l:(List<Lead>)Trigger.new){
	            if(
	            		String.isNotBlank(l.Partner_Rep_Email__c) &&
	            		mapPartnerContacts.containsKey(l.Partner_Rep_Email__c.toLowerCase())
	            		){
		            		Contact c=mapPartnerContacts.get(l.Partner_Rep_Email__c.toLowerCase());
		            		l.PartnerName__c=c.AccountId;
		            		l.Portal_Contact__c=c.Id;
		            		l.Prior_Channel_Partner_Name_Change_Date__c = System.today();
	            		}
	            		else if(
			            		String.isNotBlank(l.Partner_Rep_Email__c) && 
			            		(Trigger.isInsert || (Trigger.isUpdate && l.Partner_Rep_Email__c.equalsIgnoreCase(((Lead)Trigger.oldMap.get(l.Id)).Partner_Rep_Email__c)==false))
			            		){
				            		if(l.Partner_Contact_Not_Found_Email_Sent__c==null){
				            			l.Partner_Contact_Not_Found_Email_Sent__c=0;
				            		}
				            		l.Partner_Contact_Not_Found_Email_Sent__c+=1;			            			
			            		}
            		if(l.PartnerName__c!=null && l.Connector__c!=null){
            			partnerIDs.add(l.PartnerName__c);
            			connectorIDs.add(l.Connector__c);
            		}
            	    //https://jira.avalara.com/browse/IBST-7371
                //Devloper : Payal Bhawnani 02/20/2018
            		if(l.Prior_Channel_Partner_Name_Change_Date__c != null && Trigger.isUpdate  ){
                   Integer monthsBetween = l.Prior_Channel_Partner_Name_Change_Date__c.monthsBetween(system.today());
           	       if(l.PartnerName__c!=null &&  l.PartnerName__c != ((Lead)Trigger.oldMap.get(l.Id)).PartnerName__c && monthsBetween>=6 && system.UserInfo.getUserId() ==EloquaAvalaraCaseSafeID){
           	         l.Prior_Channel_Partner_Name_Change_Date__c = System.today();
           	         l.PriorChannelPartnerName__c =  ((Lead)Trigger.oldMap.get(l.Id)).PartnerName__c ;
                 	}
           	    else if(l.PartnerName__c!=null && monthsBetween <6 && l.PartnerName__c != ((Lead)Trigger.oldMap.get(l.Id)).PartnerName__c&& system.UserInfo.getUserId() ==EloquaAvalaraCaseSafeID){
           	         l.ChangedChannelPartnerName__c= l.PartnerName__c;
           	         l.PartnerName__c = ((Lead)Trigger.oldMap.get(l.Id)).PartnerName__c;
           	         l.Channel_Partner_Name_Update_6__c = true;
           	       }else if(l.PartnerName__c!=null &&  l.PartnerName__c != ((Lead)Trigger.oldMap.get(l.Id)).PartnerName__c ){
           	         l.Prior_Channel_Partner_Name_Change_Date__c = System.today();
           	         l.PriorChannelPartnerName__c =  ((Lead)Trigger.oldMap.get(l.Id)).PartnerName__c ;
                 	}
                 }
	        }
	        if(partnerIDs.size()>0){
	        		Map<String,Id> mapResellingPartnerRep=new Map<String,Id>();
	        		for(Reselling_Partner__c rp:[Select Id,Assigned_Sales_Rep__c,Reselling_Partner__c,Connector__c 
	        									From Reselling_Partner__c 
	        									Where Assigned_Sales_Rep__c!=null AND Reselling_Partner__c=:partnerIDs AND Connector__c=:connectorIDs]){
	        			mapResellingPartnerRep.put(''+rp.Reselling_Partner__c+rp.Connector__c,rp.Assigned_Sales_Rep__c);
	        		}
	        		for(Lead l:(List<Lead>)Trigger.new){
	        			if(l.PartnerName__c!=null && l.Connector__c!=null){
	        				l.Partner_Connector_Assigned_Rep__c=mapResellingPartnerRep.get(''+l.PartnerName__c+l.Connector__c);
	        			}
	        		}
	        }	                		
        //}
    }
     //https://jira.avalara.com/browse/IBST-8008
     //Devloper : Payal Bhawnani 01/23/2018
     protected override void afterUpdate(){
      for(Lead l:(List<Lead>)Trigger.new) 
       {
          if (l.IsConverted)
          {
            isLeadConverted = true;
          } 
       }
     }  
}