Prod/src/objects/Connector__c.object
<CustomObject>
    <description>Used to track all Avalara connectors and associated data</description>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Track the original developer of the code associated with this connector
Integrated: Yes 
Change: Level 1 
Custodian: Business Development / Greg Chapman</description>
        <inlineHelpText>Associate the account of the original developer of the code associated with this connector</inlineHelpText>
        <label>Author</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connectors (Author)</relationshipLabel>
        <relationshipName>Connectors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Managed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Track 30 day delta between old calc estimation and new calc estimation 
Integrated: No 
Change: Level 0 
Custodian: Business Development / Greg Chapman</description>
        <inlineHelpText>Associate the account currently managing / responsible for the code associated with this connector</inlineHelpText>
        <label>Managed By</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connectors (Managed By)</relationshipLabel>
        <relationshipName>Managed_Connectors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Connector</label>
    <nameField>
        <label>Connector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Connector_KB__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Address_Validation_Click_Path__c</fullName>
        <label>Address Validation Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Client_Exemption_Click_Path__c</fullName>
        <label>Client Exemption Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Connector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Connector</label>
        <referenceTo>Connector__c</referenceTo>
        <relationshipLabel>Connector KB</relationshipLabel>
        <relationshipName>Connector_KB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_Level_Addressing__c</fullName>
        <label>Line Level Addressing</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Location_Code_Click_Path__c</fullName>
        <label>Location Code &amp; Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Product_Mapping_Click_Path__c</fullName>
        <label>Product Mapping Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Sales_Tax_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Tax Matrix</label>
        <referenceTo>Functional_Matrix__c</referenceTo>
        <relationshipLabel>Connector KB</relationshipLabel>
        <relationshipName>Connector_KB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Timing_for_Tax_Calculation__c</fullName>
        <label>Timing for Tax Calculation</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Connector KB</relationshipLabel>
        <relationshipName>Connector_KB</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Connector KB</label>
    <pluralLabel>Connector KB</pluralLabel>
</CustomObject>

Prod/src/objects/Draft_Knowledge__c.object
<CustomObject>
    <fields>
        <fullName>Address_Validation_Click_Path__c</fullName>
        <label>Address Validation Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Client_Exemption_Click_Path__c</fullName>
        <label>Client Exemption Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <formula>Sales_Tax_Matrix__r.Company_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Company Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Connector</label>
        <referenceTo>Connector__c</referenceTo>
        <relationshipLabel>Draft Knowledges</relationshipLabel>
        <relationshipName>Draft_Knowledges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_Level_Addressing__c</fullName>
        <label>Line Level Addressing</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Location_Code_Click_Path__c</fullName>
        <label>Location Code &amp; Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Product_Mapping_Click_Path__c</fullName>
        <label>Product Mapping Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Sales_Tax_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Tax Matrix</label>
        <referenceTo>Functional_Matrix__c</referenceTo>
        <relationshipLabel>Draft Knowledges</relationshipLabel>
        <relationshipName>Draft_Knowledges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Draft Knowledges</relationshipLabel>
        <relationshipName>Draft_Knowledges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Draft Knowledge</label>
    <nameField>
        <displayFormat>DK-{0000}</displayFormat>
        <label>Draft Knowledge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Draft Knowledges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Functional_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Address_Validation_Click_Path__c</fullName>
        <inlineHelpText>Describe the path of clicks that the user must take to find the Address Validation button. Is it on the customer record, the invoice/order screen, or both? Is there no button and it automatically happens upon save event?</inlineHelpText>
        <label>Address Validation Click Path</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Client_Exemption_Click_Path__c</fullName>
        <inlineHelpText>Describe the path of clicks that the user must take to find where they can apply Entity Use code or Exemption No data to a customer record.</inlineHelpText>
        <label>Client Exemption Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <inlineHelpText>Describe what value comes across to AvaTax as the Company Code, is it user defined or static?</inlineHelpText>
        <label>Company Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Level_Addressing__c</fullName>
        <inlineHelpText>State whether or not the integration can send AvaTax separate addresses at the line level. If so, describe how it can be done.</inlineHelpText>
        <label>Line Level Addressing</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Location_Code_Click_Path__c</fullName>
        <inlineHelpText>Describe the path of clicks that the user must take to see the value that is sent to AvaTax as the Location Code on transactions.</inlineHelpText>
        <label>Location Code &amp; Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Product_Mapping_Click_Path__c</fullName>
        <inlineHelpText>Describe the path of clicks that the user must take to find the area where they can map products/services to Avalara Tax Codes.</inlineHelpText>
        <label>Product Mapping Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Timing_For_Tax_Calculation__c</fullName>
        <inlineHelpText>Describe the events and triggers which call out to AvaTax. Is it manually by a calculate button? Automatically on save event? State all stages of transaction life cycle where a call is made, estimate, order, invoice etc.</inlineHelpText>
        <label>Timing For Tax Calculation</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Functional Matrix</relationshipLabel>
        <relationshipName>Functional_Matrix</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Functional Matrix</label>
    <nameField>
        <displayFormat>FM-{000000}</displayFormat>
        <label>Functional Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Version__c.object
<CustomObject>
    <description>Used as an associated related list for the connector object to track the version associated with a given connector</description>
    <fields>
        <fullName>Connector__c</fullName>
        <label>Connector</label>
        <referenceTo>Connector__c</referenceTo>
        <relationshipLabel>Versions</relationshipLabel>
        <relationshipName>Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Version</label>
    <nameField>
        <label>Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev/src/classes/AvalaraCommunityWizardCtrlTest.cls
@isTest
private Class AvalaraCommunityWizardCtrlTest{

    @testSetup
    static void setup(){
        Account acc = new Account(
            Name = 'Test Account'
        );
        insert acc;

        Connector__c c = new Connector__c(
            Name = 'Test Connector',
            Author__c = acc.Id,
            Managed_By__c = acc.Id
        );
        insert c;

        Version__c ver = new Version__c(
            Name = 'Text version',
            Connector__c = c.Id
        );
        insert ver;

        Connector_KB__kav knowledge = new Connector_KB__kav(Version__c = ver.Id,Title = 'TestArticle',UrlName = 'TestArticle');
        insert knowledge;

        Draft_Knowledge__c cKnowledge = new Draft_Knowledge__c(Version__c =ver.Id);
        insert cKnowledge;
    }


    static testMethod void testAll(){
        Draft_Knowledge__c ck = [
            SELECT Id,Name,Sales_Tax_Matrix__r.Timing_For_Tax_Calculation__c,
                Company_Code__c,Address_Validation_Click_Path__c,Product_Mapping_Click_Path__c,
                Client_Exemption_Click_Path__c,Location_Code_Click_Path__c,Line_Level_Addressing__c,Sales_Tax_Matrix__c
            FROM Draft_Knowledge__c
            LIMIT 1
        ];
        String accId = [SELECT Id FROM Account LIMIT 1].Id;
        String versionId = [SELECT Id FROM Version__c LIMIT 1].Id;
        AvalaraCommunityWizardCtrl.accountIdOverride = accId;
        AvalaraCommunityWizardCtrl.fetchVersionNote(versionId);
        AvalaraCommunityWizardCtrl.insertVersionNote(versionId,'Test Note');
        AvalaraCommunityWizardCtrl.getToolTips();
        AvalaraCommunityWizardCtrl ctrl = new AvalaraCommunityWizardCtrl();
        ctrl.updateAccountDetail();
        ctrl.selectConnector();
        ctrl.selectVersion();
        ctrl.getActiveConnectors();
        ctrl.getVersions();
        try{
            ctrl.saveRecord();
        }
        catch(exception ex){}
        ctrl.att.Name = 'Test.txt';
        ctrl.att.ParentId = accId;
        ctrl.att.Body = Blob.valueOf('Test');
        ctrl.uploadAttachment();
        ctrl.getVersionAttachment();
        ctrl.getOpenOpportunitiesMap();
        ctrl.saveAndRedirect();
        AvalaraCommunityWizardCtrl.getKnowledge(versionId);
        AvalaraCommunityWizardCtrl.getConnectorKB(versionId);
        ctrl.updateConnector();
        ctrl.toFunctionalMatrix(ck);
        ctrl.getAssociates();
        System.assertEquals(1,[SELECT Id FROM Attachment WHERE ParentId =:accId].size());
    }
}