Prod/src/objects/Connector_KB__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>API__c</fullName>
        <label>API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Validation_Functional_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address Validation Functional Matrix</label>
        <referenceTo>Functional_Matrix__c</referenceTo>
        <relationshipLabel>Connector KB (Address Validation Functional Matrix)</relationshipLabel>
        <relationshipName>Connector_KB_AV</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Exemption_Click_Path__c</fullName>
        <label>Client Exemption Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Comm_Functional_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comm Functional Matrix</label>
        <referenceTo>Functional_Matrix__c</referenceTo>
        <relationshipLabel>Connector KB (Comm Functional Matrix)</relationshipLabel>
        <relationshipName>Connector_KB_Comm</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Configuration_Click_Path__c</fullName>
        <label>Configuration Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Connector KB</relationshipLabel>
        <relationshipName>Connector_KB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Core_Notes__c</fullName>
        <label>Core Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Escalation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Escalation Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Connector KB (Escalation Contact)</relationshipLabel>
        <relationshipName>Connector_KB1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Path__c</fullName>
        <label>Implementation Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Line_Level_Addressing__c</fullName>
        <label>Line Level Addressing</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Location_Code_Click_Path__c</fullName>
        <label>Location Code &amp; Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_Mapping_Click_Path__c</fullName>
        <label>Product Mapping Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Sales_Tax_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Tax Matrix</label>
        <referenceTo>Functional_Matrix__c</referenceTo>
        <relationshipLabel>Connector KB</relationshipLabel>
        <relationshipName>Connector_KB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submit_User_Guide_url__c</fullName>
        <label>Submit User Guide (url)</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Support_Notes__c</fullName>
        <label>Support Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Support_Support_Path__c</fullName>
        <label>Support - Support Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Timing_for_Tax_Calculation__c</fullName>
        <label>Timing for Tax Calculation</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Timing_for_recording_Committing_Transa__c</fullName>
        <label>Timing for recording &amp; Committing Transa</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>User_Guide_URL__c</fullName>
        <label>User Guide URL</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Connector KB</relationshipLabel>
        <relationshipName>Connector_KB</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Connector KB</label>
    <pluralLabel>Connector KB</pluralLabel>
</CustomObject>

Prod/src/objects/Functional_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>API__c</fullName>
        <label>API</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>REST V1</fullName>
                </value>
                <value>
                    <fullName>REST V2</fullName>
                </value>
                <value>
                    <fullName>SOAP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Address_Validation__c</fullName>
        <label>Address Validation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Badges_Achieved</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Exemption_Click_Path__c</fullName>
        <inlineHelpText>Describe the path of clicks that the user must take to find where they can apply Entity Use code or Exemption No data to a customer record.</inlineHelpText>
        <label>Client Exemption Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Communication_Achieved_Date__c</fullName>
        <label>Communication Achieved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Communication__c</fullName>
        <label>Communication</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Badges_Achieved</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <inlineHelpText>Describe what value comes across to AvaTax as the Company Code, is it user defined or static?</inlineHelpText>
        <label>Company Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Configuration_Click_Path__c</fullName>
        <inlineHelpText>Describe the path of clicks that the user must take to find the AvaTax configuration. Also note if it&apos;s gated by permissions.</inlineHelpText>
        <label>Configuration Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Functional Matrix</relationshipLabel>
        <relationshipName>Functional_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Core_Notes__c</fullName>
        <label>Core Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Escalation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Escalation Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Functional Matrix (Escalation Contact)</relationshipLabel>
        <relationshipName>Functional_Matrix2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Functional Matrix (Implementation Contact)</relationshipLabel>
        <relationshipName>Functional_Matrix1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Path__c</fullName>
        <label>Implementation Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Line_Level_Addressing__c</fullName>
        <inlineHelpText>State whether or not the integration can send AvaTax separate addresses at the line level. If so, describe how it can be done.</inlineHelpText>
        <label>Line Level Addressing</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Location_Code_Click_Path__c</fullName>
        <inlineHelpText>Describe the path of clicks that the user must take to see the value that is sent to AvaTax as the Location Code on transactions.</inlineHelpText>
        <label>Location Code &amp; Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>POS_Achieved_Date__c</fullName>
        <label>POS Achieved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>POS__c</fullName>
        <label>POS</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Badges_Achieved</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Mapping_Click_Path__c</fullName>
        <inlineHelpText>Describe the path of clicks that the user must take to find the area where they can map products/services to Avalara Tax Codes.</inlineHelpText>
        <label>Product Mapping Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Refunds_Achieved_Date__c</fullName>
        <label>Refunds Achieved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Refunds__c</fullName>
        <label>Refunds</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Badges_Achieved</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Tax_Achieved_Date__c</fullName>
        <label>Sales Tax Achieved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <label>Sales Tax</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Badges_Achieved</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Support_Notes__c</fullName>
        <label>Support Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Support_Support_Path__c</fullName>
        <label>Support - Support Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Timing_For_Tax_Calculation__c</fullName>
        <inlineHelpText>Describe the events and triggers which call out to AvaTax. Is it manually by a calculate button? Automatically on save event? State all stages of transaction life cycle where a call is made, estimate, order, invoice etc.</inlineHelpText>
        <label>Timing For Tax Calculation</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Timing_for_recording_Committing_Transa__c</fullName>
        <label>Timing for recording &amp; Committing Transa</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <externalId>true</externalId>
        <label>Unique Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Guide_URL__c</fullName>
        <label>User Guide URL</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>VAT_Achieved_Date__c</fullName>
        <label>VAT Achieved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <label>VAT</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Badges_Achieved</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Functional Matrix</relationshipLabel>
        <relationshipName>Functional_Matrix</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Functional Matrix</label>
    <nameField>
        <displayFormat>FM-{000000}</displayFormat>
        <label>Functional Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Matrix</pluralLabel>
    <recordTypes>
        <fullName>Core_Address_Validation</fullName>
        <active>true</active>
        <label>Core Address Validation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Core_Communication</fullName>
        <active>true</active>
        <label>Core Communication</label>
    </recordTypes>
    <recordTypes>
        <fullName>Core_Sales_Tax</fullName>
        <active>true</active>
        <label>Core Sales Tax</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Version__c.object
<CustomObject>
    <description>Used as an associated related list for the connector object to track the version associated with a given connector</description>
    <fields>
        <fullName>Certified_Address_Validation__c</fullName>
        <label>Certified Address Validation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Certified_Calc__c</fullName>
        <label>Certified Calc</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Certified_Communications_Tax__c</fullName>
        <label>Certified Communications Tax</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Certified_Global__c</fullName>
        <label>Certified Global</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Certified_POS__c</fullName>
        <label>Certified POS</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Certified_Returns__c</fullName>
        <label>Certified Product Returns</label>
        <type>Date</type>
    </fields>
    <label>Version</label>
    <nameField>
        <label>Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Avalara Fullqa/src/classes/FunctionalMatrixSyncUtil.cls
/*
* Description : Syncs the field from Article to Functional Matrix
*/
public class FunctionalMatrixSyncUtil{

    private static Map<String,String> rTypeMap = getRecordTypeIds();

    public void process(){
        List<Connector_KB__kav> knowledges = [
            SELECT Id
            FROM Connector_Kb__KAV
            WHERE Id = :ApexPages.CurrentPage().getParameters().get('id')
        ];
        process(knowledges);
    }

    public static void process(List<Connector_KB__kav> knowledges){
        syncFunctionalMatrix( [
            SELECT Id,
                Notes__c,
                KnowledgeArticleId,
                Timing_for_recording_Committing_Transa__c,
                Timing_for_Tax_Calculation__c,
                Line_Level_Addressing__c,
                Location_Code_Click_Path__c,
                Client_Exemption_Click_Path__c,
                Core_Notes__c,
                Product_Mapping_Click_Path__c,
                Company_Code__c,
                Configuration_Click_Path__c,
                Submit_User_Guide_url__c,
                API__c,
                Escalation_Contact__c,
                Contact__c,
                Support_Notes__c,
                Implementation_Path__c,
                Support_Support_Path__c,
                Version__c,
                Version__r.Certified_Calc__c,
                Version__r.Certified_Address_Validation__c,
                Version__r.Certified_Returns__c ,
                Version__r.Certified_Global__c,
                Version__r.Certified_Communications_Tax__c,
                Version__r.Certified_POS__c
            FROM Connector_Kb__Kav
            WHERE Id IN:knowledges
        ]);
    }

    public static List<Functional_Matrix__c> syncFunctionalMatrix(List<Connector_KB__kav> knowledges){

        List<Functional_Matrix__c> matrixList = syncMatrix(knowledges);
        upsert matrixList Unique_Id__c;
        publishArticle( knowledges );
        return matrixList;
    }

    public static List<Connector_KB__kav> publishArticle(List<Connector_KB__kav> knowledges){
        for(Connector_KB__kav ck : knowledges){
            ck.Id = KBManagement.PublishingService.editOnlineArticle(ck.KnowledgeArticleId, true);
        }
        upsert knowledges;
        for(Connector_KB__kav ck : knowledges) {
            KbManagement.PublishingService.publishArticle(ck.KnowledgeArticleId, true);
        }
        return knowledges;
    }

    /*
    * publishes articles that are already draft
    **/
    public static void publishNewArticle(Set<Id> ids){
        for(Connector_KB__kav ck : [
            SELECT Id,KnowledgeArticleId
            FROM Connector_KB__kav
            WHERE Id IN:ids
        ]) {
            KbManagement.PublishingService.publishArticle(ck.KnowledgeArticleId, true);
        }
    }

    private static List<Functional_Matrix__c> syncMatrix(List<Connector_KB__kav> knowledges){
        List<Functional_Matrix__c> matrixList = new List<Functional_Matrix__c>();

        for(Connector_KB__kav obj : knowledges){
            // push fields to corresponding FM
            if(obj.Core_Notes__c <> NULL){
                matrixList.add(toFunctionalMatrix('Core_Address_Validation' , obj));
            }
            if(obj.Version__r.Certified_Communications_Tax__c <> NULL){
                matrixList.add(toFunctionalMatrix('Core_Communication', obj));
            }
            matrixList.add(toFunctionalMatrix('Core_Sales_Tax', obj));

        }
        return matrixList;
    }


    private static Functional_Matrix__c toFunctionalMatrix(String rtDevName, Connector_KB__kav knowledge){
        String recordTypeId = rTypeMap.get(rtDevName);
        Functional_Matrix__c matrix = new Functional_Matrix__c();

        if(rtDevName == 'Core_Sales_Tax' || rtDevName == 'Core_Communication'){
            matrix = new Functional_Matrix__c(
                Unique_Id__c = knowledge.Version__c + '||' + recordTypeId,
                Configuration_Click_Path__c = knowledge.Configuration_Click_Path__c,
                Company_Code__c = knowledge.Company_Code__c,
                Product_Mapping_Click_Path__c = knowledge.Product_Mapping_Click_Path__c,
                Client_Exemption_Click_Path__c = knowledge.Client_Exemption_Click_Path__c,
                Location_Code_Click_Path__c = knowledge.Location_Code_Click_Path__c,
                Line_Level_Addressing__c = knowledge.Line_Level_Addressing__c,
                Timing_For_Tax_Calculation__c = knowledge.Timing_For_Tax_Calculation__c,
                Timing_for_recording_Committing_Transa__c = knowledge.Timing_for_recording_Committing_Transa__c,
                Notes__c = knowledge.Notes__c,
                Version__c = Knowledge.Version__c,
                User_Guide_URL__c = knowledge.Submit_User_Guide_url__c,
                Implementation_Contact__c = knowledge.Contact__c,
                Support_Support_Path__c = knowledge.Support_Support_Path__c,
                Escalation_Contact__c = knowledge.Escalation_Contact__c,
                Core_Notes__c = knowledge.Core_Notes__c,
                RecordTypeId = recordTypeId
            );

            if(rtDevName == 'Core_Communication'){
                // set parent Reference
                knowledge.Comm_Functional_Matrix__r = new Functional_Matrix__c(
                    Unique_Id__c = knowledge.Version__c + '||' + recordTypeId
                );
                matrix.Communication__c = knowledge.Version__r.Certified_Communications_Tax__c <> NULL ? 'Certified' : NULL;
                matrix.Communication_Achieved_Date__c = knowledge.Version__r.Certified_Communications_Tax__c;
            }
            else {
                // set parent Reference
                knowledge.Sales_Tax_Matrix__r = new Functional_Matrix__c(
                    Unique_Id__c = knowledge.Version__c + '||' + recordTypeId
                );

                matrix.Sales_Tax__c = knowledge.Version__r.Certified_Calc__c <> NULL ? 'Certified' : NULL;
                matrix.Refunds__c = knowledge.Version__r.Certified_Returns__c <> NULL ? 'Certified' : NULL;
                matrix.VAT__c = knowledge.Version__r.Certified_Global__c <> NULL ? 'Limited Functionality' : NULL;
                matrix.POS__c = knowledge.Version__r.Certified_POS__c <> NULL ? 'Certified' : NULL;
                matrix.Sales_Tax_Achieved_Date__c = knowledge.Version__r.Certified_Calc__c;
                matrix.POS_Achieved_Date__c = knowledge.Version__r.Certified_POS__c;
                matrix.Refunds_Achieved_Date__c = knowledge.Version__r.Certified_Returns__c;
                matrix.VAT_Achieved_Date__c = knowledge.Version__r.Certified_Global__c;
            }
        }
        else if( rtDevName == 'Core_Address_Validation'){
            matrix = new Functional_Matrix__c(
                Core_Notes__c = knowledge.Core_Notes__c,
                Version__c = knowledge.Version__c,
                Unique_Id__c = knowledge.Version__c + '||' + recordTypeId,
                RecordTypeId = recordTypeId,
                Address_Validation__c = knowledge.Version__r.Certified_Address_Validation__c <> NULL ? 'Certified' : NULL
            );
            // set parent Reference
            knowledge.Address_Validation_Functional_Matrix__r = new Functional_Matrix__c(
                Unique_Id__c = knowledge.Version__c + '||' + recordTypeId
            );
        }


        return matrix;
    }

    private static Map<String,String> getRecordTypeIds(){
        Map<String,String> rTypeMap = new Map<String,String>();
        for(RecordType rt : [
            SELECT Id,DeveloperName
            FROM RecordType WHERE sObjectType = 'Functional_Matrix__c' AND DeveloperName IN ('Core_Address_Validation','Core_Communication','Core_Sales_Tax')
        ]){
            rTypeMap.put(rt.DeveloperName,rt.Id);
        }
        return rTypeMap;
    }
}