Prod/src/objects/Connector__c.object
<CustomObject>
    <description>Used to track all Avalara connectors and associated data</description>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Track the original developer of the code associated with this connector
Integrated: Yes 
Change: Level 1 
Custodian: Business Development / Greg Chapman</description>
        <inlineHelpText>Associate the account of the original developer of the code associated with this connector</inlineHelpText>
        <label>Author</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connectors (Author)</relationshipLabel>
        <relationshipName>Connectors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Managed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Track 30 day delta between old calc estimation and new calc estimation 
Integrated: No 
Change: Level 0 
Custodian: Business Development / Greg Chapman</description>
        <inlineHelpText>Associate the account currently managing / responsible for the code associated with this connector</inlineHelpText>
        <label>Managed By</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connectors (Managed By)</relationshipLabel>
        <relationshipName>Managed_Connectors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Connector</label>
    <nameField>
        <label>Connector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Partner_Launch_Task__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>Certification</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Partner Launch Tasks</relationshipLabel>
        <relationshipName>Partner_Launch_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Partner Launch Task</label>
    <nameField>
        <label>Partner Launch Tasks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Launch Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FullQa New/src/objects/Solution.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Provide a brief explanation of what the solution is about or what the customer is trying to do.</description>
        <inlineHelpText>This field is used to describe the purpose and intent of the solution.  This is not a customer facing field that is viewable in the Public Knowledgebase.</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Avalara Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Avalara AvaTax</fullName>
                </value>
                <value>
                    <fullName>Avalara Returns</fullName>
                </value>
                <value>
                    <fullName>CertCapture</fullName>
                </value>
                <value>
                    <fullName>AvaTax APIs</fullName>
                </value>
                <value>
                    <fullName>Admin Console</fullName>
                </value>
                <value>
                    <fullName>Customer Center</fullName>
                </value>
                <value>
                    <fullName>Account Management</fullName>
                </value>
                <value>
                    <fullName>SST</fullName>
                </value>
                <value>
                    <fullName>Dynamics GP</fullName>
                </value>
                <value>
                    <fullName>Dynamics NAV</fullName>
                </value>
                <value>
                    <fullName>Dynamics AX</fullName>
                </value>
                <value>
                    <fullName>Dynamics RMS</fullName>
                </value>
                <value>
                    <fullName>Mas 90/200</fullName>
                </value>
                <value>
                    <fullName>Mas 500</fullName>
                </value>
                <value>
                    <fullName>Accpac</fullName>
                </value>
                <value>
                    <fullName>Sage Pro ERP</fullName>
                </value>
                <value>
                    <fullName>Netsuite</fullName>
                </value>
                <value>
                    <fullName>Quickbooks</fullName>
                </value>
                <value>
                    <fullName>OEM Connector</fullName>
                </value>
                <value>
                    <fullName>AvaLink</fullName>
                </value>
                <value>
                    <fullName>AvaLocal</fullName>
                </value>
                <value>
                    <fullName>AvaRates</fullName>
                </value>
                <value>
                    <fullName>Ebay Prostores</fullName>
                </value>
                <value>
                    <fullName>Peachtree</fullName>
                </value>
                <value>
                    <fullName>Avalara Onsite</fullName>
                </value>
                <value>
                    <fullName>ISPI</fullName>
                </value>
                <value>
                    <fullName>ISPI Rate Product</fullName>
                </value>
                <value>
                    <fullName>Laserbridge</fullName>
                </value>
                <value>
                    <fullName>CalcTx32.DLL</fullName>
                </value>
                <value>
                    <fullName>SalesTax II</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solution_Type__c</fullName>
        <description>These solution types help define the type of solutions created.</description>
        <label>Solution Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAQ</fullName>
                </value>
                <value>
                    <fullName>ERRMSG</fullName>
                </value>
                <value>
                    <fullName>TUTORIAL</fullName>
                </value>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>GO LIVE GUIDE</fullName>
                </value>
                <value>
                    <fullName>RELEASE NOTES</fullName>
                </value>
                <value>
                    <fullName>MONTHLY MAINTENANCE GUIDE</fullName>
                </value>
                <value>
                    <fullName>INTERNAL</fullName>
                </value>
                <value>
                    <fullName>OEM GUIDE</fullName>
                </value>
                <value>
                    <fullName>USER GUIDE</fullName>
                </value>
                <value>
                    <fullName>SOLUTION PARTNER</fullName>
                </value>
                <value>
                    <fullName>CHANNEL PARTNER</fullName>
                </value>
                <value>
                    <fullName>DEVELOPMENT PARTNER</fullName>
                </value>
                <value>
                    <fullName>AASP PARTNER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Prod/src/objects/Version__c.object
<CustomObject>
    <description>Used as an associated related list for the connector object to track the version associated with a given connector</description>
    <fields>
        <fullName>Connector__c</fullName>
        <label>Connector</label>
        <referenceTo>Connector__c</referenceTo>
        <relationshipLabel>Versions</relationshipLabel>
        <relationshipName>Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Version_KB__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Version KB</label>
        <referenceTo>Solution</referenceTo>
        <relationshipLabel>Versions</relationshipLabel>
        <relationshipName>Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Version</label>
    <nameField>
        <label>Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/classes/AvalaraPartnerTasksCtrlTest.cls
@isTest
private class AvalaraPartnerTasksCtrlTest{
    
    @testSetup
    static void setup(){
        Account acc = new Account(
            Name = 'Test Account'
        );
        insert acc;
        
        Connector__c c = new Connector__c(
            Name = 'Test Connector',
            Author__c = acc.Id,
            Managed_By__c = acc.Id
        );
        insert c;
        
        Solution sol = new Solution(
            SolutionName = 'Solution 1',
            Solution_Type__c  = 'FAQ',
            Description__c = 'Solution Description',
            Product__c = 'Avalara AvaTax'
        );
        insert sol;
        
        Version__c ver = new Version__c(
            Name = 'Text version',
            Connector__c = c.Id,
            Version_KB__c = sol.Id
        );
        insert ver;
         
        Partner_Launch_Task__c tsk = new Partner_Launch_Task__c(Name = 'tsak 1',Version__c = ver.Id,Type__c = 'Administration');
        insert tsk;
    }
    static testMethod void testAll(){
        AvalaraPartnerTasksCtrl ctrl =  new AvalaraPartnerTasksCtrl();
        ctrl.sVersionId = [select Id FROM Version__c LIMIT 1].Id;
        ctrl.getMapTasksByType();
    }
}