Prod/src/objects/Finance_Operations_Close_Event__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Period_End_Date__c</fullName>
        <defaultValue>IF(
  MONTH( TODAY() ) = 12,
  DATE( YEAR( TODAY() ), 12, 31 ),
  DATE( YEAR( TODAY() ), MONTH ( TODAY() ) + 1, 1 ) - 1 
)</defaultValue>
        <label>Booking Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Booking_Period_Start_Date__c</fullName>
        <defaultValue>TODAY()-DAY(TODAY())+1</defaultValue>
        <label>Booking Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EDW_Booking_Freeze_Date__c</fullName>
        <inlineHelpText>This will be populated when EDW is frozen.</inlineHelpText>
        <label>EDW Booking Freeze Date</label>
        <type>DateTime</type>
    </fields>
    <label>Finance Operations Close Event</label>
    <nameField>
        <displayFormat>FPA{0000}</displayFormat>
        <label>Finance Operations Close Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Operations Close Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/ObjectFieldLock__mdt.object
<CustomObject>
    <fields>
        <fullName>Always_Allow_Permission__c</fullName>
        <label>Always Allow Permission</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Always_Editable_Fields__c</fullName>
        <label>Always Editable Fields</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EDW_Freeze_Field__c</fullName>
        <inlineHelpText>This field will be used to determine if EDW is frozen or not.</inlineHelpText>
        <label>EDW Freeze Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exclude_User_IDs__c</fullName>
        <inlineHelpText>Case safe id for users who will be excluded from locking until EDW freeze</inlineHelpText>
        <label>Exclude User IDs</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lockable_Fields__c</fullName>
        <inlineHelpText>Comma separated fields</inlineHelpText>
        <label>Lockable Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Locked_Field__c</fullName>
        <inlineHelpText>This field will be used to determine if record is locked or not. This field should be checkbox</inlineHelpText>
        <label>Locked Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Never_Editable_Fields__c</fullName>
        <inlineHelpText>Comma Separated fields api name</inlineHelpText>
        <label>Never Editable Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>OpportunityLineItem</fullName>
                </value>
                <value>
                    <fullName>CameleonCPQ__Quote__c</fullName>
                </value>
                <value>
                    <fullName>Opportunity_Role_Split__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_Fields__c</fullName>
        <label>Other Fields</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Editable</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Not Editable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Special_Permissions__c</fullName>
        <inlineHelpText>Comma separated permissions from user special permission field who can edit these fields</inlineHelpText>
        <label>User Special Permissions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Was_Record_Locked_Field__c</fullName>
        <inlineHelpText>This field will be used to determine if record was ever locked.</inlineHelpText>
        <label>Was Record Locked Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ObjectFieldLock</label>
    <pluralLabel>ObjectFieldLocks</pluralLabel>
</CustomObject>

FullQa New/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for locking the record from editing</description>
        <inlineHelpText>Used for locking the record from editing</inlineHelpText>
        <label>Locked</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Avalara Fullqa/src/CloudCraze/objects/User.object
<CustomObject>
</CustomObject>

FullQa New/src/objects/User.object
    <fields>
        <fullName>Special_Permission__c</fullName>
        <label>Special Permission</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Merge_Account</fullName>
                </value>
                <value>
                    <fullName>CanUpdateLockedOpportunities</fullName>
                </value>
                <value>
                    <fullName>CanUpdateFrozenOpportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

Avalara Fullqa/src/classes/APIValidateRecordLockTest.cls
@isTest
private class APIValidateRecordLockTest {
	private static Account a;
	private static Contact c;
	private static Opportunity o;
	private static CameleonCPQ__Quote__c cpq;
    static testMethod void testvalidateRecordLock() {
    		APIValidateRecordLock.SkipForUnitTest=false;
		List<ObjectFieldLock__mdt> listObjMDT=[Select Id,Error_Message__c,Lockable_Fields__c,Never_Editable_Fields__c,Notes__c,
												Object_Name__c,User_Special_Permissions__c ,Other_Fields__c,Always_Editable_Fields__c,
												Locked_Field__c,Was_Record_Locked_Field__c,Exclude_User_IDs__c,EDW_Freeze_Field__c,
												Always_Allow_Permission__c
												From ObjectFieldLock__mdt 
												Where Object_Name__c='Opportunity' AND Is_Active__c=true];
		ObjectFieldLock__mdt objMDT;
		if(listObjMDT!=null && listObjMDT.size()==1){
			objMDT=listObjMDT[0];
		}    	
    		User ztbuyAPIUser=[Select id from User Where Id='00533000003RbvNAAS'];
    		Finance_Operations_Close_Event__c foce=new Finance_Operations_Close_Event__c(Booking_Period_Start_Date__c=Date.today().addDays(-10),Booking_Period_End_Date__c=Date.today().addDays(10));
    		insert foce;
   	 	Test.startTest();
	  	//Create an account
    	  	 Id emeaAccountTypeId=[Select Id from RecordType where DeveloperName='EMEA_Account' limit 1].Id;
      	 a =TestUtil.createAccount(emeaAccountTypeId,1,true)[0];
       	//create a contact 
      	 c =TestUtil.createContact(a.Id,5,true)[0];
      	 //create Opportunity
      	 Id defaultOppRecTypeId=[Select Id from RecordType where DeveloperName='Default_OppRecType' limit 1].Id;
      	 o = TestUtil.createOpportunity(a.id,defaultOppRecTypeId,1,true)[0];
      	 //create pros quote
      	 cpq = TestUtil.createProsQuote(a.id,o.id,c.id,1,false)[0];
      	// cpq.OPStatus__c = Constants.PROS_QUOTE_STATUS_COMPLETE;
      	 insert cpq;
      	 System.runAs(ztbuyAPIUser){
	      	 cpq.SentToZBillingDate__c=Date.today();
	      	 update cpq;
      	 }

      	 //Check if user dont have permissions and record is locked.
       	try{
         	   update o;
        	}
        catch(Exception e){
       	   Boolean expectedExceptionThrown =  e.getMessage().contains(objMDT.Error_Message__c) ? true : false;
           System.AssertEquals(expectedExceptionThrown, true);
        }
        //Give unlock permissions to user
        User currentUser=new User(Id=UserInfo.getUserId(),Special_Permission__c='CanUpdateLockedOpportunities');
        update currentUser;
        //UnLock Opportunity
        o.Locked__c=false;
        update o;
        //Now Opportunity is locked. Login as another user and try to update
        User salesUser=[Select id from User Where Profile.Name='Ava2 Sales Person' AND  IsActive=true limit 1];
      	 System.runAs(salesUser){
      	 	o.Locked__c=true;
	       	try{
	         	   update o;
	        	}
	        catch(Exception e){
	       	   Boolean expectedExceptionThrown =  e.getMessage().contains(objMDT.Error_Message__c) ? true : false;
	           System.AssertEquals(expectedExceptionThrown, true);
	        }
      	 } 
		//lock again and then try to unlock as a user who dont have permissions
        o.Locked__c=true;
        update o;		
      	 System.runAs(salesUser){
      	 	o.Locked__c=false;
	       	try{
	         	   update o;
	        	}
	        catch(Exception e){
	       	   Boolean expectedExceptionThrown =  e.getMessage().contains(objMDT.Error_Message__c) ? true : false;
	           System.AssertEquals(expectedExceptionThrown, true);
	        }
      	 }   
      	 //unlock again and update never editable fields
        o.Locked__c=false;
        update o;
        if(String.isNotBlank(objMDT.Never_Editable_Fields__c)){
        		List<String> listFields=objMDT.Never_Editable_Fields__c.split(',');
        		Opportunity updateO=new Opportunity(Id=o.Id);
        		for(String field:listFields){
        			updateO.put(field,null);
        		}
	       	try{
	         	   update updateO;
	        	}
	        catch(Exception e){
	       	   Boolean expectedExceptionThrown =  e.getMessage().contains(objMDT.Error_Message__c) ? true : false;
	           System.AssertEquals(expectedExceptionThrown, true);
	        }        		
        }      
        //freeze all data
        foce.EDW_Booking_Freeze_Date__c=DateTime.now();
        update foce;
  
        	             	        
      	Test.stopTest();
        //unlock after freeze
       	try{
	        o.Locked__c=false;
	        update o; 
        	}
        catch(Exception e){
       	   Boolean expectedExceptionThrown =  e.getMessage().contains(objMDT.Error_Message__c) ? true : false;
           System.AssertEquals(expectedExceptionThrown, true);
        }          
		currentUser.Special_Permission__c='CanUpdateFrozenOpportunity';
        update currentUser;     
        o.Locked__c=false;
        update o;               
    }
}