Prod/src/objects/Functional_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Functional Matrix</relationshipLabel>
        <relationshipName>Functional_Matrix</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Functional Matrix</label>
    <nameField>
        <displayFormat>FM-{000000}</displayFormat>
        <label>Functional Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Functional_Matrix_Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Functional_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Matrix</label>
        <referenceTo>Functional_Matrix__c</referenceTo>
        <relationshipLabel>Functional Matrix Requirements</relationshipLabel>
        <relationshipName>Functional_Matrix_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <inlineHelpText>Requirement Note</inlineHelpText>
        <label>Note</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Functional Matrix Requirements</label>
    <nameField>
        <label>Functional Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functional Matrix Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Note__c.object
<CustomObject>
    <label>Note</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Version__c.object
<CustomObject>
    <description>Used as an associated related list for the connector object to track the version associated with a given connector</description>
    <label>Version</label>
    <nameField>
        <label>Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Avalara Fullqa/src/classes/FMRequirementNoteSyncBatch.cls
public with sharing class FMRequirementNoteSyncBatch implements Database.batchable<SObject>{

    public Database.QueryLocator start(Database.BatchableContext info){
        return Database.getQueryLocator([
            SELECT Id, Note__c, Functional_Matrix__c
            FROM Functional_Matrix_Requirement__c
            WHERE Functional_Matrix__c <> NULL
        ]);
    }

    public void execute(Database.BatchableContext info, List<Functional_Matrix_Requirement__c> scope){
        FunctionalMatrixRequirementHandler.processNotes([
            SELECT Id, RecordTypeId, Version__c
            FROM Functional_Matrix__c
            WHERE Id IN:filter(scope)
        ]);
    }

    public void finish(Database.BatchableContext info){

    }

    private static Set<Id> filter(List<Functional_Matrix_Requirement__c> scope){
        Set<Id> fmIds = new Set<Id>();
        for(Functional_Matrix_Requirement__c fmr : scope){
            if(String.isBlank(fmr.Note__c)){
                fmIds.add(fmr.Functional_Matrix__c);
            }
        }
        return fmIds;
    }

    public static void run(){
        Database.executeBatch(new FMRequirementNoteSyncBatch(), 10);
    }

}