Prod/src/objects/Functional_Matrix__c.object
<CustomObject>
    <label>Functional Matrix</label>
    <nameField>
        <displayFormat>FM-{000000}</displayFormat>
        <label>Functional Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Functional_Matrix_Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>Requirement Date</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Functional_Matrix_Requirements_Config__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Matrix Requirements Config</label>
        <referenceTo>Functional_Matrix_Requirements_Config__c</referenceTo>
        <relationshipLabel>Functional Matrix Requirements</relationshipLabel>
        <relationshipName>Functional_Matrix_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Functional_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Matrix</label>
        <referenceTo>Functional_Matrix__c</referenceTo>
        <relationshipLabel>Functional Matrix Requirements</relationshipLabel>
        <relationshipName>Functional_Matrix_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Functional_Requirement_Name__c</fullName>
        <formula>Functional_Matrix_Requirements_Config__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Functional Requirement Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <inlineHelpText>Requirement Note</inlineHelpText>
        <label>Note</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Functional Matrix Requirements</label>
    <nameField>
        <label>Functional Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functional Matrix Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Functional_Matrix_Requirements_Config__c.object
<CustomObject>
    <fields>
        <fullName>Certification_Type_Sort_Order__c</fullName>
        <formula>CASE( Certification_Type__c , 
&quot;Sales Tax&quot;, 1,
&quot;Refunds&quot;, 2,
&quot;VAT&quot;, 3,
&quot;Duties &amp; Tarrifs&quot;, 4,
&quot;POS&quot;, 5,
&quot;MultiTax&quot;, 6,
&quot;GST&quot;, 7,
&quot;Brazil&quot;, 8,
999)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Certification Type Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Requirement_Type__c</fullName>
        <label>Requirement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Required</fullName>
                </value>
                <value>
                    <fullName>Suggested</fullName>
                </value>
                <value>
                    <fullName>Conditional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SubHeader__c</fullName>
        <label>SubHeader</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subheader_Sort__c</fullName>
        <formula>CASE( SubHeader__c , 
&quot;Administration&quot;, 1,
&quot;Customer Record&quot;, 2,
&quot;Item Record&quot;, 3,
&quot;Sales/Billing Document Integration&quot;, 4,
&quot;Server Audit Clarity&quot;, 5,
999)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subheader Sort</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tool_Tip__c</fullName>
        <label>Tool Tip</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Functional Matrix Requirements Config</label>
    <nameField>
        <label>Functional Matrix Requirements Config Na</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functional Matrix Requirements Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Note__c.object
<CustomObject>
    <label>Note</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev/src/classes/EditMatrixRequirementsCtrl.cls
public class EditMatrixRequirementsCtrl {

    public EditMatrixRequirementsCtrl(ApexPages.StandardController controller) {

    }

    @RemoteAction
    public static Object getUserTimeZone(){
        TimeZone tz = UserInfo.getTimeZone();
        return new Map<String,Object>{
            'name' => tz.getDisplayName(),
            'id' => tz.getID(),
            'offset' => tz.getOffset(DateTime.newInstance(2012,11,23,12,0,0))
        };
    }

    @RemoteAction
    public static List<SObject> getRequirements(String fid){
        return [
            SELECT Id,Name,Date__c,Note__c,Functional_Requirement_Name__c,
                Functional_Matrix_Requirements_Config__r.Section__c,
                Functional_Matrix_Requirements_Config__r.SubHeader__c,Functional_Matrix_Requirements_Config__r.Tool_Tip__c,
                Functional_Matrix_Requirements_Config__r.Requirement_Type__c
            FROM Functional_Matrix_Requirement__c
            WHERE Functional_Matrix_Requirements_Config__r.Section__c <> NULL AND Functional_Matrix__c =:fid
            ORDER BY Functional_Matrix_Requirements_Config__r.Certification_Type_Sort_Order__c ASC,
                Functional_Matrix_Requirements_Config__r.Subheader_Sort__c ASC,
                Functional_Matrix_Requirements_Config__r.Sort_Order__c ASC  NULLS LAST
        ];
    }
    
    @RemoteAction
    public static List<Functional_Matrix_Requirement__c> updateRequirement(List<Functional_Matrix_Requirement__c> req){
        update req;
        return req;   
    } 
}