Prod/src/objects/Functional_Matrix__c.object
<CustomObject>
    <label>Functional Matrix</label>
    <nameField>
        <displayFormat>FM-{000000}</displayFormat>
        <label>Functional Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Functional_Matrix_Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>Requirement Date</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Functional_Matrix_Requirements_Config__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Matrix Requirements Config</label>
        <referenceTo>Functional_Matrix_Requirements_Config__c</referenceTo>
        <relationshipLabel>Functional Matrix Requirements</relationshipLabel>
        <relationshipName>Functional_Matrix_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Functional_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Matrix</label>
        <referenceTo>Functional_Matrix__c</referenceTo>
        <relationshipLabel>Functional Matrix Requirements</relationshipLabel>
        <relationshipName>Functional_Matrix_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <inlineHelpText>Requirement Note</inlineHelpText>
        <label>Note</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Functional Matrix Requirements</label>
    <nameField>
        <label>Functional Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functional Matrix Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Functional_Matrix_Requirements_Config__c.object
<CustomObject>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Functional Matrix Requirements Config</label>
    <nameField>
        <label>Functional Matrix Requirements Config Na</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functional Matrix Requirements Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Note__c.object
<CustomObject>
    <label>Note</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev/src/classes/FunctionalMatrixRequirementListEdit.cls
public with sharing class FunctionalMatrixRequirementListEdit extends EditableList
{
  // Read the explanation in FunctionalMatrixRequirementListEdit(ApexPages.StandardController)
  // to see when to uncomment the following line.

  // public Account myAccount {get; private set;}

  public FunctionalMatrixRequirementListEdit(ApexPages.StandardController stdController) 
  {
    super(stdController);

    // If necessary, explicitly query for additional metadata on parent record
    // if you are looking to display things that don't come back with the
    // StandardController. In that case, you will need to replace the "Account.X"
    // references in the Visualforce Page with references to an Account variable
    // that you will need to declare in this class (myAccount.X). I have commented out
    // an example.

    // this.myAccount = [SELECT Id,
    //                            Name,
    //                            Custom_Relationship__r.Name
    //                        FROM Account
    //                        WHERE Id =: stdController.getRecord().Id];
    
    this.childList = [SELECT Id,Functional_Matrix_Requirements_Config__r.Name,
                          Date__c,
                          Functional_Matrix__c,
                          Note__c,
                          Name,
                          Sort_Order__c
                      FROM Functional_Matrix_Requirement__c
                      WHERE Functional_Matrix__c =: mysObject.Id];
  }

  /*
   * This method is necessary for reference on the Visualforce page, 
   * in order to reference non-standard fields.
   */
  public List<Functional_Matrix_Requirement__c> getChildren()
  {
    return (List<Functional_Matrix_Requirement__c>)childList;
  }

  public override sObject initChildRecord()
  {
    Functional_Matrix_Requirement__c child = new Functional_Matrix_Requirement__c();
    // Can either use mysObject or acct here
    child.Functional_Matrix__c = mysObject.Id;
    
    return child;
  }
}