Prod/src/objects/GoLive_Implementation__c.object
<CustomObject>
    <description>Used by GoLive to track all implementation activities relative to customer onboarding</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>GoLive Implementations</relationshipLabel>
        <relationshipName>GoLive_Implementations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GoLive Implementation</label>
    <nameField>
        <label>GoLive Implementation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GoLive Implementations</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <description>Initial Client Implementation Planning &amp; Risk Profile</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/GoLive_Implementation_Duration__c.object
<CustomObject>
    <fields>
        <fullName>Parent__c</fullName>
        <label>GoLive Implementation</label>
        <referenceTo>GoLive_Implementation__c</referenceTo>
        <relationshipLabel>GoLive Implementation Duration</relationshipLabel>
        <relationshipName>GoLive_Implementation_Duration</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GoLive Implementation Duration</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>GoLive Implementation Duration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GoLive Implementation Duration</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Avalara Fullqa/src/classes/GoLiveDurationTrigger_Test.cls
//
// (c) 2017 Avalara, Inc.
//
// Apex Test Class Name: GoLiveDurationTrigger_Test
// Description: This test class validates the GoLive Duration Trigger for Data insert and Code Coverage.
//
// 10th Apr 2017 RajaSekhara Chellari - Created for code coverage.
//

@isTest
public class GoLiveDurationTrigger_Test {
    
    static testMethod void triggerTestMethOne() {
        
        /*
         Crete Account Data with limited info with covering no validtions.
         Fields Used: Name, Type__c, Industry__c
        */
        Account accRec = new Account();
        accRec.Name='Test Account';
        accRec.Industry = 'Automotive';
        accRec.Type__c='Customer';
        insert accRec;
        
        /*
         Crete GoLive_Implementation Data with limited info with covering no validtions.
         Fields Used: Name, Account__c
        */
        GoLive_Implementation__c GLImplRec = new GoLive_Implementation__c ();
        GLImplRec.name='Go Live Implementation';
        GLImplRec.account__c=accRec.id;
        insert GLImplRec;
        
        /*
         Crete GoLive_Implementation_Duration Data with limited info with covering no validtions.
         Fields used: Parent__c
        */
        GoLive_Implementation_Duration__c  GLImplDRec = new GoLive_Implementation_Duration__c();
        GLImplDRec.parent__c=GLImplRec.id;
        insert GLImplDRec;
    }
}