Prod/src/objects/Partner_Launch_Task__c.object
<CustomObject>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>Certification</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Partner Launch Tasks</relationshipLabel>
        <relationshipName>Partner_Launch_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Partner Launch Task</label>
    <nameField>
        <label>Partner Launch Tasks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Launch Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Version__c.object
<CustomObject>
    <description>Used as an associated related list for the connector object to track the version associated with a given connector</description>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>ITBSE-973</description>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Version</label>
    <nameField>
        <label>Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FullQA/src/classes/AvalaraPartnerTasksCtrl.cls
public without sharing class AvalaraPartnerTasksCtrl {
    public String sVersionId{get;set;}
    public Decimal completedTasks {get;set;}
    public Decimal totalTasks {get;set;}
    
    public Map<String,List<Partner_Launch_Task__c>> getMapTasksByType(){
        completedTasks = 0;
        totalTasks = fetchTasks().size();
        List<Partner_Launch_Task__c> tasks = fetchTasks();
        
        Map<String,List<Partner_Launch_Task__c>> taskMap = new Map<String,List<Partner_Launch_Task__c>>();
        for(Partner_Launch_Task__c plt : tasks){
           if(plt.Complete__c){
               completedTasks++;    
           }
            if(!taskMap.containsKey(plt.Type__c)){
                taskMap.put(plt.Type__c,new List<Partner_Launch_Task__c>());
                   
            } 
            taskMap.get(plt.Type__c).add(plt);    
            
        }
        return taskMap;
    }
    
    private List<Partner_Launch_Task__c> fetchTasks(){
        return [
            SELECT Id,Name, Type__c,Complete__c 
            FROM Partner_Launch_Task__c 
            WHERE Version__c =:sVersionId AND Type__c != NULL ORDER BY Type__c ASC,Sort_Order__c ASC
        ];
    }
}