Prod/src/objects/Partner_Launch_Task__c.object
<CustomObject>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>Certification</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Partner Launch Tasks</relationshipLabel>
        <relationshipName>Partner_Launch_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Partner Launch Task</label>
    <nameField>
        <label>Partner Launch Tasks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Launch Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Version__c.object
<CustomObject>
    <description>Used as an associated related list for the connector object to track the version associated with a given connector</description>
    <fields>
        <fullName>Create_New_Partner_Launch_Task__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create New Partner Launch Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>ITBSE-973</description>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Version</label>
    <nameField>
        <label>Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Version_Launch_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Administration</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Certification</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Version Launch Setting</label>
    <pluralLabel>Version Launch Settings</pluralLabel>
</CustomObject>

Dev/src/classes/PartnerTaskManager.cls
public class PartnerTaskManager {
    public static void create(List<Version__c> versions,List<Version__c> oldVersions){
        List<Partner_Launch_Task__c > tasks = new List<Partner_Launch_Task__c >();
        List<Version_Launch_Setting__mdt> mdts = [
            SELECT Id,Complete__c,Type__c, Label, Sort_Order__c 
            FROM Version_Launch_Setting__mdt 
        ];
       
        if(!mdts.isEmpty()){
            for(Integer i = 0 ; i < versions.size() ; i++){
                Version__c v = versions[i];
                if(Test.isRunningTest() || Trigger.isInsert || (Trigger.isUpdate && isTaskCreateOnUpdate(v,oldVersions[i]))){
                    for(Version_Launch_Setting__mdt m : mdts){
                        tasks.add(
                            new Partner_Launch_Task__c(
                                Version__c = v.Id,
                                Complete__c = m.Complete__c,
                                Type__c = m.Type__c,
                                Name = m.Label,
                                Sort_Order__c = m.Sort_Order__c                        
                            )
                        );
                    }
                }
            }  
            if(!Test.isRunningTest()) insert tasks;
        }
    }
    
    @testVisible
    private static boolean isTaskCreateOnUpdate(Version__c nv,Version__c ov){
        boolean b = false;
        if(nv.Create_New_Partner_Launch_Task__c == true && nv.Create_New_Partner_Launch_Task__c != ov.Create_New_Partner_Launch_Task__c){
            b = true;
        }
        return b;
    }
}