Prod/src/objects/Rollup__c.object
<CustomObject>
    <fields>
        <fullName>Aggregate_Field_Alias__c</fullName>
        <label>Aggregate Field Alias</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <label>Batch Size</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Child_Object_API_Name__c</fullName>
        <label>Child Object API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Destination_Field_API_Name__c</fullName>
        <inlineHelpText>e.g No_Closed_Won_Opps__c on Connector</inlineHelpText>
        <label>Destination Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <label>Object API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_Id_Field__c</fullName>
        <description>This is a relationship field. e.g Connector__c on Opportunity</description>
        <inlineHelpText>This is a relationship field. e.g Connector__c on Opportunity</inlineHelpText>
        <label>Relationship Id Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOQL_Query__c</fullName>
        <label>SOQL Query</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Rollup</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Rollup Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rollups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Avalara Fullqa/src/classes/JobProcessRollupTest.cls
@isTest
private class JobProcessRollupTest {
	 @testSetup static void setup() {
        Account acc;
        Opportunity opp;    	
        Id customerAccountTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'EMEA_Account' LIMIT 1].Id;
        acc = TestUtil.createAccount(customerAccountTypeId, 1, true)[0];
        //Create an Opportunity record
        Id defaultOppRecTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Default_OppRecType' LIMIT 1].Id;
        opp = TestUtil.createOpportunity(acc.id, defaultOppRecTypeId, 1, false)[0];
        opp.Amount = 1000;
        opp.PartnerName__c=acc.Id;
        opp.SubType__c = 'Upgrade';
        opp.BookedValue__c = 1000;
        insert opp;    
        Rollup__c r=new Rollup__c(Object_API_Name__c='Account',Relationship_Id_Field__c='PartnerName__c',Destination_Field_API_Name__c='Total_Revenue__c',Aggregate_Field_Alias__c='Total_Revenue__c',Batch_Size__c=50,SOQL_Query__c='select PartnerName__c,sum(BookedValue__c) Total_Revenue__c from Opportunity Where PartnerName__c!=null Group By PartnerName__c',Child_Object_API_Name__c='Opportunity');
        insert r; 	 	
	 }
    static testMethod void test1() {
 
        Test.startTest();
        JobProcessRollup.runJobNow(); 
         Test.stopTest();      
    }
    static testMethod void test2() {
 
        Test.startTest();
       
		JobProcessRollup m = new JobProcessRollup('Select Name,count(Id) from User group by Name limit 0',null,null,null,null,null);
        String seconds = '0'; //Execute at Zero Seconds
        String minutes = '0'; //Execute at every 0 minute of hour
        String hours = '02'; // Execute at 1 AM
        String dayOfMonth = '*'; // Execute Every Day of the Month
        String month = '*'; //Execute every Month
        String dayOfWeek = '?'; //Execute on all 7 days of the Week
        ID oppbatchprocessid = Database.executeBatch(m,200);  
        
        //Seconds Minutes Hours Day_of_month Month Day_of_week optional_year
        String sch = seconds + ' ' + minutes + ' ' + hours + ' ' + dayOfMonth + ' ' + month + ' ' + dayOfWeek;
        //String sch = '0 0 01 * * ?';
        system.schedule('JobProcessRollup Run Everyday at 2am', sch, m);  
         Test.stopTest();      
    }    
}