Prod/src/objects/SST_Onboarding__c.object
<CustomObject>
    <description>https://jira.avalara.com/browse/ITBSE-1469
To save customer response for SST</description>
    <fields>
        <fullName>SST_State_Selection__c</fullName>
        <label>(NA)SST_State_Selection</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
                <value>
                    <fullName>North Carolina</fullName>
                </value>
                <value>
                    <fullName>North Dakota</fullName>
                </value>
                <value>
                    <fullName>Ohio</fullName>
                </value>
                <value>
                    <fullName>Oklahoma</fullName>
                </value>
                <value>
                    <fullName>Rhode Island</fullName>
                </value>
                <value>
                    <fullName>South Dakota</fullName>
                </value>
                <value>
                    <fullName>Tennessee</fullName>
                </value>
                <value>
                    <fullName>Utah</fullName>
                </value>
                <value>
                    <fullName>Vermont</fullName>
                </value>
                <value>
                    <fullName>Washington</fullName>
                </value>
                <value>
                    <fullName>West Virginia</fullName>
                </value>
                <value>
                    <fullName>Wisconsin</fullName>
                </value>
                <value>
                    <fullName>Wyoming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SST Onboarding</label>
    <nameField>
        <displayFormat>SST-{0000}</displayFormat>
        <label>SST Onboarding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SST Onboardings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/classes/SSTWizardController.cls
public class SSTWizardController {
	 @AuraEnabled
    public static string save(SST_Onboarding__c sstData,String signatureBody){
        try{ 
        	//sstData.SST_State_Selection__c=String.join(sstStatePicklistselected, ';');
            insert sstData; 
             Attachment a = new Attachment();
             a.ParentId = sstData.id; // record id of object.
             a.Body = EncodingUtil.base64Decode(signatureBody);
             a.ContentType = 'image/png';
             a.Name = 'Signature Capture.png';
             insert a;     
        } 
        catch(Exception ex){
            return ex.getMessage();
        }
        return 'record successfully insert';  
    }   
	 @AuraEnabled
    public static List<String> getPicklistvalues(String objectName, String field_apiname,Boolean nullRequired){
        List<String> optionlist = new List<String>();
        
        Map<String,Schema.SObjectType> gd = Schema.getGlobalDescribe(); 
        Map<String, Schema.SObjectField> field_map = gd.get(objectName.toLowerCase()).getDescribe().fields.getMap(); 
        
        List<Schema.PicklistEntry> picklistValues = field_map.get(field_apiname).getDescribe().getPickListValues();
        
        for (Schema.PicklistEntry pv : picklistValues) {
            optionlist.add(pv.getValue());
        }
        return optionlist;
    }  
}