Prod/src/objects/SST_Onboarding__c.object
<CustomObject>
    <description>https://jira.avalara.com/browse/ITBSE-1469
To save customer response for SST</description>
    <fields>
        <fullName>Business_Entity_Type__c</fullName>
        <description>Click tools mapping</description>
        <label>Business Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CO - Corporation</fullName>
                </value>
                <value>
                    <fullName>GO - Government</fullName>
                </value>
                <value>
                    <fullName>LL - Limited Liability</fullName>
                </value>
                <value>
                    <fullName>SP - Sole proprietor</fullName>
                </value>
                <value>
                    <fullName>PA - Partnership</fullName>
                </value>
                <value>
                    <fullName>TR - Trusts</fullName>
                </value>
                <value>
                    <fullName>OT - Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SST_State_Selection__c</fullName>
        <label>(NA)SST_State_Selection</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
                <value>
                    <fullName>North Carolina</fullName>
                </value>
                <value>
                    <fullName>North Dakota</fullName>
                </value>
                <value>
                    <fullName>Ohio</fullName>
                </value>
                <value>
                    <fullName>Oklahoma</fullName>
                </value>
                <value>
                    <fullName>Rhode Island</fullName>
                </value>
                <value>
                    <fullName>South Dakota</fullName>
                </value>
                <value>
                    <fullName>Tennessee</fullName>
                </value>
                <value>
                    <fullName>Utah</fullName>
                </value>
                <value>
                    <fullName>Vermont</fullName>
                </value>
                <value>
                    <fullName>Washington</fullName>
                </value>
                <value>
                    <fullName>West Virginia</fullName>
                </value>
                <value>
                    <fullName>Wisconsin</fullName>
                </value>
                <value>
                    <fullName>Wyoming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SST Onboarding</label>
    <nameField>
        <displayFormat>SST-{0000}</displayFormat>
        <label>SST Onboarding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SST Onboardings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/classes/SSTWizardControllerTest.cls
@isTest
public class SSTWizardControllerTest {
	private static SST_Onboarding__c sstOnb;
	
	 //Test for Save data
    static testMethod void testSSTPicklistSave() {
       Test.startTest();
	       //Create SST 
	       //developer name and schema to get piclist value 
	       sstOnb =TestUtil.createSSTOnboarding(1,false)[0];
           List<String> sstState = new List<String>();
           Schema.DescribeFieldResult fieldResultATS = SST_Onboarding__c.SST_State_Selection__c.getDescribe();
		   List<Schema.PicklistEntry> sstStateSelected = fieldResultATS.getPicklistValues();
		   for( Schema.PicklistEntry pickListVal : sstStateSelected){
			  sstState.add(pickListVal.getLabel());
		   }    
	       SSTWizardController.save(sstOnb,null);
       Test.stopTest();
       
    } 
    static testMethod void testSSTPicklistCheck() {
       Test.startTest();
	       //Create an account
	       //developer name and schema to get piclist value 
	       sstOnb =TestUtil.createSSTOnboarding(1,false)[0];
	       sstOnb.Business_Entity_Type__c = SSTWizardController.getPicklistvalues('SST_Onboarding__c','Business_Entity_Type__c',false)[0];
	       insert sstOnb;
       Test.stopTest();
       
    }
}