FullQa New/src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting_Type_CP__c</fullName>
        <description>ChiliPiper Fields</description>
        <label>CP Meeting Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Interest</fullName>
                </value>
                <value>
                    <fullName>Discoverey</fullName>
                </value>
                <value>
                    <fullName>Demonstration</fullName>
                </value>
                <value>
                    <fullName>Discovery Call</fullName>
                </value>
                <value>
                    <fullName>Introduction and Need Assessment</fullName>
                </value>
                <value>
                    <fullName>Outbound Works - SDR Team</fullName>
                </value>
                <value>
                    <fullName>SOHO Introduction and Need Assessment</fullName>
                </value>
                <value>
                    <fullName>Dreamforce 2017</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Connector__c.object
<CustomObject>
    <description>Used to track all Avalara connectors and associated data</description>
    <label>Connector</label>
    <nameField>
        <label>Connector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev/src/Sertifi E-Sign for Salesforce.com/objects/Contact.object
<CustomObject>
</CustomObject>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Meeting_Type_CP__c</fullName>
        <description>ChiliPiper Custom Fields</description>
        <label>CP Meeting Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Demonstration</fullName>
                </value>
                <value>
                    <fullName>Discovery Call</fullName>
                </value>
                <value>
                    <fullName>Introduction and Need Assessment</fullName>
                </value>
                <value>
                    <fullName>Outbound Works - SDR Team</fullName>
                </value>
                <value>
                    <fullName>SOHO Introduction and Need Assessment</fullName>
                </value>
                <value>
                    <fullName>Dreamforce 2017</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>SubType__c</fullName>
        <description>Update: IBST-9676</description>
        <formula>CASE(Account.RecordTypeId, &quot;01233000000Ue6l&quot;, &quot;Trustfile Bharat&quot;, &quot;012330000005hcF&quot;, &quot;Brazil&quot;, &quot;01233000000Udyw&quot;, &quot;Communications&quot;, &quot;01240000000Ubqg&quot;, &quot;Excise&quot;, &quot;01240000000Ubql&quot;, &quot;Excise&quot;, &quot;01233000000Ue4G&quot;, &quot;MyLodge&quot;, &quot;01233000000MIr9&quot;, &quot;CertCapture&quot;, &quot;012330000005hjV&quot;, &quot;Avalara Trustfile&quot;, &quot;01233000000MImx&quot;, &quot;EMEA&quot;, &quot;01233000000MIyU&quot;, &quot;SOHO&quot;, &quot;0120b0000005ip7&quot;, &quot;Included&quot;, &quot;AvaTax&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SubType</label>
        <type>Text</type>
    </fields>

Prod/src/objects/JX_Data_Feed__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>JX Data Feeds</relationshipLabel>
        <relationshipName>JX_Data_Feeds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>JX Data Feed</label>
    <nameField>
        <displayFormat>jxdf{0000}</displayFormat>
        <label>JX Data Feed ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JX Data Feeds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FullQa New/src/objects/KeyPairValue__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To store Opportunity Type and Meeting type for EventTriggerHandler</description>
    <fields>
        <fullName>Values__c</fullName>
        <label>Values</label>
        <type>TextArea</type>
    </fields>
    <label>KeyPairValue</label>
</CustomObject>

Dev/src/classes/EventTriggerHandler.cls
public class EventTriggerHandler extends TriggerHandler {
	
	 //Trigger Handler Methods
	 //customsetting : KeyPairValue__c KeyPairValue
	 
  	protected override void beforeInsert(){
  	 //TECHDEBT: PAYAL 9/15/2017
     //Trigger to Add Events to Opportunity Activity History
     //Jira Ticket : https://jira.avalara.com/browse/IBST-5148?filter=-1
     //create constnt class   
      Set<Id> contactId = new Set<Id>();
      Set<Id> accountID = new Set<Id>();
      Map<Id,Id> accConMap = new Map<Id,Id>(); 
      for( Event e : (List<Event>)Trigger.new)
      {
         if (e.whoid!=null&&e.whoid.getsobjecttype()==Contact.sObjectType){
          	contactId.add(e.WhoId);   
          	//accountID.add(e.WhoId.AccountID);
         }
      }
      for(Contact con : [Select AccountID from Contact where Id IN :contactId]){
         accountID.add(con.AccountID);
         accConMap.put(con.AccountID,con.id);
      }
      if(contactId.size()>0){
      	Map<Id,Id> mapContactOpp = new Map<Id,Id>();  
      	Map<Id,Id> mapContactJX = new Map<Id,Id>();
      	String csOpportunitySubType;
        List<String> listOppSubType = new List<String>();
        csOpportunitySubType = KeyPairValue__c.getInstance('OpportunitySubType').Values__C; 
        listOppSubType=csOpportunitySubType.split('@@');  

        for(OpportunityContactRole oCR : [SELECT ContactId, OpportunityId, CreatedDate,Opportunity.Type,Opportunity.Connector__c,Opportunity.SubType__c,
                                         Opportunity.CloseDate FROM OpportunityContactRole WHERE Opportunity.Type = 'New' AND Opportunity.Connector__c != null AND 
                                         Opportunity.SubType__c = :listOppSubType AND Opportunity.isClosed=false AND ContactId = : contactId ORDER BY CreatedDate DESC]){
    
              mapContactOpp.put(oCR.ContactId,oCR.OpportunityId); 
        }
        Id implementationCaseRecTypeId=[Select Id from RecordType where DeveloperName='Activation' limit 1].Id;
        for(JX_Data_Feed__c jx: [Select id,Account__c from JX_Data_Feed__c where Account__c=:accountID ]){
             mapContactJX.put(accConMap.get(jx.Account__c),jx.id);      
             //System.debug('Contact and Case '+ c.contactid +','+c.id);
        }
      
        for( Event e : (List<Event>)Trigger.new)
         {          
             if (e.WhoId != null && mapContactOpp.containsKey(e.WhoId))
             {         
                e.WhatID = mapContactOpp.get(e.WhoId);        
             }
             //BATS-729
             else if(e.WhoId != null && mapContactJX.containsKey(e.WhoId)/*&& Meeting_Type_CP__c*/){
                 e.WhatID =mapContactJX.get(e.WhoId);
             }   
         }
      }
  	}

    /*
  	protected override void beforeUpdate(){}

    protected override void beforeDelete(){}

  	protected override void afterInsert(){}

  	protected override void afterUpdate(){}

  	protected override void afterDelete(){}

  	protected override void afterUndelete(){}
	*/
    //Helper Methods
  
}