FullQa New/src/objects/Badge__c.object
<CustomObject>
    <fields>
        <fullName>Date_Achieved__c</fullName>
        <label>Date Achieved</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Functional_Matrix_Ext_Id__c</fullName>
        <externalId>true</externalId>
        <label>Functional Matrix Ext Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Functional_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Matrix</label>
        <referenceTo>Functional_Matrix__c</referenceTo>
        <relationshipLabel>Badges</relationshipLabel>
        <relationshipName>Badges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Badges_Achieved</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Tax</fullName>
                </value>
                <value>
                    <fullName>Refunds</fullName>
                </value>
                <value>
                    <fullName>VAT</fullName>
                </value>
                <value>
                    <fullName>Duties &amp; Tarrifs</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>MultiTax</fullName>
                </value>
                <value>
                    <fullName>GST</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Address Validation</fullName>
                </value>
                <value>
                    <fullName>Communication</fullName>
                </value>
                <value>
                    <fullName>Use Tax</fullName>
                </value>
                <value>
                    <fullName>Document Management</fullName>
                </value>
                <value>
                    <fullName>Lodging</fullName>
                </value>
                <value>
                    <fullName>Excise</fullName>
                </value>
                <value>
                    <fullName>Sales Tax - AvaTax</fullName>
                </value>
                <value>
                    <fullName>Customs Duty &amp; Import Tax</fullName>
                </value>
                <value>
                    <fullName>Provisioning</fullName>
                </value>
                <value>
                    <fullName>Sales Tax - TrustFile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Badges</relationshipLabel>
        <relationshipName>Badges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Badge</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Badge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FullQa New/src/objects/Functional_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Functional Matrix</relationshipLabel>
        <relationshipName>Functional_Matrix</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Functional Matrix</label>
    <nameField>
        <displayFormat>FM-{000000}</displayFormat>
        <label>Functional Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Functional_Matrix_Badge_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Date_Achieved_Field__c</fullName>
        <label>Date Achieved Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Field__c</fullName>
        <label>Status Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_Field__c</fullName>
        <inlineHelpText>Maps the field label of the entered field to Badge.Type</inlineHelpText>
        <label>Type Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Functional Matrix Badge Mapping</label>
    <pluralLabel>Functional Matrix Badge Mappings</pluralLabel>
</CustomObject>

FullQa New/src/objects/Version__c.object
<CustomObject>
    <description>Used as an associated related list for the connector object to track the version associated with a given connector</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Certified</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Certified</fullName>
                </value>
                <value>
                    <fullName>Revoked/Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Version</label>
    <nameField>
        <label>Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FullQa New/src/classes/FunctionalMatrixToBadge.cls
public class FunctionalMatrixToBadge {

    private static Map<String, Schema.SObjectField> fieldMap;
    /*
    * Description : creates the badges based on core type from the Functional_Matrix_Badge_Mapping__mdt
    **/
    public static void processBadge(Map<Id,Functional_Matrix__c> newMap,Map<Id,Functional_Matrix__c> oldMap) {
        List<Badge__c> badges = new List<Badge__c>();
        List<String> delBadges = new List<String>();
        List<Functional_Matrix_Badge_Mapping__mdt> settings = getData();
        for(Functional_Matrix__c obj : newMap.values()){
            for(Functional_Matrix_Badge_Mapping__mdt s : settings){
                if(
                    (Trigger.isInsert == TRUE && obj.get(s.Status_Field__c) != null)
                    || (Trigger.isUpdate == TRUE && obj.get(s.Status_Field__c) != null && oldMap.get(obj.Id).get(s.Status_Field__c) != obj.get(s.Status_Field__c))
                ){
                    String label = getLabel(s.Type_Field__c);
                    Badge__c b = new Badge__c(
                        Functional_Matrix_Ext_Id__c = label + '||' + obj.Id,
                        Type__c = label,
                        Version__c = obj.Version__c,
                        Functional_Matrix__c = obj.Id
                    );
                    b.put('Status__c', obj.get(s.Status_Field__c));
                    b.put('Date_Achieved__c', obj.get(s.Date_Achieved_Field__c));
                    System.debug(' obj.get(s.Date_Achieved_Field__c)>>>>>'+ obj.get(s.Date_Achieved_Field__c));
                    badges.add(b);
                }
                else if(Trigger.isUpdate && obj.get(s.Status_Field__c) == null && oldMap.get(obj.Id).get(s.Status_Field__c) != obj.get(s.Status_Field__c)){
                    delBadges.add(getLabel(s.Type_Field__c) + '||' + obj.Id);
                }
            }
        }
        // delete any mismatching badges
        if(!delBadges.isEmpty()){
            delete [
                SELECT id
                FROM Badge__c
                WHERE Functional_Matrix_Ext_Id__c IN :delBadges
            ];
        }
        if(!badges.isEmpty()){
            upsert badges Functional_Matrix_Ext_Id__c;
        }
    }

    private static List<Functional_Matrix_Badge_Mapping__mdt> getData(){
        return[
            SELECT Id,Type_Field__c,Status_Field__c,Date_Achieved_Field__c
            FROM Functional_Matrix_Badge_Mapping__mdt
        ];
    }

    private static String getLabel(String fieldApi){
        if(fieldMap == NULL){
            fieldMap = Schema.SObjectType.Functional_Matrix__c.fields.getMap();
        }
        return fieldMap.get(fieldApi).getDescribe().getLabel();
    }
}