FullQa New/src/objects/Badge__c.object
<CustomObject>
    <fields>
        <fullName>Date_Achieved__c</fullName>
        <label>Date Achieved</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <formula>CASE(Type__c, 
&quot;Sales Tax&quot;, 1,
&quot;Refunds&quot;, 2,
&quot;Address Validation&quot;, 3,
&quot;VAT&quot;, 4,
&quot;Customs Duty &amp; Import Tax&quot;, 5,
&quot;GST&quot;, 6,
&quot;Brazil&quot;, 7,
&quot;POS&quot;, 8,
&quot;MultiTax&quot;, 9,
&quot;Extractor&quot;, 10,
&quot;Document Management&quot;, 11,
&quot;Communication&quot;, 12,
&quot;Lodging&quot;, 13,
&quot;Excise&quot;, 14,
&quot;Provisioning&quot;,15,
null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Badges_Achieved</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Tax</fullName>
                </value>
                <value>
                    <fullName>Refunds</fullName>
                </value>
                <value>
                    <fullName>VAT</fullName>
                </value>
                <value>
                    <fullName>Duties &amp; Tarrifs</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>MultiTax</fullName>
                </value>
                <value>
                    <fullName>GST</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Address Validation</fullName>
                </value>
                <value>
                    <fullName>Communication</fullName>
                </value>
                <value>
                    <fullName>Use Tax</fullName>
                </value>
                <value>
                    <fullName>Document Management</fullName>
                </value>
                <value>
                    <fullName>Lodging</fullName>
                </value>
                <value>
                    <fullName>Excise</fullName>
                </value>
                <value>
                    <fullName>Sales Tax - AvaTax</fullName>
                </value>
                <value>
                    <fullName>Customs Duty &amp; Import Tax</fullName>
                </value>
                <value>
                    <fullName>Provisioning</fullName>
                </value>
                <value>
                    <fullName>Sales Tax - TrustFile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Badges</relationshipLabel>
        <relationshipName>Badges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Badge</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Badge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FullQa New/src/objects/Connector__c.object
<CustomObject>
    <description>Used to track all Avalara connectors and associated data</description>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Track the original developer of the code associated with this connector
Integrated: Yes 
Change: Level 1 
Custodian: Business Development / Greg Chapman</description>
        <inlineHelpText>Associate the account of the original developer of the code associated with this connector</inlineHelpText>
        <label>Author</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connectors (Author)</relationshipLabel>
        <relationshipName>Connectors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Early_Adopter_Sales_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to identify BD user who is managing the launch process in the early adoption phase
Owner: Jesse Powell

Updated 7.11.17 - Changed Field Lable to BD Sales Owner - Request by Alex DeBlois approved by Marshal K.

https://jira.avalara.com/browse/IBST-4190</description>
        <label>BD Sales Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Connectors3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PLT_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Requested by Mark Wilhelm
Integrated: No 
Change: Level 1 
Custodian: Partner Launch Team/Mark Wilhelm

Ticket: https://jira.avalara.com/browse/SFCOM-7079</description>
        <inlineHelpText>Partner Launch Team Owner</inlineHelpText>
        <label>PLT Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Connectors2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Platform_Cateogry__c</fullName>
        <description>Purpose: Track the platform category
Integrated: Yes (DW, Zuora) 
Change: Level 2 
Custodian: VP Sales</description>
        <inlineHelpText>The platform category assigned to the connector designating its pricing structure. A value in this field will make it available for quoting workflows.</inlineHelpText>
        <label>Platform Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TBD</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Level 0</fullName>
                </value>
                <value>
                    <fullName>Level 1</fullName>
                </value>
                <value>
                    <fullName>Level 2</fullName>
                </value>
                <value>
                    <fullName>Level 3</fullName>
                </value>
                <value>
                    <fullName>Level 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Track SAM associated with this connector
Integrated: No 
Change: Level 0 
Custodian: Partner Management</description>
        <inlineHelpText>Enter the SAM associated with this connector</inlineHelpText>
        <label>SAM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Connectors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>X30_Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Delayed by Partner</fullName>
                </value>
                <value>
                    <fullName>Existing - Not Certified</fullName>
                </value>
                <value>
                    <fullName>Certified</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vibrancy__c</fullName>
        <description>Purpose: Track 30 day delta between old calc estimation and new calc estimation 
Integrated: No 
Change: Level 0 
Custodian: VP Business Development</description>
        <inlineHelpText>The current vibrancy category of this connector relative to their engagement level indicating active (Sales), inactive(SAM) or revive(BiZdev).</inlineHelpText>
        <label>Vibrancy</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Established</fullName>
                </value>
                <value>
                    <fullName>Emerging</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Launch</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Connector</label>
    <nameField>
        <label>Connector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FullQa New/src/objects/Version__c.object
<CustomObject>
    <description>Used as an associated related list for the connector object to track the version associated with a given connector</description>
    <fields>
        <fullName>Connector__c</fullName>
        <label>Connector</label>
        <referenceTo>Connector__c</referenceTo>
        <relationshipLabel>Versions</relationshipLabel>
        <relationshipName>Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Parent_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Sub Versions</relationshipLabel>
        <relationshipName>Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>ITBSE-973</description>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Certified</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Certified</fullName>
                </value>
                <value>
                    <fullName>Revoked/Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Version</label>
    <nameField>
        <label>Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FullQa New/src/classes/CFSearch.cls
public class CFSearch {
	@AuraEnabled
    public static List<Connector__c> searchConnectors(String searchString){
        //return [Select Id,Name From Connector__c limit 10];
		String newSearchText = '%'+searchString+'%';
        system.debug('newSearchText==='+newSearchText);
       // List<Connector__c> connectorsSearch = [FIND :searchString IN NAME FIELDS RETURNING Connector__c(Id)][0];
        List<Connector__c> connectors =  [
            SELECT Id,Name, Expanded__c,Vibrancy__c, Platform_Cateogry__c, SAM__r.Name, Author__c,SAM__r.Email,PLT_Owner__c,PLT_Owner__r.Name,PLT_Owner__r.Email,
                Early_Adopter_Sales_Owner__r.Name, Early_Adopter_Sales_Owner__c, SAM__c,Early_Adopter_Sales_Owner__r.Email,
                (SELECT Id,Name FROM Versions__r WHERE Parent_Version__c=null AND Status__c != 'Revoked/Terminated' Order By Sort_Order__c ASC NULLS FIRST)
            FROM Connector__c
            WHERE Name LIKE :newSearchText AND 
                 Vibrancy__c != 'Error'
                AND Vibrancy__c != 'Marketing'
        ];  
        return connectors;
    }
	@AuraEnabled
    public static List<Version__c> getSubVersions(Id vId){
        List<Version__c> versions =  [
            SELECT Id,Name,
            (Select Id, Name, Status__c, Type__c, Version__c,Date_Achieved__c 
             From Badges__r 
             WHERE Type__c <> NULL AND Status__c <> NULL) FROM Version__c 
            WHERE Parent_Version__c=:vId AND Status__c != 'Revoked/Terminated' 
            Order By Sort_Order__c ASC NULLS FIRST
        ];  
        return versions;
    } 
	@AuraEnabled
    public static List<Badge__c> getBadges(Id vId){
        List<Badge__c> badges =  [
            Select Id, Name, Status__c, Type__c, Version__c,Date_Achieved__c 
             From Badge__c 
             WHERE Type__c <> NULL AND Status__c <> NULL AND Version__c=:vId
        ];  
        return badges;
    }     
}