FullQa New/src/objects/CC_AVA_KeyPairValue__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is being used for Cloud Craze custom development. For more info please contact Navees</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC_AVA_KeyPairValue</label>
</CustomObject>

Dev/src/Sertifi E-Sign for Salesforce.com/objects/Contact.object
<CustomObject>
</CustomObject>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Authorized_Identity_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Online Authorized</label>
        <type>Checkbox</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Channel_Partner_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Channel Partner Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Channel_Partner_Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Map channel partner sales rep from Lead/Opportunity
Integrated: Yes 
Change: Level 1 
Custodian: Partner Portal / VP Partner Operations</description>
        <label>Channel Partner Sales Rep</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>ContactStatus__c</fullName>
        <description>Contact Status</description>
        <inlineHelpText>Contact Status</inlineHelpText>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Suspect</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>MQL</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>mk_customer_fit_avatax_score__c</fullName>
        <label>MK Customer Fit Score AvaTax</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>mk_lead_avatax_score__c</fullName>
        <label>MK Lead Score AvaTax</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Most_Recent_Conversion_Date__c</fullName>
        <description>Populated by Eloqua when a contact comes through  to Salesforce from an Eloqua form
Integrated: Yes
Marketing: Jessica Davis</description>
        <label>Most Recent Conversion Date</label>
        <type>Date</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Offer__c</fullName>
        <description>Offering will be used for Contact DemandFunnel tracking showing the source of the contact
Marketing: Jessica Davis</description>
        <label>Offer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blog</fullName>
                </value>
                <value>
                    <fullName>Case Study</fullName>
                </value>
                <value>
                    <fullName>Content Syndication Whitepaper</fullName>
                </value>
                <value>
                    <fullName>Corporate Sponsored Event</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Direct to Rep</fullName>
                </value>
                <value>
                    <fullName>Free Rates</fullName>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>General Contact</fullName>
                </value>
                <value>
                    <fullName>Newsletter</fullName>
                </value>
                <value>
                    <fullName>OBTM</fullName>
                </value>
                <value>
                    <fullName>Online Buying</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Partner Event</fullName>
                </value>
                <value>
                    <fullName>Product Offering</fullName>
                </value>
                <value>
                    <fullName>Prospecting</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Referral Program</fullName>
                </value>
                <value>
                    <fullName>Road Show</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>Through-partner syndication</fullName>
                </value>
                <value>
                    <fullName>Tradeshow</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
                <value>
                    <fullName>Webinar</fullName>
                </value>
                <value>
                    <fullName>Website Visit</fullName>
                </value>
                <value>
                    <fullName>Web Tools</fullName>
                </value>
                <value>
                    <fullName>Whitepaper</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Opportunity_Sub_Type__c</fullName>
        <label>Opportunity Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACP</fullName>
                </value>
                <value>
                    <fullName>AvaTax</fullName>
                </value>
                <value>
                    <fullName>BevAlc</fullName>
                </value>
                <value>
                    <fullName>BizDev</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>CertCapture</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Cross-border</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Excise</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>MatrixMaster</fullName>
                </value>
                <value>
                    <fullName>MyLodge</fullName>
                </value>
                <value>
                    <fullName>SOHO</fullName>
                </value>
                <value>
                    <fullName>TrustFile</fullName>
                </value>
                <value>
                    <fullName>TrustFile Bharat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Partner_Contact_Not_Found_Email_Sent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Partner Contact Not Found Email Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Partner_Rep_Email__c</fullName>
        <label>Partner Rep Email</label>
        <type>Email</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Prior_Channel_Partner_Name_Change_Date__c</fullName>
        <description>https://jira.avalara.com/browse/IBST-7371</description>
        <label>Prior Channel Partner Name Change Date</label>
        <type>Date</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Status_Change_Date_Working__c</fullName>
        <description>Time stamp of date the status on the lead was moved to Working</description>
        <label>Working Date - Original</label>
        <type>DateTime</type>
    </fields>

FullQa New/src/objects/Individual.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FullQa New/src/objects/KeyPairValue__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To store Opportunity Type and Meeting type for EventTriggerHandler</description>
    <fields>
        <fullName>Values__c</fullName>
        <label>Values</label>
        <type>TextArea</type>
    </fields>
    <label>KeyPairValue</label>
</CustomObject>

Prod/src/objects/Response_Velocity__c.object
<CustomObject>
    <description>https://wiki.avalara.com/pages/viewpage.action?pageId=292769310</description>
    <fields>
        <fullName>Assignment_Date_Time__c</fullName>
        <description>https://wiki.avalara.com/pages/viewpage.action?pageId=292769310</description>
        <label>Assignment Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Response Velocities</relationshipLabel>
        <relationshipName>Response_Velocities_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Response Velocities</relationshipLabel>
        <relationshipName>Response_Velocities_Lead</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MQL_Date_Time__c</fullName>
        <description>https://wiki.avalara.com/pages/viewpage.action?pageId=292769310</description>
        <label>MQL Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Conversion_Date__c</fullName>
        <label>Most Recent Conversion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Blog</fullName>
                </value>
                <value>
                    <fullName>Case Study</fullName>
                </value>
                <value>
                    <fullName>CL Event</fullName>
                </value>
                <value>
                    <fullName>Content Syndication Whitepaper</fullName>
                </value>
                <value>
                    <fullName>Corporate Sponsored Event</fullName>
                </value>
                <value>
                    <fullName>Direct to Rep</fullName>
                </value>
                <value>
                    <fullName>Emergency Service Notice</fullName>
                </value>
                <value>
                    <fullName>Free Rates</fullName>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>General Contact</fullName>
                </value>
                <value>
                    <fullName>Newsletter</fullName>
                </value>
                <value>
                    <fullName>OBTM</fullName>
                </value>
                <value>
                    <fullName>Online Buying</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Partner Event</fullName>
                </value>
                <value>
                    <fullName>Partner Training</fullName>
                </value>
                <value>
                    <fullName>Product Offering</fullName>
                </value>
                <value>
                    <fullName>Prospecting</fullName>
                </value>
                <value>
                    <fullName>Referral Program</fullName>
                </value>
                <value>
                    <fullName>Revive</fullName>
                </value>
                <value>
                    <fullName>Roadshow</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>Through-partner syndication</fullName>
                </value>
                <value>
                    <fullName>Tradeshow</fullName>
                </value>
                <value>
                    <fullName>User Group</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
                <value>
                    <fullName>Webinar</fullName>
                </value>
                <value>
                    <fullName>Website Visit</fullName>
                </value>
                <value>
                    <fullName>Web Tools</fullName>
                </value>
                <value>
                    <fullName>Whitepaper</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Processing_Date_Time__c</fullName>
        <description>https://wiki.avalara.com/pages/viewpage.action?pageId=292769310
https://jira.avalara.com/browse/ITBSE-563?filter=-1</description>
        <label>Processing Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Working_Date_Time__c</fullName>
        <description>https://wiki.avalara.com/pages/viewpage.action?pageId=292769310
https://jira.avalara.com/browse/ITBSE-563?filter=-1</description>
        <label>Working Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Response Velocity</label>
    <nameField>
        <displayFormat>RV-{0000}</displayFormat>
        <label>Response Velocity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Velocities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev/src/classes/ContactTriggerHandlerTest.cls
@isTest
private class ContactTriggerHandlerTest {
     @testSetup static void setup() {
       //Setup custom setting
       List<CC_AVA_KeyPairValue__c> listCC_AVA_KeyPairValue=new List<CC_AVA_KeyPairValue__c>(); 
       listCC_AVA_KeyPairValue.add(new CC_AVA_KeyPairValue__c(Name='BizTech_API_URL_Sandbox',Value__c='http://api.salesforce.com/'));
       listCC_AVA_KeyPairValue.add(new CC_AVA_KeyPairValue__c(Name='BizTech_API_APIKEY_Sandbox',Value__c='123456'));
       listCC_AVA_KeyPairValue.add(new CC_AVA_KeyPairValue__c(Name='BizTech_API_URL_Production',Value__c='http://api.salesforce.com/'));
       listCC_AVA_KeyPairValue.add(new CC_AVA_KeyPairValue__c(Name='BizTech_API_APIKEY_Production',Value__c='123456'));
       insert listCC_AVA_KeyPairValue;
       //Setup custom setting
       List<KeyPairValue__c> listKeyPairValue=new List<KeyPairValue__c>(); 
       listKeyPairValue.add(new KeyPairValue__c(Name='Boomi_API_URL_Sandbox',Values__c='http://api.salesforce.com/'));
       listKeyPairValue.add(new KeyPairValue__c(Name='Boomi_API_Key',Values__c='123456'));
       listKeyPairValue.add(new KeyPairValue__c(Name='Boomi_API_URL_Production',Values__c='http://api.salesforce.com/'));
       listKeyPairValue.add(new KeyPairValue__c(Name='ZTBuyAPICaseSafeID',Values__c='00533000003RbvNAAS'));
       listKeyPairValue.add(new KeyPairValue__c(Name='EloquaAvalaraCaseSafeID',Values__c='00540000000yXrwAAE'));
       listKeyPairValue.add(new KeyPairValue__c(Name='LeadResponseVelocityOwnerChange',Values__c='00533000003hat0AAA,00540000001eFBmAAM,00540000002fhW6AAI'));
       listKeyPairValue.add(new KeyPairValue__c(Name='EContractActivityTriggerHandler',Values__c='False'));
       listKeyPairValue.add(new KeyPairValue__c(Name='LogOpportunityProductHistory',Values__c='TRUE'));
       listKeyPairValue.add(new KeyPairValue__c(Name='NonConnectorFees',Values__c='a0n3300000FTiWlAAL'));
       listKeyPairValue.add(new KeyPairValue__c(Name='OpportunitySubType',Values__c='AvaTax@@BizDev@@SOHO'));
       insert listKeyPairValue;
     }
    static testMethod void testLinkPartnerWithContact() {
            //Create partner account
            Id partnerAccountRecordTypeId=[select id From RecordType Where sObjectType='Account' and DeveloperName='Partner_Certification' limit 1].Id;
        Account partnerAccount=TestUtil.createAccount(partnerAccountRecordTypeId,1,false)[0];
        partnerAccount.ActivePartner__c =true;
        partnerAccount.PartnerNumber__c = '1234';
        insert partnerAccount;
        Contact partnerContact=TestUtil.createContact(partnerAccount.Id,1,false)[0];
        partnerContact.Email='partnercontact@example.com';
        insert partnerContact;
            //Create customer account
            Id customerAccountRecordTypeId=[Select Id from RecordType where DeveloperName='Customer_Account_Type' limit 1].Id;
        Account customerAccount =TestUtil.createAccount(customerAccountRecordTypeId,1,true)[0];      
        
        //create a contact and make one as primary
        Test.startTest();
        List<Contact> listContacts=TestUtil.createContact(customerAccount.Id,50,true);
        for(Contact c:[Select Id,Channel_Partner_Name__c,Channel_Partner_Sales_Rep__c,Partner_Rep_Email__c,Partner_Contact_Not_Found_Email_Sent__c From Contact Where Id=:listContacts ]){
                System.assertEquals(c.Channel_Partner_Name__c,null);
                System.assertEquals(c.Channel_Partner_Sales_Rep__c,null);
                System.assertEquals(c.Partner_Rep_Email__c,null);
                System.assertEquals(c.Partner_Contact_Not_Found_Email_Sent__c,0);
        }
        
        for(Contact c:listContacts){
                c.Partner_Rep_Email__c='test@example.com';
        }
        update listContacts;
        for(Contact c:[Select Id,Channel_Partner_Name__c,Channel_Partner_Sales_Rep__c,Partner_Rep_Email__c,Partner_Contact_Not_Found_Email_Sent__c From Contact Where Id=:listContacts ]){
                System.assertEquals(c.Channel_Partner_Name__c,null);
                System.assertEquals(c.Channel_Partner_Sales_Rep__c,null);
                System.assertNotEquals(c.Partner_Rep_Email__c,null);
                System.assertEquals(c.Partner_Contact_Not_Found_Email_Sent__c,1);
        }     

        for(Contact c:listContacts){
                c.Partner_Rep_Email__c=partnerContact.Email;
        }
        update listContacts;
        for(Contact c:[Select Id,Channel_Partner_Name__c,Channel_Partner_Sales_Rep__c,Partner_Rep_Email__c,Partner_Contact_Not_Found_Email_Sent__c From Contact Where Id=:listContacts ]){
                System.assertEquals(c.Channel_Partner_Name__c,partnerAccount.Id);
                System.assertEquals(c.Channel_Partner_Sales_Rep__c,partnerContact.Id);
                System.assertEquals(c.Partner_Rep_Email__c,partnerContact.Email);
                System.assertEquals(c.Partner_Contact_Not_Found_Email_Sent__c,1);
        }   
        Test.stopTest();        
    }
    static testMethod void test50ContactAuthorizedIdentityChanged() {
        Test.startTest();
      //Create an account
           Id customerAccountTypeId=[Select Id from RecordType where DeveloperName='Customer_Account_Type' limit 1].Id;
       Account a =TestUtil.createAccount(customerAccountTypeId,1,true)[0];
       //create a contact 
       List<Contact> listCon =TestUtil.createContact(a.Id,50,true);
           for(Contact con : listCon){
             con.Authorized_Identity_Contact__c = true;
           }
       update listCon;
       Test.setMock(HttpCalloutMock.class, new TestMockHttpResponseGenerator() );
      Test.stopTest();
    }  
    
     static testMethod void test101ContactAuthorizedIdentityChanged() {
        Test.startTest();
      //Create an account
           Id customerAccountTypeId=[Select Id from RecordType where DeveloperName='Customer_Account_Type' limit 1].Id;
       Account a =TestUtil.createAccount(customerAccountTypeId,1,true)[0];
       //try{
       //create a contact 
       List<Contact> listCon =TestUtil.createContact(a.Id,101,true);
           for(Contact con : listCon){
             con.Authorized_Identity_Contact__c = true;
           }
       update listCon;
       /*}
       catch(Exception e){
           Boolean expectedExceptionThrown =  e.getMessage().contains('More than 100 Contacts are updated') ? true : false;
           System.AssertEquals(expectedExceptionThrown, true);
       }*/
       Test.setMock(HttpCalloutMock.class, new TestMockHttpResponseGenerator() );
      Test.stopTest();
    }    
    
    static testMethod void testLeadConversion() {
        Test.startTest();
         LeadTriggerHandler.isLeadConverted = false;
          //Create an account
       Id customerAccountTypeId=[Select Id from RecordType where DeveloperName='Customer_Account_Type' limit 1].Id;
       Account a =TestUtil.createAccount(customerAccountTypeId,1,true)[0];
       //create a contact 
       Contact con =TestUtil.createContact(a.Id,1,true)[0];
       con.ContactStatus__c = 'Working';
       update con;
       Contact c = [Select id, Status_Change_Date_Working__c from Contact where id=:con.id];
       //System.assertEquals(c.Status_Change_Date_Working__c,System.now());
      Test.stopTest();
    }
     static testMethod void testChangeContactOwner() {
      Test.startTest();
       //create user 
       Id ava2CAMProfileId = [Select Id from Profile where Name ='Ava2 CAM' limit 1].id;
       User u = TestUtil.createUSer(ava2CAMProfileId,null,1,true)[0];
       //Create an account
           Id customerAccountTypeId=[Select Id from RecordType where DeveloperName='Customer_Account_Type' limit 1].Id;
       Account a =TestUtil.createAccount(customerAccountTypeId,101,true)[0];
             a.ActiveCustomer__c = true;
       update a;
       //create a contact 
       List<Contact> listCon =TestUtil.createContact(a.Id,50,true);
       for(Contact con :listCon ){
         con.ownerid = u.id;
       
       }
       /*}
       catch(Exception e){
           Boolean expectedExceptionThrown =  e.getMessage().contains('More than 100 Contacts are updated') ? true : false;
           System.AssertEquals(expectedExceptionThrown, true);
       }*/
      Test.stopTest();
    }   
     static testMethod void testChangeAccountOwner() {
      Test.startTest();
       //create user 
       Id ava2CAMProfileId = [Select Id from Profile where Name ='Ava2 CAM' limit 1].id;
       User u = TestUtil.createUSer(ava2CAMProfileId,null,1,true)[0];
       //Create an account
           Id customerAccountTypeId=[Select Id from RecordType where DeveloperName='Customer_Account_Type' limit 1].Id;
       Account a =TestUtil.createAccount(customerAccountTypeId,50,true)[0];
             a.ActiveCustomer__c = true;
             a.OwnerId = u.Id;
       update a;
       //create a contact 
       List<Contact> listCon =TestUtil.createContact(a.Id,50,true);
       /*}
       catch(Exception e){
           Boolean expectedExceptionThrown =  e.getMessage().contains('More than 100 Contacts are updated') ? true : false;
           System.AssertEquals(expectedExceptionThrown, true);
       }*/
      Test.stopTest();
    }     
      //https://jira.avalara.com/browse/IBST-7371
    static testMethod void testPartnerContactUpdate6MonthsBefore() {
            //Create partner account
            Id partnerAccountRecordTypeId=[select id From RecordType Where sObjectType='Account' and DeveloperName='Partner_Certification' limit 1].Id;
        Account partnerAccount=TestUtil.createAccount(partnerAccountRecordTypeId,1,false)[0];
        partnerAccount.ActivePartner__c =true;
        partnerAccount.PartnerNumber__c = '1234';
        insert partnerAccount;
        //Create an account
            Id customerAccountTypeId=[Select Id from RecordType where DeveloperName='Customer_Account_Type' limit 1].Id;
        Account customerAccount =TestUtil.createAccount(customerAccountTypeId,1,false)[0];
        customerAccount.ActivePartner__c =true;
        customerAccount.PartnerNumber__c = '1234';
        insert customerAccount;
        String EloquaAvalaraCaseSafeID='';
        EloquaAvalaraCaseSafeID =KeyPairValue__c.getInstance('EloquaAvalaraCaseSafeID').Values__c;  
        USer u = [Select id from User where id =: EloquaAvalaraCaseSafeID];
        Test.startTest();   
        Contact contact=TestUtil.createContact(null,1,false)[0];
        contact.Prior_Channel_Partner_Name_Change_Date__c = system.today();    
        contact.Channel_Partner_Name__c =  customerAccount.id;
        insert contact;
        
        System.runAs(u){
          contact.Channel_Partner_Name__c =  partnerAccount.id;
          update contact;
        }
        Test.stopTest();   
    }
    
     //https://jira.avalara.com/browse/IBST-7371
    static testMethod void testPartnerContactUpdate6MonthsAfter() {
           Id partnerAccountRecordTypeId=[select id From RecordType Where sObjectType='Account' and DeveloperName='Partner_Certification' limit 1].Id;
        Account partnerAccount=TestUtil.createAccount(partnerAccountRecordTypeId,1,false)[0];
        partnerAccount.ActivePartner__c =true;
        partnerAccount.PartnerNumber__c = '1234';
        insert partnerAccount;
        //Create an account
            Id customerAccountTypeId=[Select Id from RecordType where DeveloperName='Customer_Account_Type' limit 1].Id;
         Account customerAccount =TestUtil.createAccount(customerAccountTypeId,1,false)[0];
        customerAccount.ActivePartner__c =true;
        customerAccount.PartnerNumber__c = '1234';
        insert customerAccount;
        String EloquaAvalaraCaseSafeID='';
        EloquaAvalaraCaseSafeID =KeyPairValue__c.getInstance('EloquaAvalaraCaseSafeID').Values__c;  
        USer u = [Select id from User where id =: EloquaAvalaraCaseSafeID];
        Test.startTest();   
        Contact contact=TestUtil.createContact(null,1,false)[0];
        contact.Prior_Channel_Partner_Name_Change_Date__c = Date.newInstance(2016, 12, 9);    
        contact.Channel_Partner_Name__c =  customerAccount.id;
        insert contact;
        
        System.runAs(u){
          contact.Channel_Partner_Name__c =  partnerAccount.id;
          update contact;
        }
        Test.stopTest();   
    }
    static testMethod void testResponseVelocity(){
        //Create an account
        Id customerAccountTypeId=[Select Id from RecordType where DeveloperName='Customer_Account_Type' limit 1].Id;
        Account a =TestUtil.createAccount(customerAccountTypeId,1,true)[0];
            a.ActiveCustomer__c = true;
        update a;   
            //create contact and setup initial fields
            Contact c=TestUtil.createContact(a.Id,1,false)[0];
            c.ContactStatus__c=Constants.CONTACT_STATUS_MQL;
            c.Most_Recent_Conversion_Date__c=Date.today();
            insert c;
            
            //validate that response velocit was cretead and MQL date time was populated
            List<Response_Velocity__c> rvList=[Select Id,MQL_Date_Time__c,Assignment_Date_Time__c,Processing_Date_Time__c,Working_Date_Time__c From Response_Velocity__c Where Contact__c=:c.Id];
            system.assertEquals(1,rvList.size());    
            system.assertNotEquals(NULL,rvList[0].MQL_Date_Time__c);
            system.assertEquals(NULL,rvList[0].Processing_Date_Time__c);
            system.assertEquals(NULL,rvList[0].Working_Date_Time__c);
            system.assertEquals(NULL,rvList[0].Assignment_Date_Time__c);
            //change status to processing to populate processing date time
            ContactTriggerHandler.afterInsertUpdateExecuted=false;
            c.ContactStatus__c=Constants.CONTACT_STATUS_PROCESSING;
            update c;
            //change status to working to populate working date time
            ContactTriggerHandler.afterInsertUpdateExecuted=false;
            c.ContactStatus__c=Constants.CONTACT_STATUS_WORKING;
            update c;   
            /*//change owner to queue and then change it back to current user to populate assignment date time
            ContactTriggerHandler.afterInsertUpdateExecuted=false;
            c.OwnerId=[Select Id,Queue.Name,Queue.Id From QueueSObject Where sObjectType='Contact' limit 1].Queue.Id;
            update c; 
            ContactTriggerHandler.afterInsertUpdateExecuted=false;
            c.OwnerId=Userinfo.getUserId();
            update c;  */
    
        //validate all fields are populated
        rvList=[Select Id,MQL_Date_Time__c,Processing_Date_Time__c,Assignment_Date_Time__c,Working_Date_Time__c,Lead__c,Contact__c From Response_Velocity__c Where Contact__c=:c.Id];
            system.assertEquals(1,rvList.size());    
            system.assertNotEquals(NULL,rvList[0].MQL_Date_Time__c);
            system.assertNotEquals(NULL,rvList[0].Processing_Date_Time__c);
            system.assertNotEquals(NULL,rvList[0].Working_Date_Time__c);    
            //system.assertNotEquals(NULL,rvList[0].Assignment_Date_Time__c);
            system.assertEquals(NULL,rvList[0].Lead__c);    
            system.assertNotEquals(NULL,rvList[0].Contact__c);                                                      
    }  
    static testMethod void testGDPRProcess(){
            try{
                String email='testGDPR@example.com';
            Individual inv=new Individual(Email__c=email,LastName='lastname',ShouldForget=true);
            insert inv;     
                //Create an account
            Id customerAccountTypeId=[Select Id from RecordType where DeveloperName='Customer_Account_Type' limit 1].Id;
                Account a =TestUtil.createAccount(customerAccountTypeId,1,true)[0];
            a.ActiveCustomer__c = true;
                update a;   
            //create contact and setup initial fields
            Contact c=TestUtil.createContact(a.Id,1,false)[0];
            c.Email=email;
            insert c;
            }
            catch(Exception e){
            Boolean expectedExceptionThrown =  (e.getMessage().contains(Constants.CONTACT_CANNOT_INSERT_UPDATE_CONTACT_FOR_GDPR)) ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);             
            }   
    }    
     static testMethod void testResponseVelocityAvaTax(){
        //Create an account
        Id customerAccountTypeId=[Select Id from RecordType where DeveloperName='Customer_Account_Type' limit 1].Id;
        Account a =TestUtil.createAccount(customerAccountTypeId,1,true)[0];
            a.ActiveCustomer__c = true;
        update a;   
            //create contact and setup initial fields
            Contact c=TestUtil.createContact(a.Id,1,false)[0];
            c.ContactStatus__c=Constants.CONTACT_STATUS_MQL;
            c.Opportunity_Sub_Type__c='AvaTax';
            c.Most_Recent_Conversion_Date__c=Date.today();
            c.mk_lead_avatax_score__c = 45;
            c.mk_customer_fit_avatax_score__c=90;
            c.Offer__c= Contact.Offer__c.getDescribe().getPicklistValues()[0].getLabel();
            c.Method_of_Contact_Contact__c = Contact.Method_of_Contact_Contact__c.getDescribe().getPicklistValues()[0].getLabel();
            insert c;
            
            //validate that response velocit was cretead and MQL date time was populated
            List<Response_Velocity__c> rvList=[Select Id,Opportunity_SubType__c,MK_Lead_Score__c,MK_Customer_Fit_Score__c,Most_Recent_Conversion_Date__c,Offer__c,Method_of_Contact__c From Response_Velocity__c Where Contact__c=:c.Id];
            system.assertEquals(1,rvList.size());    
            system.assertNotEquals(NULL,rvList[0].Opportunity_SubType__c);
            system.assertNotEquals(NULL,rvList[0].MK_Lead_Score__c);
            system.assertNotEquals(NULL,rvList[0].MK_Customer_Fit_Score__c);
            system.assertNotEquals(NULL,rvList[0].Most_Recent_Conversion_Date__c);
            system.assertNotEquals(NULL,rvList[0].Offer__c);
            system.assertNotEquals(NULL,rvList[0].Method_of_Contact__c);                                                      
    }     
     static testMethod void testResponseVelocityCC(){
        //Create an account
        Id customerAccountTypeId=[Select Id from RecordType where DeveloperName='Customer_Account_Type' limit 1].Id;
        Account a =TestUtil.createAccount(customerAccountTypeId,1,true)[0];
            a.ActiveCustomer__c = true;
        update a;   
            //create contact and setup initial fields
            Contact c=TestUtil.createContact(a.Id,1,false)[0];
            c.ContactStatus__c=Constants.CONTACT_STATUS_MQL;
            c.Opportunity_Sub_Type__c='CertCapture';
            c.Most_Recent_Conversion_Date__c=Date.today();
            c.MK_Lead_Score_CC__c = 45;
            c.MK_Customer_Fit_Score_CC__c=90;
            c.Offer__c= Contact.Offer__c.getDescribe().getPicklistValues()[0].getLabel();
            c.Method_of_Contact_Contact__c = Contact.Method_of_Contact_Contact__c.getDescribe().getPicklistValues()[0].getLabel();
            insert c;
            
            //validate that response velocit was cretead and MQL date time was populated
            List<Response_Velocity__c> rvList=[Select Id,Opportunity_SubType__c,MK_Lead_Score__c,MK_Customer_Fit_Score__c,Most_Recent_Conversion_Date__c,Offer__c,Method_of_Contact__c From Response_Velocity__c Where Contact__c=:c.Id];
            system.assertEquals(1,rvList.size());    
            system.assertNotEquals(NULL,rvList[0].Opportunity_SubType__c);
            system.assertNotEquals(NULL,rvList[0].MK_Lead_Score__c);
            system.assertNotEquals(NULL,rvList[0].MK_Customer_Fit_Score__c);
            system.assertNotEquals(NULL,rvList[0].Most_Recent_Conversion_Date__c);
            system.assertNotEquals(NULL,rvList[0].Offer__c);
            system.assertNotEquals(NULL,rvList[0].Method_of_Contact__c);                                                      
    }     
}