FullQa New/src/objects/CC_AVA_KeyPairValue__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is being used for Cloud Craze custom development. For more info please contact Navees</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC_AVA_KeyPairValue</label>
</CustomObject>

Avalara Fullqa/src/classes/CC_AVA_API.cls
public with sharing class CC_AVA_API {
	public String getCartDefaultCampaignValues(){
		String CartDefaultCampaignValues='';
		Map<String,String> mapCartDefaultCampaignValues=new Map<String,String>();
		for(CC_AVA_KeyPairValue__c k: [Select Name,Value__c From CC_AVA_KeyPairValue__c Where Type__c='CartDefaultCampaignValues']){
			mapCartDefaultCampaignValues.put(k.Name,String.isBlank(k.Value__c)?'':k.Value__c);
		}
		CartDefaultCampaignValues=JSON.serialize(mapCartDefaultCampaignValues);
		return CartDefaultCampaignValues;
	}
    
}