FullQa New/src/objects/Connector__c.object
<CustomObject>
    <description>Used to track all Avalara connectors and associated data</description>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Track the original developer of the code associated with this connector
Integrated: Yes 
Change: Level 1 
Custodian: Business Development / Greg Chapman</description>
        <inlineHelpText>Associate the account of the original developer of the code associated with this connector</inlineHelpText>
        <label>Author</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connectors (Author)</relationshipLabel>
        <relationshipName>Connectors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Connector_Description__c</fullName>
        <inlineHelpText>Enter a summary of the partner connector relationship, capabilities and any other pertinent information specific to this connector.</inlineHelpText>
        <label>Connector Description</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Connector_EcoSystem_Test__c</fullName>
        <label>Connector EcoSystem Summary</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Managed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Track 30 day delta between old calc estimation and new calc estimation 
Integrated: No 
Change: Level 0 
Custodian: Business Development / Greg Chapman</description>
        <inlineHelpText>Associate the account currently managing / responsible for the code associated with this connector</inlineHelpText>
        <label>Managed By</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connectors (Managed By)</relationshipLabel>
        <relationshipName>Managed_Connectors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Connector</label>
    <nameField>
        <label>Connector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FullQa New/src/objects/Functional_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Configuration_Click_Path__c</fullName>
        <inlineHelpText>Describe the path of clicks that the user must take to find the AvaTax configuration. Also note if it&apos;s gated by permissions.</inlineHelpText>
        <label>Configuration Click Path</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <label>Sales Tax</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Badges_Achieved</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <referenceTo>Version__c</referenceTo>
        <relationshipLabel>Functional Matrix</relationshipLabel>
        <relationshipName>Functional_Matrix</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Functional Matrix</label>
    <nameField>
        <displayFormat>FM-{000000}</displayFormat>
        <label>Functional Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FullQa New/src/objects/Functional_Matrix_Requirements_Config__c.object
<CustomObject>
    <fields>
        <fullName>Core_Type__c</fullName>
        <label>Core Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Core Sales Tax</fullName>
                </value>
                <value>
                    <fullName>Core Address Validation</fullName>
                </value>
                <value>
                    <fullName>Core Communication</fullName>
                </value>
                <value>
                    <fullName>Core Use Tax</fullName>
                </value>
                <value>
                    <fullName>Core Document Management</fullName>
                </value>
                <value>
                    <fullName>Core Lodging</fullName>
                </value>
                <value>
                    <fullName>Core Excise</fullName>
                </value>
                <value>
                    <fullName>Core Extractor TrustFile</fullName>
                </value>
                <value>
                    <fullName>Core Extractor AvaTax</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Functional Matrix Requirements Config</label>
    <nameField>
        <label>Functional Matrix Requirements Config Na</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functional Matrix Requirements Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FullQa New/src/objects/Version__c.object
<CustomObject>
    <description>Used as an associated related list for the connector object to track the version associated with a given connector</description>
    <fields>
        <fullName>Connector__c</fullName>
        <label>Connector</label>
        <referenceTo>Connector__c</referenceTo>
        <relationshipLabel>Versions</relationshipLabel>
        <relationshipName>Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Version_KB__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Version KB</label>
        <referenceTo>Solution</referenceTo>
        <relationshipLabel>Versions</relationshipLabel>
        <relationshipName>Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Version</label>
    <nameField>
        <label>Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FullQa New/src/classes/FunctionalMatrixRequirementHandlerTest.cls
@isTest
private class FunctionalMatrixRequirementHandlerTest {
	static testMethod void testProcess(){
		Solution sol = new Solution(
            SolutionName = 'Test Solution'
        );
        insert sol;
        Account acc = new Account(
            Name = 'Test Account'
        );
        insert acc;

        Connector__c c = new Connector__c(
            Name = 'Test Connector',
            Author__c = acc.Id,
            Managed_By__c = acc.Id,
            Connector_Description__c = 'test',
            Connector_EcoSystem_Test__c = 'test'
        );
        insert c;

        Version__c ver = new Version__c(
            Name = 'Text version 11211222',
            Connector__c = c.Id,
            Version_KB__c = sol.Id
        );
        insert ver;

		Functional_Matrix_Requirements_Config__c cf = new Functional_Matrix_Requirements_Config__c(
			Core_Type__c = 'Core Sales Tax'
		);
		insert cf;


		Functional_Matrix__c fm = new Functional_Matrix__c(
			Version__c = ver.Id,
			RecordTypeId = Schema.SObjectType.Functional_Matrix__c.getRecordTypeInfosByName().get('Core Sales Tax').getRecordTypeId(),
			Sales_Tax__c = 'Certified'
		);

		insert fm;
		fm.Configuration_Click_Path__c = 'test';
		update fm;
        
        FunctionalMatrixHandler.syncToConnectorKB(new List<Functional_Matrix__c>{fm});

	}
}