FullQa New/src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ProductID__c</fullName>
        <description>System and Account Id</description>
        <externalId>true</externalId>
        <inlineHelpText>P=prod D=dev
TFxx-yyyyy=TrustFileYear-ID</inlineHelpText>
        <label>AvaTaxAccount</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/GoLive__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <description>The Asset a GoLive record is associated with.</description>
        <inlineHelpText>The Asset a GoLive record is associated with.</inlineHelpText>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipName>GoLives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ava_GoLive_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Avaralara GoLive Coordinator.  Typically the Customer Support Representative (CSR)</description>
        <label>Ava GoLive Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GoLives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ava_Original_Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GoLives5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Link_to_Dev_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dev Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>GoLivesDEV</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Link_to_Production_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prod Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>GoLivesPROD</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GoLives</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>(Deprecated) GoLive</label>
    <nameField>
        <label>GoLive ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>(Deprecated) GoLives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Avalara Fullqa/src/classes/testGoLiveCreationAddContracts.cls
@isTest
public class testGoLiveCreationAddContracts {
    
    static testMethod void validateGOLiveCreationAddContractsTrigger() {

      Account a = new Account();
      a.Name='Test Account for GoLiveCreationAddContracts trigger';
      a.Industry = 'Automotive';
      a.Type__c='Customer';
      insert a;
        
      Contact contact1 = new Contact();
      contact1.FirstName = 'First';
      contact1.LastName = 'Last';
      contact1.AccountId = a.Id;
      insert contact1; 
        
        
      Asset asst = new Asset();
      asst.Name = 'Test';
      asst.AccountId = a.Id;
      insert asst;
       
      System.Debug('AssetId:');
      System.Debug(asst.Id);
       
      Contract prodCon = new Contract();
      prodCon.AccountId=a.Id;
      prodCon.ProductId__c = 'P12345';
      insert prodCon;
        
      Contract devCon = new Contract();
      devCon.AccountId = a.Id;
      devCon.ProductId__c = 'D12345';
      insert devCon;
        
      GoLive__C golive = new GoLive__C();
      golive.RecordTypeId = [select Id, name from RecordType where name='AvaTax GoLive' and SObjectType='GoLive__c' limit 1].Id;
      golive.Asset__c = asst.Id;
      golive.Related_to_Account__c = a.id;
       
      golive.Ava_GoLive_Coordinator__c = [select Id from User limit 1].Id;
      golive.Ava_Original_Sales_Rep__c = [select Id from User limit 1].Id;
      insert golive;
      
      GoLive__c testGoLive = [select Id, Link_to_Production_Account__c, Link_to_Dev_Contract__c from GoLive__c where Id= :golive.Id];
    
      System.assert(testGoLive.Link_to_Production_Account__c == prodCon.Id);
      System.assert(testGoLive.Link_to_Dev_Contract__c == devCon.Id);
        
    }
    
}