FullQa New/src/objects/Finance_Operations_Close_Event__c.object
<CustomObject>
    <fields>
        <fullName>EDW_Booking_Freeze_Date__c</fullName>
        <inlineHelpText>This will be populated when EDW is frozen.</inlineHelpText>
        <label>EDW Booking Freeze Date</label>
        <type>DateTime</type>
    </fields>
    <label>Finance Operations Close Event</label>
    <nameField>
        <displayFormat>FPA{0000}</displayFormat>
        <label>Finance Operations Close Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Operations Close Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FullQa New/src/classes/FinanceOperationCloseEventTriggerHandler.cls
public with sharing class FinanceOperationCloseEventTriggerHandler  extends TriggerHandler{
    protected override void afterUpdate(){
    		if(Trigger.new!=null && Trigger.new.size()>0){
    			Set<Id> setIDs=new Set<Id>();
    			for(Finance_Operations_Close_Event__c foce:(List<Finance_Operations_Close_Event__c>)Trigger.new){
    				if(foce.EDW_Booking_Freeze_Date__c!=null){
    					setIDs.add(foce.Id);
    				}
    			}
		    if(setIDs!=null && setIDs.size()>0 && !System.isBatch() && !System.isFuture() && !System.isQueueable() && !System.isScheduled()){
		         JobOpportunityFreeze job = new JobOpportunityFreeze(setIDs);
		         ID batchprocessid = Database.executeBatch(job,20); 		    	
		    }     			
    		}
   		
    }

}