FullQa New/src/objects/GoLive__c.object
<CustomObject>
    <fields>
        <fullName>Related_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GoLives</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>(Deprecated) GoLive</label>
    <nameField>
        <label>GoLive ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>(Deprecated) GoLives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FullQa New/src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <description>Used for LinkedIn Navigator</description>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FullQa New/src/classes/GoLiveFindAllTasks.cls
public class GoLiveFindAllTasks{
    private final List<Task> tasks;
        static string currId = ApexPages.currentPage().getParameters().get('ParentAcctId');

    
    public GoLiveFindAllTasks() {
        tasks = [Select Subject, ActivityDate, Status, owner.name, GoLive_Product__c from Task WHERE Type = 'GoLive' and WhatId IN(SELECT ID FROM GoLive__c WHERE Related_to_Account__c = :currId) ORDER BY ActivityDate];
    }

    public List<Task> getAllGoLiveTasks() {
        return tasks;
    }
}