FullQa New/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>CPQ_Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ItemType__c</fullName>
        <label>Item Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ListPrice__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductName__c</fullName>
        <formula>LEFT( PricebookEntry.Product2.Name , 40)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

Avalara Fullqa/src/classes/PSMSTASOrderEmail.cls
public class PSMSTASOrderEmail {
    public String opportunityId{get;set;}
    public String quoteId{get;set;}
    public String getInstanceName(){
        return [select id,instancename from Organization].instancename;
    }
    public List<OpportunityLineItem> getOppLineItems(){
        return [Select Id,ProductName__c,Description,ItemType__c,CPQ_Quantity__c,ListPrice__c,TotalPrice__c from OpportunityLineItem Where OpportunityId=:opportunityId];
    }
}