FullQa New/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>AmendmentType__c</fullName>
        <label>Zuora Amendment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AddProduct</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>RemoveProduct</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ItemType__c</fullName>
        <label>Item Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

FullQa New/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ItemType__c</fullName>
        <label>ItemType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 User License</fullName>
                </value>
                <value>
                    <fullName>5 User License</fullName>
                </value>
                <value>
                    <fullName>Activation</fullName>
                </value>
                <value>
                    <fullName>Additional Certificates</fullName>
                </value>
                <value>
                    <fullName>Additional Lanes</fullName>
                </value>
                <value>
                    <fullName>Additional Transactions</fullName>
                </value>
                <value>
                    <fullName>Add-On Connector</fullName>
                </value>
                <value>
                    <fullName>Backfile Returns</fullName>
                </value>
                <value>
                    <fullName>Development Account</fullName>
                </value>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>Interface</fullName>
                </value>
                <value>
                    <fullName>Nexus Studies</fullName>
                </value>
                <value>
                    <fullName>Postage</fullName>
                </value>
                <value>
                    <fullName>Prof. Svcs</fullName>
                </value>
                <value>
                    <fullName>QuickStart</fullName>
                </value>
                <value>
                    <fullName>Rates</fullName>
                </value>
                <value>
                    <fullName>Returns</fullName>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Update License</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FullQA/src/classes/ZQUQuoteTriggerHandlerTest.cls
@isTest
private class ZQUQuoteTriggerHandlerTest {

    static testMethod void myUnitTest() {
	  //Create an account
    	   Id emeaAccountTypeId=[Select Id from RecordType where DeveloperName='EMEA_Account' limit 1].Id;
       Account a =TestUtil.createAccount(emeaAccountTypeId,1,true)[0];
       //create a contact 
       Contact c =TestUtil.createContact(a.Id,5,true)[0];
       //create Opportunity
       Id defaultOppRecTypeId=[Select Id from RecordType where DeveloperName='Default_OppRecType' limit 1].Id;
       Opportunity o = TestUtil.createOpportunity(a.id,defaultOppRecTypeId,1,true)[0];
       //create prodcut
       Product2 prod = TestUtil.createProdcut(1,true)[0];
        //create prodcut line item 
       PriceBookEntry priceEntry = TestUtil.createPricebookEntry(prod.id,1,true)[0];
       //create Opportunity Line Item 
       OpportunityLineItem oli = TestUtil.createOpportunityLineItem(o.id,priceEntry.id,1,false)[0];
       oli.ItemType__c='One-Time';
       oli.AmendmentType__c='AddProduct';
       insert oli;
       for(Opportunity opp:[Select Id,Amount,(Select Id From OpportunityLineItems) From Opportunity Where Id=:o.Id]){
       		System.assertEquals(1,opp.OpportunityLineItems.size());
       }       
       zqu__Quote__c quote = TestFactory.makeQuote( o );
       quote.O_P_Status__c='Completed';
       update quote;
       for(Opportunity opp:[Select Id,Amount,(Select Id From OpportunityLineItems) From Opportunity Where Id=:o.Id]){
       		System.assertEquals(0,opp.OpportunityLineItems.size());
       }
    }
}