FullQa New/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>AmendmentType__c</fullName>
        <label>Zuora Amendment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AddProduct</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>RemoveProduct</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estimated_Booked_Value__c</fullName>
        <description>BATS-539</description>
        <label>Estimated Booked Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ItemType__c</fullName>
        <label>Item Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Non_Estimated_Booked_Value__c</fullName>
        <description>BATS-539</description>
        <label>Non Estimated Booked Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

FullQa New/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ItemType__c</fullName>
        <label>ItemType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 User License</fullName>
                </value>
                <value>
                    <fullName>5 User License</fullName>
                </value>
                <value>
                    <fullName>Activation</fullName>
                </value>
                <value>
                    <fullName>Additional Certificates</fullName>
                </value>
                <value>
                    <fullName>Additional Lanes</fullName>
                </value>
                <value>
                    <fullName>Additional Transactions</fullName>
                </value>
                <value>
                    <fullName>Add-On Connector</fullName>
                </value>
                <value>
                    <fullName>Backfile Returns</fullName>
                </value>
                <value>
                    <fullName>Development Account</fullName>
                </value>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>Interface</fullName>
                </value>
                <value>
                    <fullName>Nexus Studies</fullName>
                </value>
                <value>
                    <fullName>Postage</fullName>
                </value>
                <value>
                    <fullName>Prof. Svcs</fullName>
                </value>
                <value>
                    <fullName>QuickStart</fullName>
                </value>
                <value>
                    <fullName>Rates</fullName>
                </value>
                <value>
                    <fullName>Returns</fullName>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Update License</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/classes/APIBookingsTest.cls
@isTest
private class APIBookingsTest {

    static testMethod void testCalculateBookings() {
    		Test.startTest();
	  	//Create an account
    	  	 Id emeaAccountTypeId=[Select Id from RecordType where DeveloperName='EMEA_Account' limit 1].Id;
      	 Account a =TestUtil.createAccount(emeaAccountTypeId,1,true)[0];
       	//create a contact 
      	 Contact c =TestUtil.createContact(a.Id,5,true)[0];
      	 //create Opportunity
      	 Id defaultOppRecTypeId=[Select Id from RecordType where DeveloperName='Default_OppRecType' limit 1].Id;
       	//create prodcut
       	Product2 	prod = TestUtil.createProdcut(1,true)[0];      	 
      	 PricebookEntry priceEntry = TestUtil.createPricebookEntry(prod.id,1,true)[0];
      	 Opportunity o = TestUtil.createOpportunity(a.id,defaultOppRecTypeId,1,true)[0];
		   OpportunityLineItem oli = TestUtil.createOpportunityLineItem(o.id,priceEntry.id,1,false)[0];
		   oli.ItemType__c='Recurring';
		   oli.AmendmentType__c='AddProduct';
		   oli.UnitPrice=111;
		   insert oli;      	 
      	 //create pros quote
      	 CameleonCPQ__Quote__c cpq = TestUtil.createProsQuote(a.id,o.id,c.id,1,false)[0];
      	// cpq.OPStatus__c = Constants.PROS_QUOTE_STATUS_COMPLETE;
      	 insert cpq;
      	// cpq.SentToZBillingDate__c=Date.today();
      	 //update cpq;
      	 TriggerHandler.clearAllBypasses();
        update oli;
        Test.stopTest();
        oli=[Select Id,Non_Estimated_Booked_Value__c,Estimated_Booked_Value__c From OpportunityLineItem Where Id=:oli.Id];
        //System.assertEquals(22,oli.Estimated_Booked_Value__c);
        //System.assertEquals(11,oli.Non_Estimated_Booked_Value__c);
    }
	
}