FullQa New/src/Conga Composer/objects/Contact.object
<CustomObject>
</CustomObject>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>mk_customer_fit_avatax_score__c</fullName>
        <label>MK Customer Fit Score AvaTax</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>MK_Customer_Fit_Score_CC__c</fullName>
        <description>https://jira.avalara.com/browse/BATS-352</description>
        <label>MK Customer Fit Score CC</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>MK_Customer_Fit_Score_Comms__c</fullName>
        <description>https://jira.avalara.com/browse/IBST-15732</description>
        <label>MK Customer Fit Score Comms</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>mk_lead_avatax_score__c</fullName>
        <label>MK Lead Score AvaTax</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>MK_Lead_Score_CC__c</fullName>
        <description>https://jira.avalara.com/browse/BATS-352</description>
        <label>MK Lead Score CC</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>MK_Lead_Score_Comms__c</fullName>
        <description>https://jira.avalara.com/browse/IBST-15732</description>
        <label>MK Lead Score Comms</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

Prod/src/classes/OpportunityHelper.cls
public class OpportunityHelper {
      public static void updateMKscoreOpp(Opportunity opp,Contact con){
       if(con.mk_customer_fit_avatax_score__c != null && 
		   	 	      (opp.MK_Customer_Fit_Score_AvaTax__C ==null || 
		   	 	      (opp.MK_Customer_Fit_Score_AvaTax__C !=null && opp.MK_Customer_Fit_Score_AvaTax__C != con.mk_customer_fit_avatax_score__c))){
	                      //System.debug('opp.MK_Customer_Fit_Score_AvaTax__>>>C'+con.get(ocr.contactId).mk_customer_fit_avatax_score__c );
	                      System.debug('opp.MK_Customer_Fit_Score_AvaTax__>>>C'+ opp.MK_Customer_Fit_Score_AvaTax__C );
	                      opp.MK_Customer_Fit_Score_AvaTax__C =  con.mk_customer_fit_avatax_score__c;
	                      System.debug('opp.MK_Customer_Fit_Score_AvaTax__>>>C'+con.mk_customer_fit_avatax_score__c );
                    }
                    
                   if(con.MK_Customer_Fit_Score_CC__c !=null && 
                     (opp.MK_Customer_Fit_Score_CC__c ==null || 
                     (opp.MK_Customer_Fit_Score_CC__c !=null && opp.MK_Customer_Fit_Score_CC__c != con.MK_Customer_Fit_Score_CC__c))){
                      opp.MK_Customer_Fit_Score_CC__c =  con.MK_Customer_Fit_Score_CC__c;
                     }
                    if(con.MK_Customer_Fit_Score_Comms__c != null &&
                      (opp.MK_Customer_Fit_Score_Comms__c == null
                      || (opp.MK_Customer_Fit_Score_Comms__c !=null && opp.MK_Customer_Fit_Score_Comms__c != con.MK_Customer_Fit_Score_Comms__c))){
                       opp.MK_Customer_Fit_Score_Comms__c =  con.MK_Customer_Fit_Score_Comms__c;
                    }
                    if(con.mk_lead_avatax_score__c != null &&
                       (opp.MK_Lead_Score_AvaTax__c ==null || 
                       (opp.MK_Lead_Score_AvaTax__c !=null && opp.MK_Lead_Score_AvaTax__c != con.mk_lead_avatax_score__c))){
                       opp.MK_Lead_Score_AvaTax__c =  con.mk_lead_avatax_score__c;
                    }
                    if(con.MK_Lead_Score_CC__c != null &&
                      (opp.MK_Lead_Score_CC__c ==null || 
                      (opp.MK_Lead_Score_CC__c != null && opp.MK_Lead_Score_CC__c != con.MK_Lead_Score_CC__c))){
                      opp.MK_Lead_Score_CC__c =  con.MK_Lead_Score_CC__c;
                    }
                    if(con.MK_Lead_Score_Comms__c != null && 
                     (opp.MK_Lead_Score_Comms__c ==null || 
                     (opp.MK_Lead_Score_Comms__c!= null && opp.MK_Lead_Score_Comms__c != con.MK_Lead_Score_Comms__c))){
                      opp.MK_Lead_Score_Comms__c =  con.MK_Lead_Score_Comms__c;
                    }  
      }
}