FullQa New/src/LeanData/objects/Campaign.object
<CustomObject>
</CustomObject>

FullQa New/src/objects/Campaign.object
    <fields>
        <fullName>CDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CDM associated with a Campaign</description>
        <inlineHelpText>The CDM associated with a Campaign</inlineHelpText>
        <label>SAM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CDM_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>

FullQa New/src/objects/Campaign.object
    <fields>
        <fullName>Connector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>New Tradeshow Campaign Fields
integrated: No
Marketing: Yvonne</description>
        <label>Connector</label>
        <referenceTo>Connector__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>

FullQa New/src/objects/Campaign.object
    <fields>
        <fullName>Counter__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Counter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Campaign.object
    <fields>
        <fullName>DingCount__c</fullName>
        <label>Ding Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Campaign.object
    <fields>
        <fullName>PPM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PMM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PPM_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>

FullQa New/src/objects/Campaign.object
    <fields>
        <fullName>TotalBookedValue__c</fullName>
        <label>Total Booked Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

Prod/src/objects/Connector__c.object
<CustomObject>
    <description>Used to track all Avalara connectors and associated data</description>
    <fields>
        <fullName>Count__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Count #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Closed_Won_Opps__c</fullName>
        <description>Using rollup helper to calculate number of opps that this connector has won.</description>
        <label>No. Closed Won Opps</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PPM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Track PMM associated with this connector
Integrated: No 
Change: Level 0 
Custodian: Partner Management</description>
        <inlineHelpText>Enter the PMM associated with this connector</inlineHelpText>
        <label>PMM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Connectors1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Track SAM associated with this connector
Integrated: No 
Change: Level 0 
Custodian: Partner Management</description>
        <inlineHelpText>Enter the SAM associated with this connector</inlineHelpText>
        <label>SAM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Connectors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Suppress_Partner_Split__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Integrated Level 1 : Process Builder</description>
        <inlineHelpText>Suppresses the SAM/PPM split on the opportunity for a given connector</inlineHelpText>
        <label>Suppress Partner Split</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X2017_YTD_Opp_Actual__c</fullName>
        <label>2017 YTD Opp Actual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Connector</label>
    <nameField>
        <label>Connector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Avalara Fullqa/src/Conversica/objects/Contact.object
<CustomObject>
</CustomObject>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Channel_Partner_Category__c</fullName>
        <description>Used to pull the Associated Channel Partners category onto a prospective contact  - used for routing via chilipiper</description>
        <formula>Text( Channel_Partner_Name__r.Partner_Category__c )</formula>
        <inlineHelpText>Used to pull the Associated Channel Partners category onto a prospective contact  - used for routing.</inlineHelpText>
        <label>Channel Partner Category</label>
        <type>Text</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Count__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>No_of_Won_Partner_Sales_Ops__c</fullName>
        <description>Count of won opportunities this year when the contact is listed as the channel partner sales rep on an Opportunity
Integrated: yes used to color code the Accounts Org chart
Partner Mgmt: Asher Matthews</description>
        <label>No. of Won Partner Sales Ops</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>SubType__c</fullName>
        <description>Update: IBST-9676</description>
        <formula>CASE(Account.RecordTypeId, &quot;01233000000Ue6l&quot;, &quot;Trustfile Bharat&quot;, &quot;012330000005hcF&quot;, &quot;Brazil&quot;, &quot;01233000000Udyw&quot;, &quot;Communications&quot;, &quot;01240000000Ubqg&quot;, &quot;Excise&quot;, &quot;01240000000Ubql&quot;, &quot;Excise&quot;, &quot;01233000000Ue4G&quot;, &quot;MyLodge&quot;, &quot;01233000000MIr9&quot;, &quot;CertCapture&quot;, &quot;012330000005hjV&quot;, &quot;Avalara Trustfile&quot;, &quot;01233000000MImx&quot;, &quot;EMEA&quot;, &quot;01233000000MIyU&quot;, &quot;SOHO&quot;, &quot;0120b0000005ip7&quot;, &quot;Included&quot;, &quot;AvaTax&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SubType</label>
        <type>Text</type>
    </fields>

Prod/src/objects/Note__c.object
<CustomObject>
    <label>Note</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod/src/objects/Opportunity_PPM_Split__c.object
<CustomObject>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opportunity_PPM_Splits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PMM_Type__c</fullName>
        <description>Used to track whether SAM is DSP or MSP
Owner: Asher Mathew</description>
        <label>PMM Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DSP</fullName>
                </value>
                <value>
                    <fullName>MSP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Percent__c</fullName>
        <label>Percent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity_PPM_Splits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity PMM Split</label>
    <nameField>
        <displayFormat>oppm{0000}</displayFormat>
        <label>Opportunity PMM Split Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity PMM Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod/src/objects/Opportunity_SAM_Split2__c.object
<CustomObject>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity SAM Splits</relationshipLabel>
        <relationshipName>Opportunity_SAM_Splits1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Percent__c</fullName>
        <label>Percent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SAM_Type__c</fullName>
        <label>SAM Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DSP</fullName>
                </value>
                <value>
                    <fullName>MSP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity_SAM_Splits1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity SAM Split</label>
    <nameField>
        <displayFormat>odspsamsplit{0000}</displayFormat>
        <label>Opportunity SAM Split Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity SAM Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FullQa New/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>BookedValue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Booked Value Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CX911_Opportunity_Line_Item_Booked_Date__c</fullName>
        <label>CX911 Opportunity Line Item Booked Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

Avalara Fullqa/src/CloudCraze/objects/User.object
<CustomObject>
</CustomObject>

FullQa New/src/objects/User.object
    <fields>
        <fullName>Count__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/User.object
    <fields>
        <fullName>Current_FY_Dings__c</fullName>
        <label>Current FY Dings</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

Avalara Fullqa/src/classes/OpportunityTriggerHandler.cls
public class OpportunityTriggerHandler extends TriggerHandler {
	///Opportunity > BookedValue__c  sum into Campaign.TotalBookedValue__c
	//SELECT BookedValue__c , CampaignId FROM Opportunity WHERE isDeleted = false AND ding_date__c != null AND type = 'New' AND campaignid != '70140000000Tm0gAAC' AND campaignid != '70140000001LPHRAA4' AND campaignid != '70140000000F4uqAAC' AND campaignid != '70140000000Tm0WAAS' AND campaignid != '701400000004ti7AAA' ORDER BY Id DESC NULLS LAST
	
	///Opportunity > Ding_Value__c  count into Campaign.DingCount__c
	//SELECT Ding_Value__c , CampaignId FROM Opportunity WHERE isDeleted = false AND ding_date__c != null AND type = 'New' AND campaignid != '70140000000Tm0gAAC' AND campaignid != '70140000001LPHRAA4' AND campaignid != '70140000000F4uqAAC' AND campaignid != '70140000000Tm0WAAS' AND campaignid != '701400000004ti7AAA' ORDER BY Id DESC NULLS LAST
	
	///Opportunity > IsWon count into Connector__c.No_Closed_Won_Opps__c
	//SELECT IsWon , Connector__c FROM Opportunity WHERE isDeleted = false AND stagename = 'Closed Won' ORDER BY Id DESC NULLS LAST
	
	//Opportunity > Counter__c  sum into Connector__c.X2017_YTD_Opp_Actual__c
	//SELECT Counter__c , Connector__c FROM Opportunity WHERE isDeleted = false AND closedate = THIS_YEAR AND type = 'New' ORDER BY Id DESC NULLS LAST
	
	//Opportunity > Count__c  sum into User.Current_FY_Dings__c
	//SELECT Count__c , OwnerId FROM Opportunity WHERE isDeleted = false AND ding_date__c = THIS_YEAR ORDER BY Id DESC NULLS LAST
	
	//Opportunity > BookedValue__c  sum into Account.Total_Revenue__c
	//SELECT BookedValue__c , PartnerName__c FROM Opportunity WHERE isDeleted = false AND ding_value__c > 0 AND booked_date__c = THIS_YEAR ORDER BY Id DESC NULLS LAST
	
	//Opportunity > Counter__c  sum into Account.Total_Deals__c
	//SELECT Counter__c , PartnerName__c FROM Opportunity WHERE isDeleted = false AND ding_value__c > 0 AND booked_date__c = THIS_YEAR ORDER BY Id DESC NULLS LAST
	
	//Opportunity > Counter__c  sum into Account.Total_Opps__c
	//SELECT Counter__c , PartnerName__c FROM Opportunity WHERE isDeleted = false AND createddate = THIS_YEAR ORDER BY Id DESC NULLS LAST
	
	//Opportunity > Count__c  count into Contact.No_of_Won_Partner_Sales_Ops__c
	//SELECT Count__c , PartnerSalesRep__c FROM Opportunity WHERE iswon = TRUE AND closedate = THIS_YEAR ORDER BY Id DESC NULLS LAST
	
	 //Trigger Handler Methods
     protected override void beforeInsert(){
     beforeInsertUpdate();
     }

  	protected override void beforeUpdate(){
  	 beforeInsertUpdate();
  	 }

    //protected override void beforeDelete(){}
    public void beforeInsertUpdate(){
    	 Set<ID> connectorIdSet = new Set<Id>();
     Set<ID> channelPartnerNameSet = new Set<Id>();
     Map<Id,Connector__c> mapConnector=new Map<Id,Connector__c>();
     Map<Id,Account> mapChannelPartner=new Map<Id,Account>();
     List<Opportunity_SAM_Split2__c> oppSAMSplitList = new  List<Opportunity_SAM_Split2__c>();
     List<Opportunity_PPM_Split__c> oppPPMSplitList = new  List<Opportunity_PPM_Split__c>();
     for(Opportunity opp: (List<Opportunity>) Trigger.new){
      	//Connector Deal DSP
      	if(String.isNotBlank(opp.Type) && String.isNotBlank(opp.SubType__c) && !opp.SubType__c.equalsIgnoreCase('SOHO') && opp.Type.equalsIgnoreCase('New') && opp.Connector__c!= null 
         && opp.Booked_Date__c != null && !opp.SubType__c.equalsIgnoreCase('EMEA')  )
      	{
      		connectorIdSet.add(opp.Connector__c);
      	}
        //Has Channel Partner MSP
        if(!String.isBlank(opp.PartnerNumber__c) && !opp.PartnerNumber__c.equals('000-000-000')&& String.isNotBlank(opp.PartnerName__c) 
        && String.isNotBlank(opp.Channel_Partner_Category__c) && opp.Booked_Date__c != null && opp.Channel_Partner_Category__c.equalsIgnoreCase('Marketing & Sales Partner')){
            channelPartnerNameSet.add(opp.PartnerName__c);    
        }
     }
    //channel Parnter MSP
    if(channelPartnerNameSet.size()>0){
    		mapChannelPartner=new Map<Id,Account>([Select id,CDM__c,Secondary_CDM__c from Account where id in:channelPartnerNameSet]);
    }
   //Connector Deal DSP
   if(connectorIdSet.size()>0){
   		mapConnector=new Map<Id,Connector__c>([Select id,SAM__c,Suppress_Partner_Split__c,PPM__c from Connector__c where id =:connectorIdSet AND Suppress_Partner_Split__c = false]);
    }
   for(Opportunity opp: (List<Opportunity>) Trigger.new){
   	//Stamp DSP SAM/PPM
    if(mapConnector.size()>0 && mapConnector.containsKey(opp.Connector__c)){
      if(!opp.Initial_DSP_SAM_Split_Complete__c && mapConnector.get(opp.Connector__c).SAM__c!=null&& !opp.Initial_DSP_SAM_Split_Complete__c){
         opp.DSP_SAM__c =  mapConnector.get(opp.Connector__c).SAM__c;
         opp.Initial_DSP_SAM_Split_Complete__c = true;
         if(opp.id != null){
         Opportunity_SAM_Split2__c oppDSPSAMSplit = new Opportunity_SAM_Split2__c(Opportunity__c = opp.id,Percent__c=100,SAM_Type__c = 'DSP',Team_Member__c =  opp.DSP_SAM__c,Note__c='--');
	     oppSAMSplitList.add(oppDSPSAMSplit); 
         }
        }      
        if(!opp.Initial_DSP_PPM_Split_Complete__c && mapConnector.get(opp.Connector__c).PPM__c!=null && !opp.Initial_DSP_PPM_Split_Complete__c ){
         opp.DSP_PPM__c = mapConnector.get(opp.Connector__c).PPM__c;
         opp.Initial_DSP_PPM_Split_Complete__c = true;
         if(opp.id != null){
         Opportunity_PPM_Split__c oppDSPPPMSplit = new Opportunity_PPM_Split__c(Opportunity__c = opp.id,Percent__c=100,PMM_Type__c = 'DSP',Team_Member__c =opp.DSP_PPM__c);
	     oppPPMSplitList.add(oppDSPPPMSplit);
         }
        }
      }	  	  
  	  //Stamp MSP SAM/PPM
      if(mapChannelPartner.containsKey(opp.PartnerName__c)){
       if(mapChannelPartner.get(opp.PartnerName__c).Secondary_CDM__c!=null && !opp.Initial_MSP_PPM_Split_Complete__c){
         opp.MSP_PPM__c = mapChannelPartner.get(opp.PartnerName__c).Secondary_CDM__c;
         opp.Initial_MSP_PPM_Split_Complete__c = true;
           if(opp.id != null){
          Opportunity_PPM_Split__c oppMSPPMSplit = new Opportunity_PPM_Split__c(Opportunity__c = opp.id,Percent__c=100,PMM_Type__c = 'MSP',Team_Member__c = opp.MSP_PPM__c);
          oppPPMSplitList.add(oppMSPPMSplit);
           }
       }
       if(mapChannelPartner.get(opp.PartnerName__c).CDM__c!=null && !opp.Initial_MSP_SAM_Split_Complete__c){
         opp.SAM__c =  mapChannelPartner.get(opp.PartnerName__c).CDM__c;
         opp.Initial_MSP_SAM_Split_Complete__c = true;
        if(opp.id != null){
         Opportunity_SAM_Split2__c oppDSPSAMSplit = new Opportunity_SAM_Split2__c(Opportunity__c = opp.id,Percent__c=100,SAM_Type__c = 'MSP',Team_Member__c = opp.SAM__c,Note__c='--');
         oppSAMSplitList.add(oppDSPSAMSplit);
        }
       }
  	 }
    }
     if(oppSAMSplitList.size()>0){
         upsert oppSAMSplitList;
       }
       if(oppPPMSplitList.size()>0){
         upsert oppPPMSplitList;
       }
  }
  	protected override void afterInsert(){
  		updateRollups((List<Opportunity>) Trigger.new);
  		afterInsertUpdate();
  	} 
  	
  	protected override void afterUpdate(){
  		updateRollups((List<Opportunity>) Trigger.new);
  		afterInsertUpdate();
  		//super.afterInsert();
  	}

  	protected override void afterDelete(){
  		updateRollups((List<Opportunity>) Trigger.old);
  	}

  	protected override void afterUndelete(){
  		updateRollups((List<Opportunity>) Trigger.new);
  	}
	
	public static void afterInsertUpdate(){
        List<Opportunity> oppList=(List<Opportunity>)Trigger.new;
        Map<Id,Opportunity> mapOldMap;
        if(Trigger.oldMap!=null && Trigger.oldMap.size()>0){
        		mapOldMap=(Map<Id,Opportunity>)Trigger.oldMap;
        }
        if(oppList!=null && oppList.size()>0){
            Set<Id> oppIDs=new Set<Id>();
            for(Opportunity o:oppList){
                if(mapOldMap!=null && mapOldMap.containsKey(o.Id) && o.Booked_Date__c!=mapOldMap.get(o.Id).Booked_Date__c){
                    oppIDs.add(o.Id);
                }
            }
            if(oppIDs.size()>0){
                List<OpportunityLineItem> listOLI=[Select Id,OpportunityId,Opportunity.Booked_Date__c,CX911_Opportunity_Line_Item_Booked_Date__c From OpportunityLineItem Where OpportunityId=:oppIDs];
                for(OpportunityLineItem oli:listOLI){
                    oli.CX911_Opportunity_Line_Item_Booked_Date__c=oli.Opportunity.Booked_Date__c;
                }
                TriggerHandler.bypass('OpportunityTriggerHandler');
                update listOLI;
            }
        }
	}
	
    public static void updateRollups(List<Opportunity> listOpportunity){
    		/*if(listOpportunity!=null && listOpportunity.size()>0){
    			if(!System.isBatch() && !System.isFuture() && !System.isScheduled()){
    				Map<Id,Opportunity> mapSP=new Map<Id,Opportunity>(listOpportunity);
    				updateRollupsFuture(mapSP.keySet());
    			}
    		}	*/
    }	
   /* @future    	
    public static void updateRollupsFuture(Set<Id> setOppIDs){
    		if(setOppIDs!=null && setOppIDs.size()>0){
    			Set<Id> setExcludeCampaigns=new Set<Id>{'70140000000Tm0gAAC','70140000001LPHRAA4','70140000000F4uqAAC','70140000000Tm0WAAS','701400000004ti7AAA'};
    			List<Opportunity> listOpps=[Select Id,CampaignId,Connector__c From Opportunity Where Id=:setOppIDs ALL ROWS];
    			Set<Id> campaignIDs=new Set<Id>();
    			Set<Id> connectorIDs=new Set<Id>();
    			for(Opportunity o:listOpps){
    				if(!setExcludeCampaigns.contains(o.CampaignId)){
    					campaignIDs.add(o.CampaignId);
    				}
    				connectorIDs.add(o.Connector__c);
    			}
    			if(campaignIDs.size()>0){
    				Map<Id,Campaign> mapCampaigns=new Map<Id,Campaign>();
				AggregateResult[] groupedResults=[Select CampaignId,sum(BookedValue__c) TotalBookedValue,count(Id) DingCount 
													From  Opportunity 
													Where Type = 'New' AND Ding_Date__c!=null AND IsDeleted=false 
													Group By CampaignId 
													Having CampaignID=:campaignIDs]; 
				for (AggregateResult ar : groupedResults){
					mapCampaigns.put(String.valueOf(ar.get('CampaignId')),new Campaign(Id=String.ValueOf(ar.get('CampaignId')),TotalBookedValue__c=Double.valueOf(ar.get('TotalBookedValue')),DingCount__c=Integer.valueOf(ar.get('DingCount'))));
				}
				//by pass account trigger 
				TriggerHandler.bypass('CampaignTriggerHandler');
				Database.SaveResult[] dsrList=Database.update(mapCampaigns.values(),false);
				Utility.createApexLog('OpportunityTriggerHandler', dsrList,true);
				TriggerHandler.clearBypass('CampaignTriggerHandler');					    				
    			}
    			if(connectorIDs.size()>0){
    				List<Connector__c> conList=new List<Connector__c>();
				AggregateResult[] groupedResults=[select Connector__c,count(Id) NoClosedWonOpps From Opportunity Where StageName='Closed Won' group by Connector__c
													Having Connector__c=:connectorIDs]; 
				for (AggregateResult ar : groupedResults){
					conList.add(new Connector__c(Id=String.valueOf(ar.get('Connector__c')),No_Closed_Won_Opps__c=Integer.valueOf(ar.get('NoClosedWonOpps'))));
				} 
				Database.SaveResult[] dsrList=Database.update(conList,false);
				Utility.createApexLog('OpportunityTriggerHandler', dsrList,true);				   				
    			}
    		} 
    }	*/
    //Helper Methods
    //IBST-6181
    //Disable Delete on Opportunities when Order is Complete
    protected override void beforeDelete(){
    Set<Id> oppIDSet = new Set<Id>();
    for( Opportunity opp : (List<Opportunity>)Trigger.old){
       oppIDSet.add(opp.id);
    }
    List<CameleonCPQ__Quote__c> closedProsQuoteId = [Select Id,OpportunityId__c from CameleonCPQ__Quote__c where CameleonCPQ__Quote__c.OPStatus__c = 'Complete' AND OpportunityId__c IN :oppIDSet];
    Set<Id> prosQuoteID = new  Set<Id>();
    for (CameleonCPQ__Quote__c cpq : closedProsQuoteId){
       prosQuoteID.add(cpq.id);
    }
    for( Opportunity opp : (List<Opportunity>)Trigger.old){
    	if(prosQuoteID.contains(opp.PROS_Order_Quote__c)){
        opp.addError('You cannot delete the Opportunity if Pros Quote Order Status is Complete.');
     	}
    }
 }
}