Dev/src/Sertifi E-Sign for Salesforce.com/objects/Contact.object
<CustomObject>
</CustomObject>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>mk_customer_fit_avatax_score__c</fullName>
        <label>MK Customer Fit Score AvaTax</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>mk_lead_avatax_score__c</fullName>
        <label>MK Lead Score AvaTax</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Most_Recent_Conversion_Date__c</fullName>
        <description>Populated by Eloqua when a contact comes through  to Salesforce from an Eloqua form
Integrated: Yes
Marketing: Jessica Davis</description>
        <label>Most Recent Conversion Date</label>
        <type>Date</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Partner_Contact_Not_Found_Email_Sent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Partner Contact Not Found Email Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Partner_Rep_Email__c</fullName>
        <label>Partner Rep Email</label>
        <type>Email</type>
    </fields>

FullQa New/src/objects/Contact.object
    <fields>
        <fullName>Prior_Channel_Partner_Name_Change_Date__c</fullName>
        <description>https://jira.avalara.com/browse/IBST-7371</description>
        <label>Prior Channel Partner Name Change Date</label>
        <type>Date</type>
    </fields>

FullQa New/src/objects/Individual.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FullQa New/src/objects/KeyPairValue__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To store Opportunity Type and Meeting type for EventTriggerHandler</description>
    <fields>
        <fullName>Values__c</fullName>
        <label>Values</label>
        <type>TextArea</type>
    </fields>
    <label>KeyPairValue</label>
</CustomObject>

FullQa New/src/Conversica/objects/Lead.object
<CustomObject>
</CustomObject>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>mk_customer_fit_avatax_score__c</fullName>
        <label>MK Customer Fit Score AvaTax</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>mk_lead_avatax_score__c</fullName>
        <label>MK Lead Score AvaTax</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>Most_Recent_Conversion_Date__c</fullName>
        <description>Eloqua to populate date that lead came through a Form from Eloqua
Integrated: Yes
Marketing: Jessica Davis</description>
        <label>Most Recent Conversion Date</label>
        <type>Date</type>
    </fields>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>OpportunitySubType__c</fullName>
        <description>*Revised 7/1/15 - Used to direct Lead routing based on Business units
Integrated: Yes, coming through on all Eloqua forms, essential to lead assignment rules and redirection of existing leads
Marketing: Jessica Davis</description>
        <label>Opportunity SubType</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Opportunity_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ACP</fullName>
                </value>
                <value>
                    <fullName>AvaTax</fullName>
                </value>
                <value>
                    <fullName>BevAlc</fullName>
                </value>
                <value>
                    <fullName>BizDev</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>CertCapture</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Cross-border</fullName>
                </value>
                <value>
                    <fullName>DSP</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Excise</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>MatrixMaster</fullName>
                </value>
                <value>
                    <fullName>MSP</fullName>
                </value>
                <value>
                    <fullName>MSP-Payroll</fullName>
                </value>
                <value>
                    <fullName>MyLodge</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>SOHO</fullName>
                </value>
                <value>
                    <fullName>TrustFile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>Partner_Contact_Not_Found_Email_Sent__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is being used in LeadTrigger. If Partner_Rep_Email__c field is populated and no contact is found then code will put current time stamp in this field and WF will send email to  pmm@avalara.com</description>
        <label>Partner Contact Not Found Email Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>Partner_Rep_Email__c</fullName>
        <label>Partner Rep Email</label>
        <type>Email</type>
    </fields>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>Partner_Territory__c</fullName>
        <description>https://jira.avalara.com/browse/ITBSE-941</description>
        <label>Partner Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACP Breadth</fullName>
                </value>
                <value>
                    <fullName>ACP East</fullName>
                </value>
                <value>
                    <fullName>ACP West</fullName>
                </value>
                <value>
                    <fullName>APAC-India</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                </value>
                <value>
                    <fullName>CertCapture</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>DSP</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Excise</fullName>
                </value>
                <value>
                    <fullName>GEO MSP - Central</fullName>
                </value>
                <value>
                    <fullName>GEO MSP - GL</fullName>
                </value>
                <value>
                    <fullName>GEO MSP - NE</fullName>
                </value>
                <value>
                    <fullName>GEO MSP - NW</fullName>
                </value>
                <value>
                    <fullName>GEO MSP - SE</fullName>
                </value>
                <value>
                    <fullName>GEO MSP - SW</fullName>
                </value>
                <value>
                    <fullName>Inside MSP</fullName>
                </value>
                <value>
                    <fullName>Marketing Vendor</fullName>
                </value>
                <value>
                    <fullName>National ACP</fullName>
                </value>
                <value>
                    <fullName>National MSP</fullName>
                </value>
                <value>
                    <fullName>National MSP - Premier</fullName>
                </value>
                <value>
                    <fullName>National SI</fullName>
                </value>
                <value>
                    <fullName>SOHO</fullName>
                </value>
                <value>
                    <fullName>Unsigned MSP</fullName>
                </value>
                <value>
                    <fullName>Unwilling to Engage</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>PartnerName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Track the Partner responsible for bringing in the Lead
Integrated: Yes (Partner Portal)
Change: Level 1 
Custodian: VP Partner Management / Balz Wyss</description>
        <inlineHelpText>The Partner responsible for bringing in the Lead</inlineHelpText>
        <label>Channel Partner Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>PartnerNumber__c</fullName>
        <formula>PartnerName__r.PartnerNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Number</label>
        <type>Text</type>
    </fields>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purpose: Track the partner portal user who submitted this lead - changed Label from Portal contact to Channel Partner Sales Rep 10.7.15
Integrated: Yes
Change: Level 1 
Custodian: Partner Portal / VP Partner Operations</description>
        <inlineHelpText>Partner portal user contact. Maps to Channel Sales Rep on the opportunity.</inlineHelpText>
        <label>Channel Partner Sales Rep</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>

FullQa New/src/objects/Lead.object
    <fields>
        <fullName>Prior_Channel_Partner_Name_Change_Date__c</fullName>
        <description>https://jira.avalara.com/browse/IBST-7371</description>
        <label>Prior Channel Partner Name Change Date</label>
        <type>Date</type>
    </fields>

Prod/src/objects/Response_Velocity__c.object
<CustomObject>
    <description>https://wiki.avalara.com/pages/viewpage.action?pageId=292769310</description>
    <fields>
        <fullName>Assignment_Date_Time__c</fullName>
        <description>https://wiki.avalara.com/pages/viewpage.action?pageId=292769310</description>
        <label>Assignment Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Response Velocities</relationshipLabel>
        <relationshipName>Response_Velocities_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Response Velocities</relationshipLabel>
        <relationshipName>Response_Velocities_Lead</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MQL_Date_Time__c</fullName>
        <description>https://wiki.avalara.com/pages/viewpage.action?pageId=292769310</description>
        <label>MQL Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Conversion_Date__c</fullName>
        <label>Most Recent Conversion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Processing_Date_Time__c</fullName>
        <description>https://wiki.avalara.com/pages/viewpage.action?pageId=292769310
https://jira.avalara.com/browse/ITBSE-563?filter=-1</description>
        <label>Processing Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Working_Date_Time__c</fullName>
        <description>https://wiki.avalara.com/pages/viewpage.action?pageId=292769310
https://jira.avalara.com/browse/ITBSE-563?filter=-1</description>
        <label>Working Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Response Velocity</label>
    <nameField>
        <displayFormat>RV-{0000}</displayFormat>
        <label>Response Velocity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Velocities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev/src/classes/LeadTriggerHandlerTest.cls
@isTest
private class LeadTriggerHandlerTest {
      @testSetup static void setup() {
     //  createCustomSetting();
     }
     
   /*public static void createCustomSetting(){
     //Setup custom setting
       List<KeyPairValue__c> listKeyPairValue=new List<KeyPairValue__c>(); 
       listKeyPairValue.add(new KeyPairValue__c(Name='Boomi_API_URL_Sandbox',Values__c='http://api.salesforce.com/'));
       listKeyPairValue.add(new KeyPairValue__c(Name='Boomi_API_Key',Values__c='123456'));
       listKeyPairValue.add(new KeyPairValue__c(Name='Boomi_API_URL_Production',Values__c='http://api.salesforce.com/'));
       listKeyPairValue.add(new KeyPairValue__c(Name='ZTBuyAPICaseSafeID ',Values__c='00533000003RbvNAAS '));
       listKeyPairValue.add(new KeyPairValue__c(Name='EloquaAvalaraCaseSafeID ',Values__c='00540000000yXrwAAE '));
       insert listKeyPairValue;
    }*/
    //https://jira.avalara.com/browse/SFCOM-8722?filter=-1
    static testMethod void testLinkPartnerWithContact() {
        Test.startTest();
        //Create partner account
        Id partnerAccountRecordTypeId=[select id From RecordType Where sObjectType='Account' and DeveloperName='Partner_Certification' limit 1].Id;
        Account partnerAccount=TestUtil.createAccount(partnerAccountRecordTypeId,1,false)[0];
        partnerAccount.ActivePartner__c =true;
        partnerAccount.PartnerNumber__c = '1234';
        insert partnerAccount;
        Contact partnerContact=TestUtil.createContact(partnerAccount.Id,1,false)[0];
        partnerContact.Email='partnercontact@example.com';
        insert partnerContact;  
           
        Test.stopTest();
        List<Lead> listLead=TestUtil.createLead(100,true);
        for(Lead l:[Select Id,PartnerName__c,Portal_Contact__c,Partner_Rep_Email__c,Partner_Contact_Not_Found_Email_Sent__c From Lead Where Id=:listLead]){
                System.assertEquals(l.PartnerName__c,null);
                System.assertEquals(l.Portal_Contact__c,null);
                System.assertEquals(l.Partner_Rep_Email__c,null);
                System.assertEquals(l.Partner_Contact_Not_Found_Email_Sent__c,0);           
        }
        
        for(Lead l:listLead){
                l.Partner_Rep_Email__c='test@example.com';
        }
        update listLead;
        for(Lead l:[Select Id,PartnerName__c,Portal_Contact__c,Partner_Rep_Email__c,Partner_Contact_Not_Found_Email_Sent__c From Lead Where Id=:listLead]){
                System.assertEquals(l.PartnerName__c,null);
                System.assertEquals(l.Portal_Contact__c,null);
                System.assertNotEquals(l.Partner_Rep_Email__c,null);
                System.assertEquals(l.Partner_Contact_Not_Found_Email_Sent__c,1);           
        }     
        for(Lead l:listLead){
                l.Partner_Rep_Email__c=partnerContact.Email;
        }
        update listLead;
        for(Lead l:[Select Id,PartnerName__c,Portal_Contact__c,Partner_Rep_Email__c,Partner_Contact_Not_Found_Email_Sent__c From Lead Where Id=:listLead]){
                System.assertEquals(l.PartnerName__c,partnerAccount.Id);
                System.assertEquals(l.Portal_Contact__c,partnerContact.Id);
                System.assertEquals(l.Partner_Rep_Email__c,partnerContact.Email);
                System.assertEquals(l.Partner_Contact_Not_Found_Email_Sent__c,1);           
        }            
       
    }
    //https://jira.avalara.com/browse/IBST-7371
    static testMethod void testPartnerContactUpdate6MonthsBefore() {
        //Create partner account
        Id partnerAccountRecordTypeId=[select id From RecordType Where sObjectType='Account' and DeveloperName='Partner_Certification' limit 1].Id;
        Account partnerAccount=TestUtil.createAccount(partnerAccountRecordTypeId,1,false)[0];
        partnerAccount.ActivePartner__c =true;
        partnerAccount.PartnerNumber__c = '1234';
        insert partnerAccount;
        //Create an account
        Id customerAccountTypeId=[Select Id from RecordType where DeveloperName='Customer_Account_Type' limit 1].Id;
        Account customerAccount =TestUtil.createAccount(customerAccountTypeId,1,false)[0];
        customerAccount.ActivePartner__c =true;
        customerAccount.PartnerNumber__c = '1234';
        insert customerAccount;
        String EloquaAvalaraCaseSafeID='';
        EloquaAvalaraCaseSafeID =KeyPairValue__c.getInstance('EloquaAvalaraCaseSafeID').Values__c;  
        USer u = [Select id from User where id =: EloquaAvalaraCaseSafeID];
        Test.startTest();   
        Lead lead=TestUtil.createLead(1,false)[0];
        lead.Prior_Channel_Partner_Name_Change_Date__c = system.today();    
        lead.PartnerName__c =  customerAccount.id;
        insert lead;
        
        System.runAs(u){
          lead.PartnerName__c =  partnerAccount.id;
          update lead;
        }
        Test.stopTest();   
    }
    
     //https://jira.avalara.com/browse/IBST-7371
    static testMethod void testPartnerContactUpdate6MonthsAfter() {
            //Create partner account
            Id partnerAccountRecordTypeId=[select id From RecordType Where sObjectType='Account' and DeveloperName='Partner_Certification' limit 1].Id;
        Account partnerAccount=TestUtil.createAccount(partnerAccountRecordTypeId,1,false)[0];
        partnerAccount.ActivePartner__c =true;
        partnerAccount.PartnerNumber__c = '1234';
        insert partnerAccount;
        //Create an account
        Id customerAccountTypeId=[Select Id from RecordType where DeveloperName='Customer_Account_Type' limit 1].Id;
        Account customerAccount =TestUtil.createAccount(customerAccountTypeId,1,false)[0];
        customerAccount.ActivePartner__c =true;
        customerAccount.PartnerNumber__c = '1234';
        insert customerAccount;
        String EloquaAvalaraCaseSafeID='';
        EloquaAvalaraCaseSafeID =KeyPairValue__c.getInstance('EloquaAvalaraCaseSafeID').Values__c;  
        USer u = [Select id from User where id =: EloquaAvalaraCaseSafeID];
        Test.startTest();   
        Lead lead=TestUtil.createLead(1,false)[0];
        lead.Prior_Channel_Partner_Name_Change_Date__c = Date.newInstance(2016, 12, 9);    
        lead.PartnerName__c =  customerAccount.id;
        insert lead;
        
        System.runAs(u){
          lead.PartnerName__c =  partnerAccount.id;
          update lead;
        }
        Test.stopTest();   
    }
    //https://jira.avalara.com/browse/IBST-8008
    //https://jira.avalara.com/browse/ITBSE-941?filter=-1
     //Devloper : Payal Bhawnani 01/23/2018
    static testMethod void testLeadconversion() {
           List<Lead> listL=TestUtil.createLead(3,false);
           Lead acpLead=listL[0];
           acpLead.status = 'Converted';
           acpLead.OpportunitySubType__c='ACP';
           acpLead.Partner_Territory__c='Brazil';
           Lead dspLead=listL[1];
           dspLead.status = 'Converted';
           dspLead.OpportunitySubType__c='DSP';
           dspLead.Partner_Territory__c='Brazil';
           Lead mspLead=listL[2];
           mspLead.status = 'Converted';
           mspLead.OpportunitySubType__c='MSP';
           mspLead.Partner_Territory__c='Brazil';                  
           insert listL;
           LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
           for(Lead l:listL){
        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(l.id);
        lc.setConvertedStatus(convertStatus.MasterLabel);
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());
           }
    }
    static testMethod void testResponseVelocity(){
            //create lead and setup initial fields
            Lead l=TestUtil.createLead(1,false)[0];
            l.Status=Constants.LEAD_STATUS_MQL;
            l.Most_Recent_Conversion_Date__c=Date.today();
            insert l;
            
            //validate that response velocit was cretead and MQL date time was populated
            List<Response_Velocity__c> rvList=[Select Id,MQL_Date_Time__c,Assignment_Date_Time__c,Processing_Date_Time__c,Working_Date_Time__c From Response_Velocity__c Where Lead__c=:l.Id];
            system.assertEquals(1,rvList.size());    
            system.assertNotEquals(NULL,rvList[0].MQL_Date_Time__c);
            system.assertEquals(NULL,rvList[0].Processing_Date_Time__c);
            system.assertEquals(NULL,rvList[0].Working_Date_Time__c);
            system.assertEquals(NULL,rvList[0].Assignment_Date_Time__c);
            //change status to processing to populate processing date time
            LeadTriggerHandler.afterInsertUpdateExecuted=false;
            l.Status=Constants.LEAD_STATUS_PROCESSING;
            update l;
            //change status to working to populate working date time
            LeadTriggerHandler.afterInsertUpdateExecuted=false;
            l.Status=Constants.LEAD_STATUS_WORKING;
            update l;   
            //change owner to queue and then change it back to current user to populate assignment date time
            LeadTriggerHandler.afterInsertUpdateExecuted=false;
            l.OwnerId=[Select Id,Queue.Name,Queue.Id From QueueSObject Where sObjectType='Lead' limit 1].Queue.Id;
            update l; 
            LeadTriggerHandler.afterInsertUpdateExecuted=false;
            l.OwnerId=Userinfo.getUserId();
            update l;  
            //convert lead to validate that response volocity is moved to converted contact 
            LeadTriggerHandler.afterInsertUpdateExecuted=false;   
        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1]; 
        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(l.id);
        lc.setConvertedStatus(convertStatus.MasterLabel);
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());     
        //validate all fields are populated
        rvList=[Select Id,MQL_Date_Time__c,Processing_Date_Time__c,Assignment_Date_Time__c,Working_Date_Time__c,Lead__c,Contact__c From Response_Velocity__c Where Lead__c=:l.Id];
            system.assertEquals(1,rvList.size());    
            system.assertNotEquals(NULL,rvList[0].MQL_Date_Time__c);
            system.assertNotEquals(NULL,rvList[0].Processing_Date_Time__c);
            system.assertNotEquals(NULL,rvList[0].Working_Date_Time__c);    
            system.assertNotEquals(NULL,rvList[0].Assignment_Date_Time__c);
            system.assertNotEquals(NULL,rvList[0].Lead__c); 
            system.assertNotEquals(NULL,rvList[0].Contact__c);                                                      
    }
    static testMethod void testGDPRProcess(){
    		try{
	    		String email='testGDPR@example.com';
			Individual inv=new Individual(Email__c=email,LastName='lastname',ShouldForget=true);
			insert inv;    	
	    		//create lead and setup initial fields
	    		Lead l=TestUtil.createLead(1,false)[0];
	    		l.Email=email;
	    		insert l;  
    		}
    		catch(Exception e){
			Boolean expectedExceptionThrown =  (e.getMessage().contains(Constants.LEAD_CANNOT_INSERT_UPDATE_LEAD_FOR_GDPR)) ? true : false;
			System.AssertEquals(expectedExceptionThrown, true);    			
    		}  	
    } 
     static testMethod void testResponseVelocityAvaTax(){
            //create lead and setup initial fields
            Lead l=TestUtil.createLead(1,false)[0];
            l.Status=Constants.LEAD_STATUS_MQL;
            l.Most_Recent_Conversion_Date__c=Date.today();
            l.OpportunitySubType__c='AvaTax';
            l.mk_lead_avatax_score__c = 45;
            l.mk_customer_fit_avatax_score__c=90;
            l.Offer__c= Lead.Offer__c.getDescribe().getPicklistValues()[0].getValue();
            l.Method_of_Contact_Lead__c = Lead.Method_of_Contact_Lead__c.getDescribe().getPicklistValues()[0].getValue();
            insert l;
         
            //validate that response velocit was cretead and MQL date time was populated
            List<Response_Velocity__c> rvList=[Select Id,Opportunity_SubType__c,MK_Lead_Score__c,MK_Customer_Fit_Score__c,Most_Recent_Conversion_Date__c,Offer__c,Method_of_Contact__c From Response_Velocity__c Where Lead__c=:l.Id];
            system.assertEquals(1,rvList.size());    
            system.assertNotEquals(NULL,rvList[0].Opportunity_SubType__c);
            system.assertNotEquals(NULL,rvList[0].MK_Lead_Score__c);
            system.assertNotEquals(NULL,rvList[0].MK_Customer_Fit_Score__c);
            system.assertNotEquals(NULL,rvList[0].Most_Recent_Conversion_Date__c);
            system.assertNotEquals(NULL,rvList[0].Offer__c);
            system.assertNotEquals(NULL,rvList[0].Method_of_Contact__c);                                                                 
    }   
      static testMethod void testResponseVelocityCC(){
            //create lead and setup initial fields
            Lead l=TestUtil.createLead(1,false)[0];
            l.Status=Constants.LEAD_STATUS_MQL;
            l.Most_Recent_Conversion_Date__c=Date.today();
            l.OpportunitySubType__c='CertCapture';
            l.MK_Lead_Score_CC__c = 45;
            l.MK_Customer_Fit_Score_CC__c=90;
            l.Offer__c= Lead.Offer__c.getDescribe().getPicklistValues()[0].getValue();
            l.Method_of_Contact_Lead__c = Lead.Method_of_Contact_Lead__c.getDescribe().getPicklistValues()[0].getValue();
            insert l;
         
            //validate that response velocit was cretead and MQL date time was populated
            List<Response_Velocity__c> rvList=[Select Id,Opportunity_SubType__c,MK_Lead_Score__c,MK_Customer_Fit_Score__c,Most_Recent_Conversion_Date__c,Offer__c,Method_of_Contact__c From Response_Velocity__c  Where Lead__c=:l.Id];
            system.assertEquals(1,rvList.size());    
            system.assertNotEquals(NULL,rvList[0].Opportunity_SubType__c);
            system.assertNotEquals(NULL,rvList[0].MK_Lead_Score__c);
            system.assertNotEquals(NULL,rvList[0].MK_Customer_Fit_Score__c);
            system.assertNotEquals(NULL,rvList[0].Most_Recent_Conversion_Date__c);
            system.assertNotEquals(NULL,rvList[0].Offer__c);
            system.assertNotEquals(NULL,rvList[0].Method_of_Contact__c);                                                             
    }         
}